### ISSUE TITLE
Unable to convert classes into dex format. See the Console for details.

### ISSUE THREAD

**Issue by Ddfh** [playgameservices/play-games-plugin-for-unity#858] opened 2015-12-11 20:04 UTC
I'm using Unity 4.6.8 and I have the actual android-sdk and the actual java development kit. I used the package 0.9.26. (This version works). 

Now, I saw, that there is a newer version 0.9.27 (28 days ago). So, I deleted in my unity assets folder "GooglePlayGames" folder,"Plugins" folder and the created script like GPGSIds.cs. Then I added the new package. No errors. 

Then I clicked setup. (Window > Google play games > Setup > Android Setup). One problem here is, that the constant class is not created! Nothing in the assets folder.

Now  when I try to build & run the project I get this.

Error building Player: CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
C:/Program Files/Java/jdk1.8.0_66\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/android-sdk\tools" -Dfile.encoding=UTF8 -jar "C:/Program Files (x86)/Unity/Editor/Data/BuildTargetTools/AndroidPlayer\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/AnimRes;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/AnimatorRes;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/AnyRes;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/ArrayRes;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/AttrRes;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/BinderThread;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/BoolRes;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/CallSuper;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/CheckResult;

...

**Comment by claywilkinson** [comment] 2015-12-11 20:53
It looks like you have 2 android support jars included in the Plugins/Android directory (or subdirectories).

**Comment by Ddfh** [comment] 2015-12-11 21:16
In "Plugins \ Android", I only have:
support-annotations-23.1.1.jar
support-v4-23.1.1.aar

Plugins \ Android \ MainLibProj \ libs:
play-games-plugin-support.jar

Plugins \ Android \ libs:
android-support-v4.jar

That's everything.

**Comment by claywilkinson** [comment] 2015-12-11 21:32
Delete Plugins \ Android \ libs:
android-support-v4.jar which overlaps with support-v4-23.1.1.aar

**Comment by Ddfh** [comment] 2015-12-11 21:43
Delete?
OK. Is "support-v4-23.1.1.aar" a new version of "android-support-v4.jar"?

I deleted "android-support-v4.jar" in the libs folder. Now I can't sign in. Nothing happens.

Also the "GPGSIds.cs" is not created.

**Comment by claywilkinson** [comment] 2015-12-11 21:46
Sounds like you got past the building phase :+1: 

The GPGSIds.cs is created by running Window>Google PlayGames>Setup>Android Setup...  I suggest running that again.

Then build and run on a device.  If you can't sign in, can share the log?

**Comment by Ddfh** [comment] 2015-12-11 21:53
I clicked "Setup". Like this image here:
https://github.com/playgameservices/play-games-plugin-for-unity/raw/master/source/docgen/AndroidSetup.png

The file is not created in the assets folder.

**Comment by claywilkinson** [comment] 2015-12-11 21:59
Hmm. Strange. Are there errors in the console? Does it have the alert box, " Success Setup completed Successfully"?

**Comment by Ddfh** [comment] 2015-12-11 22:03
Yes. Alert box says. "Success" and no errors.

**Comment by claywilkinson** [comment] 2015-12-18 17:16
Did you get your build issues resolved?  Is it OK to close this issue?

**Comment by Ddfh** [comment] 2015-12-18 20:55
No. The actual patch is not working. Still the GPGSIds.cs file is not created. 

I'm using Unity 4.6.8 and the package 0.9.26. (0.9.26 works without problems)

**Comment by Ddfh** [comment] 2015-12-21 11:55
I just downloaded a fresh copy of Unity 4.7.0. The new package "GooglePlayGamesPlugin-0.9.27a.unitypackage" also not generates the GPGSIds.cs file.

**Comment by claywilkinson** [comment] 2016-01-04 17:09
The old-builds folder just bloats up the repository.  You can get to older versions of the plugin in the current-builds directory, and click on "History" to see older versions.

**Comment by claywilkinson** [comment] 2016-01-27 20:24
OK to close this one?

**Comment by Ddfh** [comment] 2016-01-29 13:30
Yes. You can close it. Thank you!

**Closed** 2016-01-29 16:21 UTC

**Comment by GabLeRoux** [comment] 2016-02-05 02:38
Also getting this on latest `0.9.30`, I tried a few other versions including `0.9.26` and it does the same. My `Assets/GPGSIds.cs` file seems to be generated correctly. I suspect a conflicting plugin as I wasn't able to reproduce on a blank unity project.

Someone asked a [question on unity answers last october](http://answers.unity3d.com/questions/1080401/commandinvokationfailure-unable-to-convert-classes-1.html) concerning this.
