### ISSUE TITLE
crash on sign in 

### ISSUE THREAD

**Issue by XblakninjaX** [playgameservices/play-games-plugin-for-unity#849] opened 2015-12-08 18:52 UTC
I followed #801 with the second option and when i start the app up on my phone it crashes immediately.

**Comment by claywilkinson** [comment] 2015-12-08 20:15
Can you share the log of the crash?  That will help diagnose the issue.

**Comment by XblakninjaX** [comment] 2015-12-10 13:14
@claywilkinson I am getting this when i test it in unity  i put a script to see if i can log in and i get this

Authentication failed
UnityEngine.Debug:Log(Object)
Signin:<Start>m__E8(Boolean) (at Assets/Scripts/Signin.cs:21)
GooglePlayGames.BasicApi.DummyClient:Authenticate(Action`1, Boolean) (at Assets/GooglePlayGames/BasicApi/DummyClient.cs:33)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1, Boolean) (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs:305)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1) (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs:275)
GooglePlayGames.PlayGamesLocalUser:Authenticate(Action`1) (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesLocalUser.cs:48)
Signin:Start() (at Assets/Scripts/Signin.cs:12)

**Comment by claywilkinson** [comment] 2015-12-11 01:04
It looks like you are running it in the editor?  I see DummyClient in the call stack.  Play Game Services only work on devices, so you have to test it on an actual device.

**Comment by OracleParadiser** [comment] 2015-12-15 00:33
I also have crash on Unity 5.3 with plugin 27a. In unity it works ok. Looks like wrong manifest. I've done rollback to u5.2.3p3 and plugin v27...

**Comment by OracleParadiser** [comment] 2015-12-15 20:08
[log.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/63131/log.txt)

**Comment by ElSucioSucio** [comment] 2015-12-17 01:39
i think this is happening to me too. i followed #832 and i was able to build with both, Admob and Google Play sevices plugins, however, as soon as my app starts on the phone it stops working and quits.

**Comment by ElSucioSucio** [comment] 2015-12-17 03:19
here is mi error log

GPGservices plugin version 0.9.27a
Admob plugin version 2.3.1
Unity 5.2.2f1

I followed instruction on #832 for both, option 1 and option 2 trying to implement Google Play games + admob. in both cases i was able to make a build of the game. however this leads to some other issues.

option 1 - the game crashes as soon as it starts. not possible to log in.

option 2 - the game plays and the ads are shown, but the authentication into Google Play games is never possible, neither to see the leaderboards or achievements.


next will be the log that appered for the option one of #832 
Option 1 log
[errorGPG-0.9.27a.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/64845/errorGPG-0.9.27a.txt)

please, if someone here knows what would be the cause ro the solution to this, it would be of help for me and for others.

**Comment by claywilkinson** [comment] 2015-12-17 03:26
The error message in the log: `? E/ValidateServiceOp: Application ID () must be a numeric `
Indicates a problem with  the games app id.  This comes from the resources xml that is copied from the Play Games Console and pasted into the setup dialog (Window > Google Play Games > Setup > Android Setup ...)

I suggest copy them again and run setup again.

**Comment by ElSucioSucio** [comment] 2015-12-17 07:21
thank you for your answer. I rechecked that and correcting that app ID number in the appropriate manifest files solved the problem. I hope this information can help others

**Comment by claywilkinson** [comment] 2015-12-18 17:03
Great! thanks for letting us know you got it working.

**Comment by OracleParadiser** [comment] 2015-12-18 17:12
Why it was closed? Crash still present with
GPGservices plugin version 0.9.27a
Admob plugin version 2.3.1
Unity 5.3.0

Problem described ElSucioSucio doesn't related to this case...

**Comment by claywilkinson** [comment] 2015-12-18 17:22
@OracleParadiser  - It looks like there are multiple issues in this thread.  Which one are you referring to?  I looked at the log.txt you uploaded a couple days ago, it is an out of memory issue - which really is not directly related to this plugin, but something else going on in your app?

**Comment by OracleParadiser** [comment] 2015-12-18 17:44
It happens only with 27a and U5.3... With 5.2.3 all works... it crashes immediately after start... I had a similar problem with bad merged manifes... But now i didn't change anything except plugin version and Unity update...

**Comment by claywilkinson** [comment] 2016-01-27 20:21
This has devolved into a multi-headed thread, and many of the heads are resolved.  Please open a new issue if any of you are still having issues.  Feel free to reference this thread so you don't have to re-enter all the details.

Thanks!

**Closed by claywilkinson** 2016-01-27 20:21 UTC

**Comment by mzm0o** [comment] 2016-07-20 00:26
Hello guys,, the problem for me was happened after used and remove Facebook ,, it deleted the gameID ,, so u can add it again or just reset it by window -->google play games -->android setup ,, and thats it ,, unexpectable
