### ISSUE TITLE
crash when i call Authenticate method

### ISSUE THREAD

**Issue by green4you** [playgameservices/play-games-plugin-for-unity#1668] opened 2017-03-31 04:39 UTC
in unity 5.5.0f3, Authenticate is crash

**Comment by siadark** [comment] 2017-04-03 05:49
same here

**Comment by mfburn** [comment] 2017-04-04 10:11
same after update to 5.6

**Comment by claywilkinson** [comment] 2017-04-05 00:05
Not much to go on, can you share a log ?

**Comment by siadark** [comment] 2017-04-05 05:30
found a workaround for this issue (tested already):
#1604

**Comment by claywilkinson** [comment] 2017-04-05 14:15
Thanks for responding.  There will be an updated version of the plugin to work with 10.2 this week.  Closing this issue as a dupe of #1604.

**Closed by claywilkinson** 2017-04-05 14:15 UTC
