### ISSUE TITLE
Imported into existing project, getting an error at runtime.

### ISSUE THREAD

**Issue by treyzania** [playgameservices/play-games-plugin-for-unity#794] opened 2015-11-12 03:10 UTC
I haven't the slightest idea of how to fix it.

    ResolutionException: Cannot find candidate artifact for com.google.android.gms:play-services-games:8.1+
    Google.JarResolver.PlayServicesSupport.DependOn (System.String group, System.String artifact, System.String version)
    GooglePlayGames.BackgroundResolution.AddDependencies () (at Assets/GooglePlayGames/Editor/BackgroundResolution.cs:53)
    GooglePlayGames.BackgroundResolution..cctor () (at Assets/GooglePlayGames/Editor/BackgroundResolution.cs:45)
    Rethrow as TypeInitializationException: An exception was thrown by the type initializer for GooglePlayGames.BackgroundResolution
    System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor (RuntimeTypeHandle type) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Runtime.CompilerServices/RuntimeHelpers.cs:101)
    UnityEditor.EditorAssemblies.ProcessEditorInitializeOnLoad (System.Type type) (at C:/buildslave/unity/build/Editor/Mono/EditorAssemblies.cs:123)
    Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
    System.Reflection.MonoCMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:519)
    System.Reflection.MonoCMethod.Invoke (BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:528)
    System.Reflection.ConstructorInfo.Invoke (System.Object[] parameters) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/ConstructorInfo.cs:77)
    System.Activator.CreateInstance (System.Type type, Boolean nonPublic) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System/Activator.cs:372)
    System.Activator.CreateInstance (System.Type type) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System/Activator.cs:254)
    UnityEditor.AssetPostprocessingInternal.GetTextureProcessorVersions () (at C:/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:253)
    UnityEditor.AssetPostprocessingInternal:GetTextureProcessorVersions()

It appears someone else has a similar problem on the [Unity3D forums](http://forum.unity3d.com/threads/social-interface-experiments.325523/).

**Comment by joserocha3** [comment] 2015-11-12 03:39
I get a similar error, but mine references com.android.support:appcompat, not play services. Bummer cause I swear the version I downloaded yesterday was working.

```
ResolutionException: Cannot find candidate artifact for com.android.support:appcompat-v7:23.1.0+
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for GooglePlayGames.BackgroundResolution
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
```

**Comment by joserocha3** [comment] 2015-11-12 03:46
@treyzania  Actually, the problem is that it is looking for a newer version of the package than what you have downloaded to your Android SDK. In my scenarion I had 23.0.1 installed and it was looking for 23.1.0 or greater. Updating the SDK solved the issue.

\sdk\extras\android\m2repository\com\android\support\appcompat-v7

**Comment by shlapkoff** [comment] 2015-11-13 23:24
Need install or update Android SDK - Extras/Android Support Repository

**Comment by claywilkinson** [comment] 2015-11-19 19:45
Is it working now? OK to close this issue?

**Closed** 2015-12-02 17:12 UTC
