### ISSUE TITLE
Resource '@integer/google_play_services_version' not found in AndroidManifest.xml

### ISSUE THREAD

**Issue by zaferyy** [playgameservices/play-games-plugin-for-unity#2019] opened 2017-11-11 17:16 UTC
Hi,

I have GooglePlayGamesPlugin-0.9.42 and it doesn't work with Gradle build
it says:"Resource '@integer/google_play_services_version' not found in AndroidManifest.xml:35"

when I delete the below meta-data line from GooglePlayGames/Plugins/Android/GooglePlayGamesManifest.plugin/AndroidManifest.xml

        <meta-data android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />

it is working but can not login to google play games platform. if this line is not needed anymore why don't you delete it. if I don't use Gradle it is working but I need Gradle for adding firebase (with a lot of unnecessary plugins).

thanks.

**Comment by jongorr** [comment] 2017-11-14 20:25
Same.

**Comment by alleluso** [comment] 2017-11-14 23:08
Same here

**Comment by sieonK** [comment] 2017-11-16 01:40
I have the same problem. I need a Gradle build, but I can not find a way to solve the problem.

**Comment by supersolid-Justy** [comment] 2017-11-16 12:28
The line from above has to be MOVED into the main AndroidManifest.xml (into the Assets/Plugins/AndroidManifest.xml).

**Comment by zaferyy** [comment] 2017-11-16 16:36
That doesn't solve the problem

**Comment by arodus** [comment] 2017-12-01 09:29
Remove the line from ```GooglePlayGames/Plugins/Android/GooglePlayGamesManifest.plugin/AndroidManifest.xml``` and add the following line to ```Assets/Plugins/AndroidManifest.xml```.

```
<meta-data android:name="google_play_services_version" android:value="GPG_VERSION" />
```
You have to replace ```GPG_VERSION``` with the version you are using. You can find the version in ```res/values/values.xml``` when you unpack the ```play-services-basement-x.y.z.aar```.

**Comment by sshumihin** [comment] 2017-12-01 12:20
Hi arodus.
Your suggestion doesn't work for me because I have a conflict with another plugin DevToDev.

>  Attribute meta-data#com.google.android.gms.version@value value=(11720000) from AndroidManifest.xml:22:62-86
> 	is also present at [:devtodev:] AndroidManifest.xml:64:13-66 value=(@integer/google_play_services_version).
> 	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:22:5-89 to override.
> 

I have added 'tools:replace="android:value"' to my manifest and new an error fired after launch a game.

> InvalidOperationException: There was an error creating a GameServices object. Check for log errors from GamesNativeSDK
>   at GooglePlayGames.Native.PInvoke.GameServicesBuilder.Build

**Comment by OpenLevel** [comment] 2017-12-03 15:39
same here. need a Gradle build

**Comment by arodus** [comment] 2017-12-03 15:52
@sshumihin what does the log say?

**Comment by OpenLevel** [comment] 2017-12-03 16:03
C:\Users\PIMMSong\Source\Repos\RollPlayingGame\Temp\gradleOut\GooglePlayGamesManifest.plugin\build\intermediates\bundles\release\aapt\AndroidManifest.xml:35:28-65: AAPT: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version')

The problem has gone. I don't know why.

then the build succeeded but another error occurred like below :
GamesNativeSDK` : Can't register class ...

**Comment by sshumihin** [comment] 2017-12-04 08:26
@arodus 

```
GRADLE ERROR : colliding-attributes
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UnityEditor.Android.GradleInvokationException:ParseAndShowException()
UnityEditor.Android.PostProcessor.PostProcessRunner:RunAllTasks(PostProcessorContext)
UnityEditor.Android.PostProcessAndroidPlayer:PostProcess(BuildTarget, String, String, String, String, String, String, BuildOptions, RuntimeClassRegistry, BuildReport)
UnityEditor.Android.AndroidBuildPostprocessor:PostProcess(BuildPostProcessArgs)
UnityEditor.PostprocessBuildPlayer:Postprocess(BuildTargetGroup, BuildTarget, String, String, String, Int32, Int32, BuildOptions, RuntimeClassRegistry, BuildReport) (at C:\buildslave\unity\build\Editor\Mono\BuildPipeline\PostprocessBuildPlayer.cs:271)
UnityEditor.BuildPipeline:BuildPlayerInternalNoCheck(String[], String, String, BuildTargetGroup, BuildTarget, BuildOptions, Boolean)
UnityEditor.BuildPipeline:BuildPlayerInternal(String[], String, String, BuildTargetGroup, BuildTarget, BuildOptions) (at C:\buildslave\unity\build\artifacts\generated\common\editor\BuildPipelineBindings.gen.cs:335)
UnityEditor.BuildPipeline:BuildPlayer(String[], String, String, BuildTargetGroup, BuildTarget, BuildOptions) (at C:\buildslave\unity\build\artifacts\generated\common\editor\BuildPipelineBindings.gen.cs:232)
UnityEditor.BuildPipeline:BuildPlayer(BuildPlayerOptions) (at C:\buildslave\unity\build\artifacts\generated\common\editor\BuildPipelineBindings.gen.cs:210)
BuildManager:BuildAndroid(AndroidBuildSystem, AppStore, Boolean, BuildOptions, AndroidTargetDevice, Boolean) (at Assets\Infoshell\Scripts\Editor\BuildManager.cs:127)
MainMenu:BuildAndroidGradleDebug() (at Assets\Infoshell\Scripts\Editor\MainMenu.cs:190)
 
(Filename: Assets/Infoshell/Scripts/Editor/BuildManager.cs Line: 127)

CommandInvokationFailure: Gradle build failed. 
C:/Program Files/Java/jdk1.8.0_111\bin\java.exe -classpath "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-2.14.jar" org.gradle.launcher.GradleMain "assembleDebug"

stderr[
F:\Work\MyProject\Temp\gradleOut\src\main\AndroidManifest.xml:24:62-86 Error:
	Attribute meta-data#com.google.android.gms.version@value value=(11720000) from AndroidManifest.xml:24:62-86
	is also present at [:devtodev:] AndroidManifest.xml:64:13-66 value=(@integer/google_play_services_version).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:24:5-89 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed : Attribute meta-data#com.google.android.gms.version@value value=(11720000) from AndroidManifest.xml:24:62-86
	is also present at [:devtodev:] AndroidManifest.xml:64:13-66 value=(@integer/google_play_services_version).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:24:5-89 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
]
stdout[
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
```

**Comment by arodus** [comment] 2017-12-04 18:20
@sshumihin I was referring to the log from the GamesNativeSDK. Since it seems that you already fixed the bug with the colliding attributes. 
It seems that the analytics plugin you are using does not support google play resolver and already contains all the libraries in it's own unity package. I guess there is some version mismatch between the libraries imported from the plugin and the libs from the resolver.

**Comment by sshumihin** [comment] 2017-12-05 08:17
@arodus I think you are right. Thank you.

**Comment by sshumihin** [comment] 2017-12-05 09:49
@arodus I removed DevToDev plugin and there is another an error:
```

stderr[
D:\MyProject\Temp\gradleOut\src\main\AndroidManifest.xml:23:62-86 Error:
	Attribute meta-data#com.google.android.gms.version@value value=(11720000) from AndroidManifest.xml:23:62-86
	is also present at [:play-services-basement-11.6.2:] AndroidManifest.xml:20:66-119 value=(@integer/google_play_services_version).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:23:5-89 to override.
```
Now the problem is Play-Services-Basement.

**Comment by arodus** [comment] 2017-12-05 12:16
@sshumihin did you also remove the libraries which were imported by the plugin?
Do you have a project to reproduce the error, or can you send a screenshot of the contents of the ```Assets/Plugins/Android``` folder.

**Comment by sshumihin** [comment] 2017-12-05 14:24
@arodus I reproduce the issue on a clean project with GPGS only. 
There is a [video](https://youtu.be/mlS3gHBoanI) how to reproduce.
There is an [Unity project](https://drive.google.com/open?id=1_yefIUYJSZhvfA8AMXNTQAkQtIqKJaWV)

**Comment by sshumihin** [comment] 2017-12-06 12:30
Sorry, I didn't share the video. Update.

**Comment by arodus** [comment] 2017-12-06 20:38
I can build the project without any problem. It could be possible that the reason is the target api level on which you are the building the application. Since the default settings is `Automatic (highest installed)` this could also explain why the build works for me. 

I currently have the following versions installed:
![image](https://user-images.githubusercontent.com/18667020/33684204-c56ad478-dacd-11e7-8fbf-2f246c8deacf.png)

**Comment by sshumihin** [comment] 2017-12-07 00:53
Ok. Seems I figure it out.

I copy the 2 lines from the GPGS manifest to my manifest as is. Then I can build a project.
I don't have to replace "@integer/google_play_services_version" by the gp-basement version.

I will check it tomorrow again.

Note, when you do Android setup again the GPGS manifest recreate. You have to remove 2 lines again.

**Comment by OpenLevel** [comment] 2017-12-07 06:15
I've solved the GamesNativeSDK problem

by add these 2 line to proguard-user.txt :
<pre><code>-keep class com.google.android.gms.** { *; }
-keep interface com.google.android.gms.** { *; }
</code></pre>

**Comment by sshumihin** [comment] 2017-12-12 10:09
I can't use the plugin. 
1. I can't build it because of the conflict with DevToDev. Ok, I fix it but then
1. I can't build it because of "no found resource". Ok, I fix it but then
2. I have a crash on init because Social.localUser is null. Ok, I fix it but then
3. I can't sign in because of an ERROR_ON_AUTHORISED.

I give up. It's the worst plugin I have ever used.

**Comment by creutzfeldt0** [comment] 2017-12-14 08:15
5.  I can't sign in because of an ERROR_ON_AUTHORISED.
same Issue "TokenFragment class not found error #2054"
but not resolved

**Comment by pranavt7** [comment] 2018-01-01 17:48
If I remove the following lines, the apk gets created, but I am not able to authenticate and email and username returns blank - 


        <meta-data android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />

**Comment by Shaitan1805** [comment] 2018-01-14 23:38
Can someone help me please?
Had the same problem that I can't build. Removed the line like in the question in file
GooglePlayGames/Plugins/Android/GooglePlayGamesManifest.plugin/AndroidManifest.xml

Now I can build, but I am not able to login.
In my Directory Assets/Plugins is no AndroidManifest.

Currently I get very frustrated with this package

**Comment by shanta3220** [comment] 2018-01-20 08:02
Weirdly like others I didn't face the GamesNativeSDK problem and arodus's answer solved my problem. may be because I'm also using build tool 26.0.1.

**Comment by shanta3220** [comment] 2018-01-23 13:18
Hello everyone, I faced the same issue as you guys and spent almost 2 days searching for solutions and even used the solution arodus suggested,although it did build the apk but doesn't let me sign in. So I kind of used every solutions I found on the internet and merged them together don't know exactly what actually made it work but it is working now, you can do the same thing and see if it works. 
I'm using unity 2017.2.0f3 and API 27. 
1. Instead of using the current build I used "GooglePlayGamesPlugin-0.9.41", you can find it here: https://github.com/EdgarGomez/UnityGooglePlayGameServices (you better download the whole zip because we will need for later steps).
2. instead of using the current google play services of android I downloaded https://dl-ssl.google.com/android/repository/google_play_services_8298000_r28.zip this is developed by "Andrew S",(thank you!) and put this in Android-Sdk\extras\google after deleting the latest version.
3. Another solution was to add the dependencies in the mainTemplate.gradle:
find the gradle here: Unity\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\GradleTemplates.
just simply add in the mainTemplate.grade:
dependencies {
    compile 'com.google.android.gms:play-services-games:11.0.2'
}
 if you're not sure where to put it then just put it below the fileTree dependency.
4.  Now back to unity I opened "GooglePlayGamesPlugin-0.9.41.unitypackage", after it was done. from EdgarGomez's project(link in step 1) , i copied or override all the .aar files from -'UnityGooglePlayGameServices/Assets/Plugins/Android/" into my project's UnityGooglePlayGameServices/Assets/Plugins/Android/". if you open the unitypackage you may find "only 1 .aar file" in that folder or if all of them are available just delete  them and put his ones. 
5. lastly don't forget to add:
      <activity android:name="com.google.games.bridge.NativeBridgeActivity"
android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
in your AndroidManifest.xml(GooglePlayGames/Plugins/Android/GooglePlayGamesManifest.plugin/) because without this your Leaderboards, achievments probably wouldn't work.

**Comment by claywilkinson** [comment] 2018-01-23 16:47
The manifest attribute has been removed in 0.9.50, so gradle builds will work now without modification/.

**Closed by claywilkinson** 2018-01-23 16:47 UTC

**Comment by BenoitFreslon** [comment] 2018-01-29 16:37
Sorry but when I try to build with gradle I can't sign in too.

Without gradle: http://prntscr.com/i78v42
With gradle: http://prntscr.com/i78vcr

**Comment by aneeshpanoli** [comment] 2018-07-07 16:35
6 months and no progress on this? I can do gradle build but get operationexception error, cant sign in. Everything works fine with the Internal build.

**Comment by j-ito-Tribe** [comment] 2019-04-25 02:36
> 
> 
> The line from above has to be MOVED into the main AndroidManifest.xml (into the Assets/Plugins/AndroidManifest.xml).

I seen the same problem, I have solved with your solution!

**Comment by srcsameer** [comment] 2019-05-02 10:34
Hi! guys i am having the same issue, i am using unity 2018.3.1f1 and i have imported  my old project(it has gpgs 0.9.42) from  unity 2017 to 2018 i was unable to build APKs but after moving The line 
`<meta-data android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />`
from 
Assets\GooglePlayGames\Plugins\Android\GooglePlayGamesManifest.plugin\AndroidManifest.xml
to
F:\Unity_prac\Pong\OnDevelopment\Unity2018\Super_pong\Assets\Plugins\Android\AndroidManifest.xml

i can build the APK but when i am testing it it's crashing after opening.

**Comment by j-ito-Tribe** [comment] 2019-05-17 08:33
Hello srcsameer, did you already resolve the crash issue?
If not, can you post those error logs?

**Comment by srcsameer** [comment] 2019-05-18 07:07
@j-ito-Tribe  thanks for your reply,  but i have solved it. had to add admob app id to F:\Unity_prac
Assets\Plugins\Android\GoogleMobileAdsPlugin\AndroidManifest.xml

**Comment by LifeIsJourney** [comment] 2019-05-18 07:19
> 
> 
> Hi! guys i am having the same issue, i am using unity 2018.3.1f1 and i have imported my old project(it has gpgs 0.9.42) from unity 2017 to 2018 i was unable to build APKs but after moving The line
> `<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />`
> from
> Assets\GooglePlayGames\Plugins\Android\GooglePlayGamesManifest.plugin\AndroidManifest.xml
> to
> Assets\Plugins\Android\AndroidManifest.xml
> 
> i can build the APK but when i am testing it, it's crashing after opening.

If you are using unity for this. You don't have to change anything in  android:name = "". Change andoid:value to your admob id. I think this video will solve this issue
[https://youtu.be/qlRvqi1DAQk](url)

**Comment by victor871129** [comment] 2019-09-05 13:26
GameAnalytics can trigger that error in AndroidManifest.xml
https://gameanalytics.com/docs/item/unity-sdk#android

**Comment by idurvesh** [comment] 2019-09-08 20:37
I disabled Unity's default Android configuration, ran the Playstore resolve, then again enabled default config

**Comment by alamboley** [comment] 2019-09-16 14:49
@victor871129 how did you resolve this?

**Comment by victor871129** [comment] 2019-09-16 19:38
Go to preferences, uncheck the NDK, SDK and JDK checkboxes, click 3 Browse buttons. Then check those NDK, SDK and JDK checkboxes again. Restart Unity app.

**Comment by alamboley** [comment] 2019-09-17 08:23
@victor871129 that did the trick, many thanks!

**Comment by med-the-lord** [comment] 2022-05-28 22:01
> Remove the line from `GooglePlayGames/Plugins/Android/GooglePlayGamesManifest.plugin/AndroidManifest.xml` and add the following line to `Assets/Plugins/AndroidManifest.xml`.
> 
> ```
> <meta-data android:name="google_play_services_version" android:value="GPG_VERSION" />
> ```
> 
> You have to replace `GPG_VERSION` with the version you are using. You can find the version in `res/values/values.xml` when you unpack the `play-services-basement-x.y.z.aar`.

Your suggestion solved my issue, 1M thanks :)
