### ISSUE TITLE
Conflict with Android Ultimate Plugin (Unity Asset)

### ISSUE THREAD

**Issue by rakuzas** [playgameservices/play-games-plugin-for-unity#852] opened 2015-12-09 12:02 UTC
Hello,

I just bought this asset from Unity Asset Store.. After I import this asset.. I cannot build and stuck at dex error.. I contacted the developer and he fix my problem.. But, his method is to delete PlayGameServices plugin.. So I cannot use PlayGames feature anymore.. Can someone guide me how to fix this? I opened the play-games-plugin-support.jar and see nothing much in there.. Hope can fix my problem soon.. Thank you..

Note : I also having same problem with other asset too.. Which having their own jar.. :(

**Comment by SDowd-FD** [comment] 2015-12-09 15:48
Hi,
I am also getting new class conflicts trying to implement this plugin.  The project has a couple of other plugins such as chart boost, Facebook, and AdColony.  Here are my build logs:

CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/bin/java -Xmx2048M -Dcom.android.sdkmanager.toolsdir="/Users/sdowd/Desktop/Temp/Android/sdk/tools" -Dfile.encoding=UTF8 -jar "/Applications/Unity/Unity.app/Contents/PlaybackEngines/AndroidPlayer/Tools/sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/ads/identifier/AdvertisingIdClient;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/ads/identifier/AdvertisingIdClient$Info;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/ads/identifier/AdvertisingIdClient$zza;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzav;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzav$zza;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzav$zza$zza;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zznn;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzno;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zznp;

The plugin is generating all of its  "play-serverices-*.aar" files which seem to be the cause of the conflicts.  I could be wrong.  the conflict could be generated from the play-games-plugin-support.jar.  Is anyone aware of the location of the above classes within this plugin?  Also, what is the best course of action to resolve these conflicts?  I would like to try to avoid ripping open jar files and removing classes bundled inside, but that may not be an option.  

Of note, I have updated all the necessary SDKs and repositories suggested in the Android SDK Manager and should be up to date with each of the necessary pieces.

Any help would be appreciated.

Thanks

**Comment by rakuzas** [comment] 2015-12-09 23:43
I just contacted the developer few times and he keep reply and give support.. 

For what I see.. This plugin not working with PlayGames plugin.. I contacted him and he keep telling me to follow his instructions.. When I follow, keep getting DEX error.. When I deleted play-games-plugin-support.jar, I got error.. If I delete this asset jar files.. Also getting error.. Its my day 2 try to solve this.. And developer support not much help at all.. He asked me to give my zip project.. And he fixed it.. I can build demo scene and run on my android phone.. But no PlayGames plugin.. Hope anyone can guide us how to do this.. In addition, we already paid for this asset.. :(

**Comment by SDowd-FD** [comment] 2015-12-10 15:49
I manually went through all of the jar files in the project looking for duplicate class definitions.  Once identified, I was able to remove one of our jars that contained duplicate class definitions for things like the AdvertisingIdClient and other related classes.  This allowed the build to complete and run on device.

**Comment by rakuzas** [comment] 2015-12-13 21:18
Can you share which jar your removed its content? Thank you..

**Comment by SDowd-FD** [comment] 2015-12-14 01:04
i needed to remove the *analytics.aar file which defined AdvertisingIdClient and a bunch of other classes which were already included.  also, i removed the post-processing code set to re-import the jar/aar dependencies after it ran once.

**Comment by rakuzas** [comment] 2015-12-14 08:03
Wait a min.. Did you use full version? XD Because I'm not found your mentioned .aar or jar.. I'm using lite version.. Still struggling to make this works.. I already spend 2-3 hours to delete duplicated classes but still failed to build.. Awww..

**Comment by litemesa** [comment] 2015-12-25 17:10
Did someone fix this issue? I use Facebook SDK 7.3.0 and trying to add GooglePlayGamesPlugin - any version of it gives an error:

```
Error building Player: CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
C:\Program Files\Java\jdk1.7.0_75\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Users/Eugene/AppData/Local/Android/sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Landroid/support/annotation/WorkerThread;
	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
	at com.android.dx.command.dexer.Main.processClass(Main.java:732)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at SDKMain.main(SDKMain.java:129)
```

**Comment by gigadrillgames** [comment] 2015-12-26 15:12
@rakuzas  hey it seems you just don't know what you are doing because i successfully integrated this google play games plugin on Android Ultimate Plugin, so i think there's no problem or conflict at all, maybe the problem is the way you setup your project and aside from that i already help you and in return you are spreading this kind of wrong information, don't worry i will show you a proof that i successfully integrated google play services and also please if you are the one that  put a lower ratings on our plugin please kindly modify it because this is so wrong and for the proof here's the link of Android Ultimate Plugin Demo with Google Play Game https://drive.google.com/file/d/0Bw14w3QBZaGxWF9mUjk1aVlGYUU/view and for few write up on this issue http://www.gigadrillgames.com/2015/12/26/integration-of-google-play-games-on-android-ultimate-plugin-issue/ , i hope this will end the spreading of this false information

**Comment by litemesa** [comment] 2015-12-26 16:33
I found solution:
Facebook SDK shipped with android-support-v4.jar, so GooglePlayGamesPlugin (support-annotations-23.1.1.jar + support-v4-23.1.1.aar) - If I leave only one of them all is working good.

**Comment by claywilkinson** [comment] 2016-01-04 16:37
@litemesa thanks for the update.  Where does facebook place their copy of the android-support-v4.jar?

**Comment by ShadoVv91** [comment] 2016-01-22 11:17
Hi
I Had similar problem, and I have solve it. Maybe my solution will be useful for someone.  Besides Google Play Service plugin I'm using Facebook, Game Analytics and Soomla plugins in my project. 

To force plugin to not update libs you have to commment out method OnPostprocessAllAssets in BackgroundResolution.

I've removed support-annotations-23.1.1.jar + support-v4-23.1.1.aar and there were still double definition of classes:  

>UNEXPECTED TOP-LEVEL EXCEPTION:
>java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzat;
>...
>java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zznn;
>...
>java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzqf;

So I've also had to remove play-services-analytics-7.5.0. Now it is working fine.

**Comment by claywilkinson** [comment] 2016-01-27 20:22
OK to close this?

**Comment by ShadoVv91** [comment] 2016-01-27 20:26
I guess, problem is cause more by conflicts with other plugins and it needs separate approache for each case.

**Comment by claywilkinson** [comment] 2016-01-27 20:28
Unfortunately I think that is the case.  We've open sourced how the play-services client libs should be resolved, you can see it here: https://github.com/googlesamples/unity-jar-resolver  Feel free to pass along to other plugin developers.

**Closed by claywilkinson** 2016-01-27 20:28 UTC
