### ISSUE TITLE
Scores not posted on iOS ?

### ISSUE THREAD

**Issue by narger17** [playgameservices/play-games-plugin-for-unity#662] opened 2015-08-15 21:38 UTC
Hi guys, i've got a problem with my iOS build...When i the score is sent, if i open the leaderboards, the score appears on the 'social' tab, but not in the 'worldwide'... everything on the console for ios is ok (certificates) and the code is perfect (on android works without any problem).
What could be?

**Comment by banditdevelopment** [comment] 2015-09-07 12:27
The reason the scores are not on the public leaderboard is due the the signed in user's sharing settings.  The problem is, iOS users can't change their Google Play Games sharing settings, only on Android.

**Comment by banditdevelopment** [comment] 2015-09-07 12:51
@narger17 I have found one way to fix your problem.

By default, Google Play Game Services changes the settings of signed-in users so that their scores are not posted on the "worldwide" leaderboard. On Android, users can change their sharing settings to allow score posting to "worldwide". On iOS, you need to redirect the user to https://plus.google.com/u/0/apps and have them change the " *YOUR GAME* game activity" settings to "public".

Hopefully this is helpful.

**Comment by banditdevelopment** [comment] 2015-09-09 17:46
@claywilkinson Is there a way to automatically have users' scores uploaded to the global leaderboard, or do they need to change their sharing settings no matter what?

I'm curious because I'd like to know if I need to direct my users to change their settings if they want their score posted.

Let me know if I should open this up as a new issue. Thanks.

**Comment by banditdevelopment** [comment] 2015-09-27 21:18
@claywilkinson I don't want to bug you, but do you have any info on this issue? I'm almost ready to release my game, so I want to know if people need to change their Google Plus app settings for the global leaderboard.

**Comment by claywilkinson** [comment] 2015-09-27 21:54
Yes, leaderboard scores on iOS are not public, it is a server side issue. I'll update this thread when I know more.

**Comment by banditdevelopment** [comment] 2015-09-28 14:20
So is it safe to assume that the issue will be fixed in a month or two, or is there any ETA at all?

I'm sure that there are more pressing issues for GPGS, but I just want to know if I should make it a point to let my users know about the global leaderboard problems on iOS.

Thanks,

**Comment by yafarida** [comment] 2015-10-25 17:12
Hi, so it seems that using gpg for iOS is still unacceptable solution(((

**Comment by yafarida** [comment] 2015-10-25 17:14
@claywilkinson any updates for this bug?

**Comment by claywilkinson** [comment] 2015-10-27 16:16
I'll try to track down an update, I don't have an ETA, I'll work on that too.

**Comment by claywilkinson** [comment] 2015-12-01 02:22
There are definitely issues with Google Play Game Services on iOS related to multiplayer and social APIs.  I've been told to communicate that these issues are not going to be addressed in the immediate future.  As a result, you should treat these APIs as "beta" quality.  Please continue to share your experiences using this library on iOS, as your feedback is important to making the library better in the future. 

As there are updates to the iOS SDK, I will share them.

**Comment by justinkmai** [comment] 2015-12-02 21:01
@banditdevelopment is that work around confirmed to work? One of my testers was still unable to see his score after changing his settings to 'public'.

**Comment by banditdevelopment** [comment] 2015-12-02 21:38
It has worked on multiple accounts for me. It should be noted that the scores may not be on the global leaderboard for up to 24 hours.

**Comment by justinkmai** [comment] 2015-12-02 21:41
Glad to hear! Thanks!

**Comment by Naamani** [comment] 2016-02-11 08:58
Just encountered the same issue. @justinkmai - I get the same results as you described above (scores posted by iOS users are hidden from both android and other iOS users as well).

This is bad - 1/4 from my users (IOS users) don't see their score on the leaderboard, which actually leave them out of the game.

**Comment by cecco4** [comment] 2016-04-07 14:31
There are some update? I can't ask the users to set it manually. Also, every time i sign out it doesn't remember the previus settings.

**Comment by claywilkinson** [comment] 2016-04-07 16:21
No update yet.

**Comment by Bjakuja** [comment] 2016-06-22 17:23
Still nothing on this? I get the same problem, our game is published on Play Store and ITunes. For Adroid everything works normal but for IOS no scores are posted yet and we don't know why... Pls help if possible, do i have to switch to Game Center if i want IOS leaderboards or is still doable with GPGS but i am missing something? Thanks

**Comment by mattjackson4** [comment] 2016-07-27 20:19
Is this going to be fixed anytime soon, kind of disables highscore functionality on iOS? Users aren't going to be manually setting this every time.

**Comment by boywithstick** [comment] 2016-12-26 15:34
It's beyond a year's time when this issue was made apparent, has there been any progress on addressing this issue? If this part of the plugin should be treated as “beta quality” for iOS, it should be noted within the read-me. The plugin works great and I'm really happy with all its features. The built in leaderboard UI is so clean, familiar and nice looking that it would be a real shame to craft a custom solution. However, it was incredibly disappointing to hear from several of my friends who downloaded my game to say their high scores did not post to the leaderboards. They were all on iOS.

I tested this myself by beating my high score on my iPhone and my score appears in the leaderboard. If I log in on my Android phone, I can see my score just the same. However, regardless of platform, no one else can see my new leaderboard score. If I beat that leaderboard score I achieved on iOS when logged in on my Android phone, everyone can see the score.

Can we get an update on this, a fix, or should anyone who is expecting this as a solution for a cross-platform leaderboard service look elsewhere?

**Comment by claywilkinson** [comment] 2016-12-27 18:41
There is an update on iOS support - https://android-developers.googleblog.com/2016/12/games-authentication-adopting-google.html.  There issues with Game Services and Google Plus on iOS.  Since Google Plus integration is removed, there will be problems on iOS for things like leaderboards and multiplayer.  Also, new players (players on iOS that do not have an associated Games Profile ) will not be able to sign in at all on iOS.  The symptom is a looping consent screen.

I can't comment on future plans beyond what is in the blog post, but it does say that account creation in iOS is not supported.  I've asked for more information from the product team and when I know more, I will share it.

**Comment by Spud6703** [comment] 2017-02-07 17:25
I've been adding Google Play Games leaderboards to the iOS version of my game as an alternative to Apple's Game Center which has been going downhill rapidly recently both in terms of features and reliability. However, I was disappointed to discover that the social leaderboards don't appear to be working on iOS and that there's no API to add other players to your social leaderboards. This transition from Google+ to Games Profiles seems to be going slow. Please don't ditch the iOS SDK. I'm sure there are plenty of other developers who would prefer to use Google Play Games SDK in their iOS games rather than Game Center. Clay Wilkinson > is there a mailing list I can be added to in order to be kept up to date with any iOS SDK development ? Thanks !

**Comment by yruizw** [comment] 2017-02-28 21:19
Hi there,
Is there any progress or any news about the leaderboards on IOS?
Regards
Yuri

**Comment by claywilkinson** [comment] 2017-03-03 15:01
@Spud6703 (and others) Thanks for the feedback.  If you don't mind, can you email me a quick summary of your thoughts and some info on your company.  I will pass it along to the product management team.  My email address is on my profile.

**Comment by claywilkinson** [comment] 2017-04-06 14:44
The decision was made to discontinue iOS support for iOS: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html

**Closed by claywilkinson** 2017-04-06 14:44 UTC
Labels: iOS
