### ISSUE TITLE
Invalid PBX Project

### ISSUE THREAD

**Issue by Armend** [playgameservices/play-games-plugin-for-unity#725] opened 2015-09-26 02:02 UTC
Hey i am getting an error while i am building the xcode project by building the Unity Project on a MacBook Pro. The Xcode project was build but this Error-Msgs are shown up. Do anyone know how to fix this? Or can i ignore them? 
Without the GoogePlayGames Plugin the building was successful. 

I am using the GPS Version 0.9.25 and Unity 5.2.0f3 Personal Edition.
![invalidpbxproject](https://cloud.githubusercontent.com/assets/2729892/10115269/489b4c82-6402-11e5-8e60-2da669d0a240.png)

Thank you.

**Comment by Armend** [comment] 2015-09-26 13:57
Well, i ignored them and after manually adding the frameworks and linking, the App was successfully builded. (CocoaPods seems not to help here :/ ) Until now i can't find a bug, which could be linked to this Erros-Messages.

**Comment by claywilkinson** [comment] 2015-09-28 17:21
Strange.  Is it easily reproducable for you?  Can you see if there is a pbx file that is non-empty when you get the error?  What version of XCode are you using?

**Comment by claywilkinson** [comment] 2015-10-27 18:55
OK to close this one?

**Closed** 2015-11-24 20:56 UTC

**Comment by heyalistair** [comment] 2016-03-31 09:04
Hello! I was wondering how this was ever resolved? I am encountering the same error, except I can't really ignore it because I have other plugins and post build processes that try to modify the project file as well, but they can't after the cocoapods update in this plugin.

I am also on a MacBook Pro, with OS X 11.4 building for iOS.
GPGS Plugin version is 0.9.32 and Cocoapods is at version 0.39.0

Here is the error:
```
Exception: Invalid PBX project (parsing line 0)
UnityEditor.iOS.Xcode.PBX.Parser.ParseTree () (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/XCode/PBX/Parser.cs:114)
UnityEditor.iOS.Xcode.PBXProjectData.ParseContent (System.String content) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/XCode/PBXProjectData.cs:451)
UnityEditor.iOS.Xcode.PBXProjectData.ReadFromStream (System.IO.TextReader sr) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/XCode/PBXProjectData.cs:458)
UnityEditor.iOS.Xcode.PBXProject.ReadFromStream (System.IO.TextReader sr) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/XCode/PBXProject.cs:868)
UnityEditor.iOS.Xcode.PBXProject.ReadFromString (System.String src) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/XCode/PBXProject.cs:863)
GooglePlayGames.Editor.GPGSPostBuild.UpdateGeneratedPbxproj (System.String pbxprojPath) (at Assets/GooglePlayGames/Editor/GPGSPostBuild.cs:239)
GooglePlayGames.Editor.GPGSPostBuild.OnPostprocessBuild (BuildTarget target, System.String pathToBuiltProject) (at Assets/GooglePlayGames/Editor/GPGSPostBuild.cs:132)
UnityEditor.HostView:OnGUI()
```

I try to open up the workspace file in Xcode and when I click on the Unity-iPhone project, a dialog box tells me "The file couldn’t be opened."

When I try to open up the project file in a text editor, I can see a PBX project file in XML:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
...
```

It looks good, but right before CocoaPodHelper.cs runs update, it is in a JSON-like format, beginning with:
```
// !$*UTF8*$!
{
	archiveVersion = 1;
	classes = {
	};
	objectVersion = 46;
	objects = {
/* Begin PBXBuildFile section */
		03ED4C149B5BDB3B58B3FD81 /* LaunchScreen-iPad.png in Resources */ = {isa = PBXBuildFile; fileRef = D6754BA58EAAF51155D98BDF /* LaunchScreen-iPad.png */; };
...
```

Might that have something to do with it? I'm not sure what the expected behavior is. Thanks for your help!

**Comment by heyalistair** [comment] 2016-03-31 09:10
Ok, hmmmm running `pod update` manually in Terminal gives me:

```
Analyzing dependencies
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface/error_report.rb:13:in `report': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:61:in `report_error'
	from /Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:374:in `handle_exception'
	from /Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:315:in `rescue in run'
	from /Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
	from /usr/local/bin/pod:23:in `load'
	from /usr/local/bin/pod:23:in `<main>'
```
