### ISSUE TITLE
always print : Debug.Log("Resolver version is now: " + _resolver.Version());

### ISSUE THREAD

**Issue by fromsantorini** [playgameservices/play-games-plugin-for-unity#1310] opened 2016-08-05 03:18 UTC
how fix ?!

**Comment by claywilkinson** [comment] 2016-08-09 18:04
Thanks for the feedback.  The code needs to be updated to remove that line or make it less frequent.  
Until the plugin is updated, feel free to delete this line from `Assets/PlayServicesResolver/Editor/PlayServicesResolver.cs`

**Comment by claywilkinson** [comment] 2016-10-06 17:37
Closing as a duplicate of #1361

**Closed by claywilkinson** 2016-10-06 17:37 UTC
