### ISSUE TITLE
Impossible to run on iOS (NSInvalidArgumentException)

### ISSUE THREAD

**Issue by chaky31** [playgameservices/play-games-plugin-for-unity#1407] opened 2016-10-04 08:30 UTC
Hi, I have a game working perfectly en android, but when I try to port to iOS I have a execution problem, and my iPhone freezes. Is the following error:

`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[GPGSAppController application:didRegisterForRemoteNotificationsWithDeviceToken:]:`

I´m using a free account develop in this moment, I don´t know if this is relevant.

**Comment by claywilkinson** [comment] 2016-10-06 17:22
This looks like a bug.  In Assets/Plugins/iOS/GPGSAppController.mm, delete [line 93](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/Plugins/iOS/GPGSAppController.mm#L93), the call to super didRegisterForRemoteNotifications.

**Comment by claywilkinson** [comment] 2016-10-06 17:35
Closing as a duplicate of #1313

**Closed by claywilkinson** 2016-10-06 17:35 UTC
Labels: iOS
