### ISSUE TITLE
leaderboard showing only the first player untill i refresh

### ISSUE THREAD

**Issue by HaimBendanan** [playgameservices/play-games-plugin-for-unity#798] opened 2015-11-12 23:39 UTC
hi,
as you can see in the screenshots, when i go to my leaderboard in the "all" section, i see only the first player. only when i refresh, the other players appears. i reimported the plugin, still the same.
any idea?

![screenshot_2015-11-13-01-34-58](https://cloud.githubusercontent.com/assets/14773715/11134680/560e471e-89a7-11e5-8fe6-6a9fb0f8eca3.png)
![screenshot_2015-11-13-01-35-05](https://cloud.githubusercontent.com/assets/14773715/11134679/560e4a98-89a7-11e5-8ae7-99b9307fd4ad.png)
![screenshot_2015-11-13-01-35-12](https://cloud.githubusercontent.com/assets/14773715/11134678/560e1ca8-89a7-11e5-9b67-fea22390d15b.png)

**Comment by claywilkinson** [comment] 2015-11-13 17:01
Can you share which versions of Play Services, Play Games App and the client version you are building with?  Thanks!

**Comment by HaimBendanan** [comment] 2015-11-13 21:07
(its after i updated them, note i had this problem even before update)
play service 28
plugin version 0.9.27

what do you mean by play game app and client version?

**Comment by claywilkinson** [comment] 2015-11-13 21:13
These are applications installed on the device that implement the services. To find the versions on the device, go to Settings, then Apps, then find "Google Play Games" and "Google Play services" in the list.  Tap them and the version is displayed under the title.

**Comment by HaimBendanan** [comment] 2015-11-13 21:21
good to know:) ! i have:
google play games : 3.4.12 
google play services : 8.3.01

**Comment by claywilkinson** [comment] 2015-11-13 21:22
Thanks!

**Comment by Hangul-Lim** [comment] 2015-11-19 08:50
I'm experiencing exactly the same issue, and I'm very positive that retrieving leaderboard data [via PlayGamesPlatform.LoadScores(...) and/or Social.LoadUsers(...)] causes it. I tested it on my Vega Iron(android v4.4) and Nexus5(android v6.0) with all the latest google play updates. When I submitted a new score without using those methods, then it worked fine, while using the methods before submitting created the issue.

**Comment by claywilkinson** [comment] 2015-11-25 21:42
We've reproduced the problem - Thanks everyone for the details.  I'll update the thread when I know about a fix.  I think a workaround is to make the call twice to get the data.

**Comment by ayrton2388** [comment] 2015-12-17 14:28
I`m having the same problem.... any ETA until the bug will be solved? We want to publish a game january - february, and Google Play Game Services is an important feature for us.

**Comment by skirners1** [comment] 2015-12-19 15:04
I think that I saw my own high score on a friends device, since testing out some functions during development. But then when I logged in on my own device and set the Google settings to public for this app, I could only see my self in my own device, and I was disappeared in my friends device.

And also, a test user from AppStore is still visible in one of the leaderboards. I guess he didn't change his Google settings.

Sounds like a serverside bug to me...

**Comment by GroundCombo** [comment] 2016-01-26 10:19
We also have from this bug combined with #789. ShowLeaderboardUI is messed up as shown in earlier comments. Google Play Games 3.5.17, Services 8.4.89, plugin 0.9.27.

**Comment by MgFredex** [comment] 2016-02-08 13:56
Is there still no update or workaround for this issue? This seems like a pretty big deal for the service.
I'm experiencing this issue and currently trying to figure out a workaround.

**Comment by claywilkinson** [comment] 2016-03-31 17:20
This should be fixed in  the latest update to the Play Games app.

**Closed by claywilkinson** 2016-03-31 17:20 UTC
Labels: Android, bug
