### ISSUE TITLE
FAILED BINDER TRANSACTION on Login on Android 4.X Device

### ISSUE THREAD

**Issue by FrankNine** [playgameservices/play-games-plugin-for-unity#356] opened 2015-01-10 14:41 UTC
Hello,

I am testing the Play Games Plugin 0.9.11 with 
   Android SDK Tools 24.0.2
   Android SDK Platform-tools 21
   Android SDK Build-tools 21.1.1
   Google Play services Rev. 22
and API 21 API 20 SDK Platform installed

I ran the Android Setup from Unity Editor and
it works fine on a Nexus 7 2012 with Android 5.0.2 and a Nexus 7 2013 with Android 5.0.1.
But it crashes on login on a Nexus 5 with Android 4.4.4

the logcat looks like:
```
V/GamesNativeSDK( 1744): Play Games callback indicates connection.
I/GamesNativeSDK( 1744): Successfully connected to Google Play.
I/Unity   ( 1744):  [Play Games Plugin DLL] 01/10/15 6:19:35 -08:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID
I/Unity   ( 1744):
I/Unity   ( 1744): (Filename: /Applications/buildAgent/work/d63dfc6385190b60/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   ( 1744):
W/art     ( 1744): Thread[21,tid=1874,Native,Thread*=0x4ddab2e8,peer=0x65895f68,"Thread-2355"] attached without supplying a name
E/JavaBinder(18699): !!! FAILED BINDER TRANSACTION !!!
E/DataHolderOperation(18699): When providing result
E/DataHolderOperation(18699): android.os.TransactionTooLargeException
E/DataHolderOperation(18699):   at android.os.BinderProxy.transact(Native Method)
E/DataHolderOperation(18699):   at com.google.android.gms.games.internal.dr.a(SourceFile:1115)
E/DataHolderOperation(18699):   at com.google.android.gms.games.service.a.a.c.a(SourceFile:34)
E/DataHolderOperation(18699):   at com.google.android.gms.games.service.a.a.a(SourceFile:87)
E/DataHolderOperation(18699):   at com.google.android.gms.games.service.GamesIntentService.a(SourceFile:884)
E/DataHolderOperation(18699):   at com.google.android.gms.common.app.c.run(SourceFile:101)
E/DataHolderOperation(18699):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/DataHolderOperation(18699):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/DataHolderOperation(18699):   at java.lang.Thread.run(Thread.java:811)
```

The game is in beta testing and not released yet.
There are 6 achievements and 4 leader boards now. 

I tried installing google_play_services_6171000_r21 manually and ran the setup again.
But the result is the same. It works on 5.0 devices and crashes on 4.X device.
Any help would be greatly appreciated. Thank you.

**Comment by claywilkinson** [comment] 2015-01-26 17:23
tracking internally as 19143074

**Comment by claywilkinson** [comment] 2015-01-27 00:18
@FrankNine Does this happen with the Minimal sample?  If not, could you please share a small sample so I can try to reproduce it?

**Comment by FrankNine** [comment] 2015-01-27 06:37
Hello,

The attached archive is the minimal Unity project I used for testing:
https://drive.google.com/a/rayark.com/file/d/0By-ZTGgTBwUcQzJjUTZJd21aWlE/view?usp=sharing

And I can reproduce the issue with this sample. I did several other tests
after I posted this issue on GitHub, and the Play Service works fine on all
the devices except for the Nexus 5 I mentioned before. I wonder is there a
way to dump the device information which might be helpful?

Thank you.

Frank

2015-01-27 8:18 GMT+08:00 Clayton Wilkinson <notifications@github.com>:

> @FrankNine <https://github.com/FrankNine> Does this happen with the
> Minimal sample? If not, could you please share a small sample so I can try
> to reproduce it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/playgameservices/play-games-plugin-for-unity/issues/356#issuecomment-71566660>
> .
>



-- 
Chun-Fu Chao
Software Engineer @ Rayark, Inc
http://www.ChunFuChao.com

**Comment by hdemmer** [comment] 2015-02-09 10:36
Having the same issue on a Galaxy S3 with Android 4.3.

**Comment by claywilkinson** [comment] 2015-02-09 18:07
Thanks for the sample - i'll take a look.....

**Comment by Jokercheng** [comment] 2015-03-06 07:37
Any news?
I crash on LG G3 with same issue.

**Comment by claywilkinson** [comment] 2015-06-02 23:57
@Jokercheng or @hdemmer - If this is still happening, can you post a log as well? So far, we have not been able to make progress on this issue.

**Comment by claywilkinson** [comment] 2015-08-04 03:03
Closing this issue since it has been a long time with any activity, and there is no reproducible issue..  Please open another issue if you are still having the same error.  Thanks!

**Closed by claywilkinson** 2015-08-04 03:03 UTC
