### ISSUE TITLE
EnableHidePops is not working on android 8.0+

### ISSUE THREAD

**Issue by Dirly** [playgameservices/play-games-plugin-for-unity#2078] opened 2018-01-14 05:07 UTC
If anyone is trying to hide popups for VR there is an issue with the way passing a custom config file to the PlayGamesClientConfiguration.Builder ().  I'm not entirely sure why but if I try this is what i was doing:

    //CALLED ON AWAKE
    private MultiplayerManager () {
         PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder ()
            .EnableSavedGames ()
            .EnableHidePopups ()
            .Build ();
        PlayGamesPlatform.InitializeInstance (config);

        //Debug.Log(PlayGamesClientConfiguration.Is)
        built = true;
    }

    public void Activate () {
        PlayGamesPlatform.Activate ();
    }

    //CALLED ON START
    public void TrySilentSignIn () {
        if (!PlayGamesPlatform.Instance.localUser.authenticated) {
            PlayGamesPlatform.Instance.Authenticate ((bool success) => {
                if (success) {
                    SignedIn = true;
                    Debug.Log ("Silently signed in! Welcome " + PlayGamesPlatform.Instance.localUser.userName);
                    PlayerName = PlayGamesPlatform.Instance.localUser.userName;
                } else {
                    SignedIn = false;
                    Debug.Log ("Oh... we're not signed in.");
                    PlayerName = "No Name";
                }
            }, true);
        } else {
            SignedIn = true;
            PlayerName = PlayGamesPlatform.Instance.localUser.userName;
            Debug.Log ("We're already signed in");
        }
    }

If i comment out the enablehide popups it works.  This was working on android 7.1

**Comment by ilterbilguven** [comment] 2018-04-26 09:35
After 3 months, is there no fix?

**Comment by 13Flo** [comment] 2018-11-20 18:31
Any update on this?

**Comment by olehkuznetsov** [comment] 2018-11-23 13:53
Can you try it with v0.9.54, please? There were some sign-in code changes.

**Comment by olehkuznetsov** [comment] 2018-11-23 13:58
I've reproduced it on v0.9.54

**Comment by 13Flo** [comment] 2018-11-23 17:48
It would be great if you guys could fix that issue. I'm trying to submit my game but it has been refused several times by the Daydream team because of the Play Games SDK displaying 2D notifications on top of the VR view.

**Comment by 13Flo** [comment] 2018-11-27 02:13
Would it be possible to have an ETA on this?

**Comment by olehkuznetsov** [comment] 2018-11-29 14:12
Should be fixed in 0.9.55

**Closed by olehkuznetsov** 2018-11-29 14:12 UTC
Labels: bug

**Comment by 13Flo** [comment] 2018-11-29 23:11
Confirmed, it's fixed. Thank so very much!
