### ISSUE TITLE
[BUG] Version Handler - Verbose Logging can't be turned off - console spam

### ISSUE THREAD

**Issue by st4rdog** [playgameservices/play-games-plugin-for-unity#2977] opened 2020-11-26 22:34 UTC
### [REQUIRED] Please fill in the following fields:
  * Unity editor version: 2019.3.6f1
  * External Dependency Manager version: 1.2.162
  * Source you installed EDM4U: v0.10.12 unitypackage release
  * Features in External Dependency Manager in use: Android Resolver, iOS Resolver, VersionHandler, Package Manager Resolver
  * Platform you are using the Unity editor on: Windows

### [REQUIRED] Please describe the issue here:
Cannot turn off Verbose Logging for Version Handler. Same as this [issue](https://github.com/googlesamples/unity-jar-resolver/issues/391).

When playing in editor, it will spam the console every time. After turning off Verbose Logging in the settings window, on reopening the window, it will be on again.

Changing the setting in GPGSAndroidSetupUI.cs and NearbyConnectionUI.cs to false doesn't solve it.

**Comment by ozdemir08** [comment] 2020-11-27 11:44
This issue is mainly about External Dependency Manager and should be addressed there. I am closing this issue now. If the issue is not resolved there, feel free to reopen it.

**Closed by ozdemir08** 2020-11-27 11:44 UTC
Labels: Enhancement
