### ISSUE TITLE
Why not fix the crash problem?

### ISSUE THREAD

**Issue by HoiMinJeong** [playgameservices/play-games-plugin-for-unity#1657] opened 2017-03-21 01:58 UTC
I've contacted Google about the crash, but I have not received a response at all.

Is not this an official plugin developed by Google?

**Comment by buckbim** [comment] 2017-03-23 03:36
Google Team work really poor! Not like Unity Team.They support developer is very good.

**Comment by haim96** [comment] 2017-03-23 06:44
is this official plugin of google play for unity?

**Comment by JasperDre** [comment] 2017-03-25 11:09
The publisher/maintainer of this repository seems to be working for, or atleast with, Google. However, there hasn't been much activity from him in this repository, so I don't know what is going on. I'm pretty there is a comment of the publisher saying there would be a big update in February or March, but I don't know what is going on behind the scenes.

**Comment by buckbim** [comment] 2017-03-27 08:54
Right Now I really need to fix crash login on google play services 10.2.xxx But Google dev Team don't have anything response about this topic.!

**Comment by claywilkinson** [comment] 2017-04-05 00:19
There is an update coming out this week to fix this issue.  Closing this issue as a dupe of #1604.

**Closed by claywilkinson** 2017-04-05 00:19 UTC
