### ISSUE TITLE
Android crash 

### ISSUE THREAD

**Issue by raducostea** [playgameservices/play-games-plugin-for-unity#1693] opened 2017-04-14 08:30 UTC
I am getting a lot of these in the crash report section

> java.lang.Error: FATAL EXCEPTION [UnityMain]
Unity version     : 5.4.0f3
Device model      : HUAWEI HUAWEI Y541-U02
Device fingerprint: HUAWEI/Y541-U02/HWY541-U:4.4.2/HUAWEIY541-U02/C479B109:user/ota-rel-keys,release-keys

Caused by: java.lang.Error: signal 6 (SIGABRT), code -6 (?), fault addr --------
Build fingerprint: 'HUAWEI/Y541-U02/HWY541-U:4.4.2/HUAWEIY541-U02/C479B109:user/ota-rel-keys,release-keys'
Revision: '0'
pid: 10413, tid: 10660, name: callback_queue  >>> com.tedrasoft.plumber <<<
    r0 00000000  r1 000029a4  r2 00000006  r3 00000000
    r4 00000006  r5 00000000  r6 000029a4  r7 0000010c
    r8 0000004c  r9 41cea350  sl 00000001  fp 5fa85699
    ip 6e74f868  sp 6e74f550  lr 4012a09d  pc 40138fd8  cpsr 34355949

	at libc.tgkill(tgkill:12)
	at libc.pthread_kill(pthread_kill:48)
	at libc.raise(raise:10)
	at libc.00011fe1(Native Method)
	at libc.abort(abort:4)
	at libdvm.dvmAbort(dvmAbort:78)
	at libdvm.IndirectRefTable::get(void*) const(IndirectRefTable:252)
	at libdvm.dvmDecodeIndirectRef(Thread*, _jobject*)(dvmDecodeIndirectRef:30)
	at libdvm.dvmCallMethodA(Thread*, Method const*, Object*, bool, JValue*, jvalue const*)(dvmCallMethodA:122)
	at libdvm.0004f90f(Native Method)
	at libunity.00853518(Native Method)
	at Unknown.00003874(Unknown Source)
	at AndroidJNI.INTERNAL_CALL_CallStaticObjectMethod(Native Method)
	at AndroidJNI.CallStaticObjectMethod(<0x00038>:56)
	at AndroidJNISafe.CallStaticObjectMethod(<0x0002b>:43)
	at AndroidReflection.GetMethodMember(<0x0011b>:283)
	at _AndroidJNIHelper.GetMethodID(<0x0005b>:91)
	at AndroidJNIHelper.GetMethodID(<0x00033>:51)
	at _AndroidJNIHelper.GetMethodID(<0x0004b>:75)
	at AndroidJNIHelper.GetMethodID(<0x00043>:67)
	at AndroidJavaObject._CallStatic(<0x0007b>:123)
	at AndroidJavaObject.CallStatic(<0x0003b>:59)
	at AndroidJavaObject.FindClass(<0x00077>:119)
	at AndroidJavaClass._AndroidJavaClass(<0x00043>:67)
	at AndroidJavaClass..ctor(<0x0002b>:43)
	at AndroidTokenClient.Signout(<0x0003b>:59)
	at AndroidClient.CreateTokenClient(<0x0005b>:91)
	at NativeClient.ToUnauthenticated(<0x00063>:99)
	at NativeClient.SignOut(<0x0001b>:27)
	at NativeClient.PopulateAchievements(<0x00113>:275)
	at <HandleAuthTransition>c__AnonStorey42.<>m__B2(<0x0002b>:43)
	at <ToIntPtr>c__AnonStorey99`1.<>m__134(<0x00073>:115)

>

**Comment by claywilkinson** [comment] 2017-04-26 19:09
This is known issue: #1675. Closing as a dupe of that issue.  I'll update the plugin shortly.

**Closed by claywilkinson** 2017-04-26 19:09 UTC
