### ISSUE TITLE
Incompatible with play-services 10.2.0

### ISSUE THREAD

**Issue by 3583Bytes** [playgameservices/play-games-plugin-for-unity#1629] opened 2017-03-03 21:12 UTC
This plugin is now incompatible with play-services 10.2.0 the resolver incorrectly downloads this version instead of keeping 10.0.1 which it needs.  The result is that the plugin crashes Unity Game.  Please fix

**Comment by josephbk117** [comment] 2017-03-04 13:00
I am having the same problem

**Comment by donislawdev** [comment] 2017-03-05 20:58
Same here, any information when this issue  gonna be fixed ?
Also i found a workaround for this issue (not tested yet):
https://github.com/playgameservices/play-games-plugin-for-unity/issues/1604
Look for a tolgau post.

**Comment by fabrantes** [comment] 2017-03-05 21:52
Same here. Unfortunately this makes the plugin incompatible with the Firebase plugin which requires 10.2.0. I wonder if there are plans to fix this soon.

**Comment by claywilkinson** [comment] 2017-03-05 22:04
There is a fix in process.  In the mean time you should be able to turn off automatic resolution and use 10.1.0 for both games and firebase.

**Comment by eklebanski** [comment] 2017-03-10 12:03
When will the fix be ready? Anyone can provide proximate date????

**Comment by mrbava** [comment] 2017-03-13 17:21
Does not play well with firebase and 10.0.2. Hoping for a quick fix.

**Comment by claywilkinson** [comment] 2017-03-13 18:08
@mrbava  - Do you mean 10.2.0? Everything should work with 10.0.x.  I don't have a date yet for the update, as soon as I do, I will make sure everyone knows.  The issue is in the C++ SDK which this plugin wraps, so it is a more involved change.  Stay Tuned!

**Comment by mrbava** [comment] 2017-03-13 19:13
@claywilkinson appreciate it! 

I don't have my build errors with me, but I have two repos going where I am able to use each service individually ( firebase in one, google play services in the other ) but as soon as I combine the two, I either get build errors, missing dll exceptions or game crashes on login. Replacing the 10.0.2s with 10.0.xx works for google play services, but I believe it throws an error when trying to log an event with firebase. I can report back when I get back on my main machine with logs.

**Comment by ivanquirino** [comment] 2017-03-14 18:39
same for me, I reverted to 10.0.1 and it worked fine again.

**Comment by andreasp79** [comment] 2017-03-15 15:48
@claywilkinson Can you confirm latest Unity Firebase SDK (3.0.0) works by downgrading everything to 10.0.x? If so, would you mind giving some instructions on how to downgrade firebase to use 10.0.x? I can't get that to work, either by replacing the .aars directly, or by editing the required versions in code and re-running the dependency resolver.

I assume it would be easier to roll back to old functionality if we had access to older Unity Firebase SDKs, but it seems the team actively discourages that and there are no download links to them anywhere. It's very frustrating this was working 2 weeks ago and now all of a sudden we have critical functionality broken without any workaround.

**Comment by Suhrahj** [comment] 2017-03-16 02:20
I've been losing my mind over this, I'm glad I found this. I tried reverting google play services but it still didn't work. Hoping for a fix soon.

**Comment by onedge** [comment] 2017-03-16 10:52
Same for me, I know that rolling back to 10.0.1 could fix this issue.
But I need to use firebase for unity 3.0.x - using play services 10.2.0, Because firebase for unity 1.1.2 - using play services 10.0.1 - has a trouble with on some IOS devices.
So I'm waiting for a fix.

**Comment by luizjunior** [comment] 2017-03-16 17:14
same for me... using 10.0.1

**Comment by felipemmax** [comment] 2017-03-17 07:06
I am in the same situation as onedge

**Comment by PluginIO** [comment] 2017-03-17 17:35
Same problem.

**Comment by GilbertZhang** [comment] 2017-03-18 11:46
same for me, anyone knows the procedure to revert back to 10.0.1? Thanks in advance

**Comment by ShakedJuran** [comment] 2017-03-21 11:56
Ive been able to confirm that if you downgrade to 10.0.1 you can use Firebase unity plugin 3.0.0 (have not confirmed with 3.0.1), this plugin and also the Google mobile ads plugin.

**Comment by Suhrahj** [comment] 2017-03-21 11:58
@ShakedJuran how do you do that exactly?

**Comment by ShakedJuran** [comment] 2017-03-21 12:15
I think this should do the trick.
1. Import all the plugins as you would normally do.
2. Go to Assets/Play Services Resolver/Version Handler/Settings and turn OFF "Enable Version Managment"
3. Apply my patch (just make sure you overwrite all the files)
4. in Assets/Play Services Resolver/Version Handler press "Update".
5. in Assets/Play Services Resolver/Android Resolver/Settings and turn OFF "Enable Background Resolution"
6. in Assets/Play Services Resolver/Android Resolver click the "Resolve Client Jars"
5. Go to Window/Google Play Games/Setup/Android Setup and click the "Setup" button.
6. you should now be able to build and run to android. (I hope) :)





[GooglePlay-Firebase-GoogleMobileAds-UnityPatch.zip](https://github.com/playgameservices/play-games-plugin-for-unity/files/858027/GooglePlay-Firebase-GoogleMobileAds-UnityPatch.zip)

**Comment by Suhrahj** [comment] 2017-03-21 14:43
@ShakedJuran honestly I don't know how you change those settings and I don't have anything called Android Resolver, just a JarResolver. On top of it all I have no idea where to overwrite those assets because apparently they don't exist in my project. Are we using the same thing?

**Comment by ShakedJuran** [comment] 2017-03-21 14:51
@Suhrahj , note that the solution i proposed was for using the play-games-plugin-for-unity, and https://firebase.google.com/docs/unity/setup, and https://github.com/googleads/googleads-mobile-unity (version 3.2.0)

So if you just want to use 10.0.1 for the play-games-plugin-for-unity take a look at: #1604 

Also im using Unity 5.5.2f1 if it makes any difference

**Comment by Suhrahj** [comment] 2017-03-21 15:21
@ShakedJuran Thanks a million man! I only have love for you, I don't have googleads, so I followed the steps in #1604 to lower the version and then I had to delete firebase (at least for now), now play services work without a problem, thank you.

**Comment by lolingloled** [comment] 2017-03-22 15:49
@ShakedJuran Could you please tell me the exact path to unzip each file in the .zip you uploaded? I'm trying to but I got quite lost with the files zipped. Thank you in advance

**Comment by arcrus** [comment] 2017-03-22 16:48
@lolingloled Try uncompress on Windows.

**Comment by lolingloled** [comment] 2017-03-22 17:03
@arcrus I can unzip without any problem, mi issue is I don't know where to exactly locate each of the unzipped files.

**Comment by arcrus** [comment] 2017-03-22 17:13
@lolingloled GooglePlay-Firebase-GoogleMobileAds-10.0.1-UnityPatch.unitypackage is the file you've got uncompressed, right? than, by importing unitypackage, should replace necessary files. 
Which part exactly you have problem with? 

<img width="641" alt="screen shot 2017-03-22 at 17 12 24" src="https://cloud.githubusercontent.com/assets/2043563/24211038/ce1ca438-0f22-11e7-84cc-3c9f2d61bc0c.png">

**Comment by lolingloled** [comment] 2017-03-22 17:30
@arcrus Nope I'm sorry, the files I downloaded are on this zip:
https://github.com/playgameservices/play-games-plugin-for-unity/files/858055/AssetsModified.zip

**Comment by lolingloled** [comment] 2017-03-22 17:40
@arcrus I think that patch is excatly what I need though, could you give me an URL to download it?
Thank you.
And sorry I'm quite noob with this stuff

**Comment by arcrus** [comment] 2017-03-22 17:43
@lolingloled Actually, if you uncompress AssetModified.zip, you should get unitypackage file as a result. but somehow, it's not uncompressed properly in OSX. anyway, I attached unitypackage file here in new compressed zip file.
[GooglePlay-Firebase-GoogleMobileAds-10.0.1-UnityPatch.unitypackage.zip](https://github.com/playgameservices/play-games-plugin-for-unity/files/862336/GooglePlay-Firebase-GoogleMobileAds-10.0.1-UnityPatch.unitypackage.zip)

**Comment by lolingloled** [comment] 2017-03-22 17:45
@arcrus thank you very much! I hope it works for me :D

**Comment by ShakedJuran** [comment] 2017-03-22 17:45
Yeah sorry i removed that pack because i thought a zip file would be easier

**Comment by arcrus** [comment] 2017-03-22 17:48
btw, big thanks to @ShakedJuran your solution works perfectly and saved me from hell.

**Comment by lolingloled** [comment] 2017-03-23 11:27
@ShakedJuran Thank you, I could make it work, now I have joined google play services and firebase accounts and can finally keep working on my game, you really saved my ass.
And thank you @arcrus for re-uploading the unitypackage I could use it with no problems, I feel so happy now 😀

**Comment by AdnanNazir** [comment] 2017-03-27 10:25
same issue with me. After removing 10.2.0 and adding 10.1.0 
My game no longer crashes but I am unable to successfully login with Google Play Games.

**Comment by claywilkinson** [comment] 2017-04-06 17:26
This has been fixed in version 0.9.37 - The plugin works with play-services 10.2+

**Closed by claywilkinson** 2017-04-06 17:26 UTC
