### ISSUE TITLE
Issue with Unity 5.2.1f1

### ISSUE THREAD

**Issue by StormSabotage** [playgameservices/play-games-plugin-for-unity#724] opened 2015-09-25 14:02 UTC
Hello there, i have successfully integrated play-services using this sdk in my projects on Unity 5.0+ and all was perfect and correct until yesterday. One of my projects was updated to latest Unity Engine version (5.2.1f1) and issue comes.
All settings are right and correct, builded project works fine, calling "PlayGamesPlatform.Activate()" also returns success, but when i try to sign in with google account (calling "Social.localUser.Authenticate ()") it shows me pop-up "choose your account or log-in with new" and after i do, pop-up disappears and nothing happens. Few seconds later Social.localUser.Authenticate () returns me "false" as success argument. I also tried to create clean project and integrate play-service sdk in it, absolutely same result. 

(please don't tell me about test accounts or something else from integration guide that i should configure - it's configured well already, i'll repeat - this project with play-services was on-the-go and all worked fine until engine update, reimporting\reconfiguring gives no result)

Need your assistance, thanks!

**Comment by claywilkinson** [comment] 2015-09-25 15:46
Can you share the log file of when you are authenticating?  Since the game was working before, it does sound like it is not a console configuration issue - but a couple quick things to check are:

Re-run the plugin setup (maybe during the upgrading of the project to the next version of Unity something was lost?).

The keystore you are using to sign the app, make sure something was not misdirected there to a different keystore.

**Comment by StormSabotage** [comment] 2015-09-25 18:11
Thanks for answering.

"Re-run the plugin setup (maybe during the upgrading of the project to the next version of Unity something was lost?)."
- Tried already. How i said, i even tried to create fresh clean unity project, integrate and configure sdk in it and build it to device with same app-ids / keys / bundle identifiers as in original project - was same result.

"The keystore you are using to sign the app, make sure something was not misdirected there to a different keystore."
- Keystore was configured once at project start and has no changes (btw. project also has in-app purchases and they still works fine)

My Unity engine version is latest (5.2.1f1), also android SDK libraries updated to latest revisions.

Here is logcat from device unity activity when i click on "Authorise" button:

I/Unity   (24354):  [Play Games Plugin DLL] 09/25/15 21:09:01 +03:00 DEBUG: Creating platform-specific Play Games client.
I/Unity   (24354):  
I/Unity   (24354): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (24354): 
I/Unity   (24354):  [Play Games Plugin DLL] 09/25/15 21:09:01 +03:00 DEBUG: Creating Android IPlayGamesClient Client
I/Unity   (24354):  
I/Unity   (24354): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (24354): 
I/Unity   (24354): Building GPG services, implicitly attempts silent auth
I/Unity   (24354):  
I/Unity   (24354): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (24354): 
I/Unity   (24354):  [Play Games Plugin DLL] 09/25/15 21:09:01 +03:00 DEBUG: Entering state: BeforeRoomCreateStartedState
I/Unity   (24354):  
I/Unity   (24354): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (24354): 
I/Unity   (24354):  [Play Games Plugin DLL] 09/25/15 21:09:01 +03:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.
I/Unity   (24354):  
I/Unity   (24354): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (24354): 
I/Unity   (24354):  [Play Games Plugin DLL] 09/25/15 21:09:01 +03:00 DEBUG: Entering state: ShutdownState
I/Unity   (24354):  
I/Unity   (24354): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (24354): 
I/Unity   (24354):  [Play Games Plugin DLL] 09/25/15 21:09:01 +03:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.
I/Unity   (24354):  
I/Unity   (24354): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (24354): 
I/Unity   (24354):  [Play Games Plugin DLL] 09/25/15 21:09:02 +03:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
I/Unity   (24354):  
I/Unity   (24354): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (24354): 
I/Unity   (24354): Invoking callbacks, AuthState changed from silentPending to Unauthenticated.
I/Unity   (24354):  
I/Unity   (24354): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (24354): 
I/Unity   (24354): there are pending auth callbacks - starting AuthUI
I/Unity   (24354):  
I/Unity   (24354): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (24354): 
I/Unity   (24354):  [Play Games Plugin DLL] 09/25/15 21:09:02 +03:00 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.
I/Unity   (24354):  
I/Unity   (24354): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (24354): 
I/Unity   (24354):  [Play Games Plugin DLL] 09/25/15 21:09:16 +03:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
I/Unity   (24354):  
I/Unity   (24354): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (24354): 
I/Unity   (24354): AuthState == Unauthenticated calling auth callbacks with failure
I/Unity   (24354):  
I/Unity   (24354): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (24354): 
I/Unity   (24354):  [Play Games Plugin DLL] 09/25/15 21:09:16 +03:00 DEBUG: Invoking user callback on game thread
I/Unity   (24354):  
I/Unity   (24354): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (24354): 
I/Unity   (24354): GPController: User was not logged in.
I/Unity   (24354):  
I/Unity   (24354): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (24354):

**Comment by StormSabotage** [comment] 2015-09-25 18:18
How you can see - first "ERROR_NOT_AUTHORIZED" returned when i clicked on button, after that SDK opens authorisation pop-up, and when i selected my account, it returns "ERROR_NOT_AUTHORIZED" again. Tell me if i can give you more logs somehow, thanks.

**Comment by claywilkinson** [comment] 2015-09-25 18:24
The first ERROR_NOT_AUTHORIZED is a silent login attempt that happens when calling authenticate for the first time (this is when the C++ SDK is initialized, and the silent auth is part of the SDK initialization).  

The second one is from the explicit authentication - and unfortunately there is not much more to go on.  It does point to the configuration difference between the app and the Play Game Console:
1. app id 
2. package id
3. SHA1 fingerprint of the keystore
4. player is in the tester list.

**Comment by StormSabotage** [comment] 2015-09-25 18:56
I checked twice all that. Could you take a look at my screenshots please? Maybe i just forgot about something... spend second day trying to figure it out...

![screen](https://cloud.githubusercontent.com/assets/14837775/10109546/30860bf0-63d0-11e5-93dd-0c6bce8b0232.jpg)

**Comment by StormSabotage** [comment] 2015-09-25 19:16
And i just uploaded new update to project, to be sure my fingerprint of the keystore is right, uploaded successfully.

**Comment by claywilkinson** [comment] 2015-09-25 19:28
Ahh - it is a little confusing (Open to suggestions on how to make it more clear) - the Web App Client Id looks like it should be blank in your case.

If your game has a server back end, you would need to link a web application to the game and paste the client id of the web app in this box.

**Comment by StormSabotage** [comment] 2015-09-25 20:53
Unfortunately that doesn't solve problem.

**Comment by claywilkinson** [comment] 2015-09-25 21:34
can you check the file ProjectSettings/GooglePlayGameSettings.txt  to see if the client id is in-fact empty?  It could be a bug in the settings dialog when the value is empty?

**Comment by StormSabotage** [comment] 2015-09-25 22:01
Checked, it has provided values:

lastUpgrade=00925
proj.AppId=841736539500
proj.ConstantsClassName=UnicycleAndroid
and.ResourceData=%3c%3fxml+version%3d%221.0%22+encoding%3d%22utf-8%22%3f%3e%0a%3c%21--%0aGoogle+Play+game+services+IDs.%0aSave+this+file+as+res%2fvalues%2fgames-ids.xml+in+your+project.%0a--%3e%0a%3cresources%3e%0a++%3cstring+name%3d%22app_id%22%3e841736539500%3c%2fstring%3e%0a++%3cstring+name%3d%22achievement_achievement_1%22%3eCgkI7Jqh278YEAIQAg%3c%2fstring%3e%0a++%3cstring+name%3d%22achievement_achievement_2%22%3eCgkI7Jqh278YEAIQAw%3c%2fstring%3e%0a++%3cstring+name%3d%22achievement_achievement_3%22%3eCgkI7Jqh278YEAIQBA%3c%2fstring%3e%0a++%3cstring+name%3d%22achievement_achievement_4%22%3eCgkI7Jqh278YEAIQBQ%3c%2fstring%3e%0a++%3cstring+name%3d%22achievement_achievement_5%22%3eCgkI7Jqh278YEAIQBg%3c%2fstring%3e%0a++%3cstring+name%3d%22leaderboard_distance%22%3eCgkI7Jqh278YEAIQBw%3c%2fstring%3e%0a%3c%2fresources%3e
and.ClientId=
android.SetupDone=true

**Comment by banditdevelopment** [comment] 2015-09-27 19:58
Just so you know, I am working with the latest GPGS and Unity 5.2.1f1. No problems here using Social.user.authenticate.

My guess is that there is something else wrong with your project.

**Comment by 133900029** [comment] 2015-10-04 17:45
I have the same problem  ..
please tell me how to solve it ?

**Comment by 133900029** [comment] 2015-10-04 17:45
10-05 01:45:25.093 32751-32766/? D/Unity:  GL_AMD_compressed_ATC_texture GL_AMD_performance_monitor GL_AMD_program_binary_Z400 GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_robustness GL_EXT_texture_format_BGRA8888 GL_EXT_texture_type_2_10_10_10_REV GL_NV_fence GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth_texture GL_OES_depth24 GL_OES_EGL_image GL_OES_EGL_sync GL_OES_EGL_image_external GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_fragment_precision_high GL_OES_get_program_binary GL_OES_packed_depth_stencil GL_OES_depth_texture_cube_map GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_vertex_type_10_10_10_2 GL_OES_vertex_array_object GL_QCOM_alpha_test GL_QCOM_binning_control GL_QCOM_driver_control GL_QCOM_perfmon_global_mode GL_QCOM_extended_get GL_QCOM_extended_get2 GL_QCOM_tiled_rendering GL_QCOM_writeonly_rendering GL_KHR_texture_compression_astc_ldr GL_EXT_s
10-05 01:45:25.093 32751-32766/? D/Unity: RGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_EXT_texture_filter_anisotropic GL_EXT_multisampled_render_to_texture GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_EXT_disjoint_timer_query
10-05 01:45:26.203 32751-32766/? I/Unity:  [Play Games Plugin DLL] 10/05/15 1:45:26 +08:00 DEBUG: Activating PlayGamesPlatform.
10-05 01:45:26.203 32751-32766/? I/Unity:  
10-05 01:45:26.203 32751-32766/? I/Unity: (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
10-05 01:45:26.213 32751-32766/? I/Unity:  [Play Games Plugin DLL] 10/05/15 1:45:26 +08:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
10-05 01:45:26.213 32751-32766/? I/Unity:  
10-05 01:45:26.213 32751-32766/? I/Unity: (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
10-05 01:45:26.213 32751-32766/? I/Unity:  [Play Games Plugin DLL] 10/05/15 1:45:26 +08:00 DEBUG: Creating platform-specific Play Games client.
10-05 01:45:26.213 32751-32766/? I/Unity:  
10-05 01:45:26.213 32751-32766/? I/Unity: (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
10-05 01:45:26.213 32751-32766/? I/Unity:  [Play Games Plugin DLL] 10/05/15 1:45:26 +08:00 DEBUG: Creating Android IPlayGamesClient Client
10-05 01:45:26.213 32751-32766/? I/Unity:  
10-05 01:45:26.213 32751-32766/? I/Unity: (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
10-05 01:45:26.243 32751-32766/? D/GamesUnitySDK: Performing Android initialization of the GPG SDK
10-05 01:45:26.373 32751-32766/? I/Unity: Building GPG services, implicitly attempts silent auth
10-05 01:45:26.373 32751-32766/? I/Unity:  
10-05 01:45:26.373 32751-32766/? I/Unity: (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
10-05 01:45:26.423 32751-32766/? I/Unity:  [Play Games Plugin DLL] 10/05/15 1:45:26 +08:00 DEBUG: Entering state: BeforeRoomCreateStartedState
10-05 01:45:26.423 32751-32766/? I/Unity:  
10-05 01:45:26.423 32751-32766/? I/Unity: (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
10-05 01:45:26.423 32751-32766/? I/Unity:  [Play Games Plugin DLL] 10/05/15 1:45:26 +08:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.
10-05 01:45:26.423 32751-32766/? I/Unity:  
10-05 01:45:26.423 32751-32766/? I/Unity: (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
10-05 01:45:26.423 32751-32766/? I/Unity:  [Play Games Plugin DLL] 10/05/15 1:45:26 +08:00 DEBUG: Entering state: ShutdownState
10-05 01:45:26.423 32751-32766/? I/Unity:  
10-05 01:45:26.423 32751-32766/? I/Unity: (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
10-05 01:45:26.423 32751-32766/? I/Unity:  [Play Games Plugin DLL] 10/05/15 1:45:26 +08:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.
10-05 01:45:26.423 32751-32766/? I/Unity:  
10-05 01:45:26.423 32751-32766/? I/Unity: (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
10-05 01:45:36.233 32751-387/? I/Unity:  [Play Games Plugin DLL] 10/05/15 1:45:36 +08:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
10-05 01:45:36.233 32751-387/? I/Unity:  
10-05 01:45:36.233 32751-387/? I/Unity: (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
10-05 01:45:36.233 32751-387/? I/Unity: Invoking callbacks, AuthState changed from silentPending to Unauthenticated.
10-05 01:45:36.233 32751-387/? I/Unity:  
10-05 01:45:36.233 32751-387/? I/Unity: (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
10-05 01:45:36.243 32751-387/? I/Unity: there are pending auth callbacks - starting AuthUI
10-05 01:45:36.243 32751-387/? I/Unity:  
10-05 01:45:36.243 32751-387/? I/Unity: (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
10-05 01:45:36.953 32751-387/? I/Unity:  [Play Games Plugin DLL] 10/05/15 1:45:36 +08:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
10-05 01:45:36.953 32751-387/? I/Unity:  
10-05 01:45:36.953 32751-387/? I/Unity: (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
10-05 01:45:36.953 32751-387/? I/Unity: AuthState == Unauthenticated calling auth callbacks with failure
10-05 01:45:36.953 32751-387/? I/Unity:  
10-05 01:45:36.953 32751-387/? I/Unity: (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
10-05 01:45:36.963 32751-32766/? I/Unity:  [Play Games Plugin DLL] 10/05/15 1:45:36 +08:00 DEBUG: Invoking user callback on game thread

**Comment by tsx5000** [comment] 2015-10-09 17:34
I am having the exact same problem. I tried every solution available online but still no success. I even made a blank project with only GPGS but it still didn't work.
The strange part is, this is happening only for some google play ids. for example, it works fine with my id but fails with my friend's id (Both ids are registered in the testers list). I just went live with my app and checked who all got this issue. For most of them it worked fine. But there were one or two cases where their login failed and the app was not responding for 2-3 seconds. 
Later, my friend tried to login with a different email id on his device and it worked fine, but when he used his own id, it failed again.
Please try to fix this, as the problem is very erratic and has no apparent solution.

**Comment by claywilkinson** [comment] 2015-10-27 19:01
This thread seems to have 3 different issues - Any objections to closing this thread  - and please open a new issue with each individual's specific situation?  Thanks!

**Comment by alaattinbedir** [comment] 2015-11-15 20:46
I have similar problem. Social.localUser.Authenticate() not login in Android device but login in iOS. When i use PlayGamesPlatform.Instance.localUser.Authenticate() it works for both platform. I implemented this code for invitation 
PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
			// enables saving game progress.
			.EnableSavedGames()
				// registers a callback to handle game invitations received while the game is not running.
				.WithInvitationDelegate(OnInvitationReceived)
				.Build();
		
		PlayGamesPlatform.InitializeInstance(config);
		// recommended for debugging:
		PlayGamesPlatform.DebugLogEnabled = true;

PlayGamesPlatform.Activate();


But then Social.localUser.Authenticate() not working for Android devices..

**Closed** 2016-01-27 20:06 UTC

**Comment by 2rusbekov** [comment] 2016-07-11 09:34
I had same issue. Problem was that auth code was in static method
`    public static void GPLogin()
    {
        PlayGamesPlatform.DebugLogEnabled = true;
        PlayGamesPlatform.Activate();
        Social.Active.Authenticate(Social.localUser, GPAuthCallback);
    }`

But when I moved it to instance method all became fine.

**Comment by StormSabotage** [comment] 2016-07-14 06:47
@2rusbekov That was actual for me 10 months ago, I used static method too. Anyway, good to know that info.

**Comment by kkondarev** [comment] 2016-09-24 17:06
This should be documented!

**Comment by jungyunwoo** [comment] 2017-02-23 07:53
10.0.1arr .. Thanks !!

**Comment by abramovks** [comment] 2018-10-19 04:57
This helped me.

https://github.com/playgameservices/play-games-plugin-for-unity/issues/2217#issuecomment-417619382

Can confirm this works:
open template-AndroidManifest.txt
"\ APP_ID" to "\u003__APP_ID__"
setup GPGS from Unity (press Window/Google Play Services/Setup)



True, after the correction, I received the error "Authentification failed". But it was a problem with SHA-1. It was decided when I did
keytool -exportcert -keystore user.keystore -list -v
And put the correct SHA-1 in https://console.developers.google.com/apis/credentials in the application settings.
