### ISSUE TITLE
`GooglePlayGames.Android.AndroidClient' does not implement interface member

### ISSUE THREAD

**Issue by kamen1221** [playgameservices/play-games-plugin-for-unity#1288] opened 2016-07-21 11:09 UTC
Hey, I ran into a small error when using unity new beta version 5.4.0f , could you guys give me some advice how to fix this ?
thx in advance.

Assets/GooglePlayGames/Platforms/Android/AndroidClient.cs(31,20): error CS0738: `GooglePlayGames.Android.AndroidClient' does not implement interface member `GooglePlayGames.IClientImpl.GetPlayerStats(System.IntPtr, System.Action<GooglePlayGames.BasicApi.CommonStatusCodes,PlayerStats>)' and the best implementing candidate `GooglePlayGames.Android.AndroidClient.CreatePlatformConfiguration()' return type `GooglePlayGames.Native.PInvoke.PlatformConfiguration' does not match interface member return type `void'

**Comment by claywilkinson** [comment] 2016-07-21 16:05
It sounds like you might have some old code somewhere?  That method is definitely implemented: https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/Platforms/Android/AndroidClient.cs#L118

It had been removed in a previous version.

**Comment by kamen1221** [comment] 2016-07-21 16:36
Hmmm i tried deleting all the files and remove any connection from my scripts to google play so the game was playable again, than i installed a fresh copy and the same error is still there.
Than i tried installing this package on my other projects, there it works just fine no errors insight.
Could my project be corrupted somehow and does anyone have any ideas how to fix it ?

**Comment by MihailOstapenko** [comment] 2016-07-24 11:36
Same issue here. In my case the root cause of the problem was naming conflict - I have my own class named `PlayerStats`, which is conflicts with `GooglePlayGames.BasicApi.PlayerStats`.

I've fixed that by specifying full class name `GooglePlayGames.BasicApi.PlayerStats` in method `GetPlayerStats` in `IClientImpl` interface.

**Comment by claywilkinson** [comment] 2016-08-12 21:57
Thanks for the comment @MihailOstapenko.  

@kamen1221  - ok to close this issue?  Did you get it resolved?

**Comment by kamen1221** [comment] 2016-08-13 08:16
@claywilkinson sorry for late response, yeah i managed to fix it by copying all my own scripts and assets to an older backup of my game, when this error didn't exist.

**Closed** 2016-08-15 14:39 UTC
