### ISSUE TITLE
CommitUpdate is not working on Android

### ISSUE THREAD

**Issue by qbit86** [playgameservices/play-games-plugin-for-unity#460] opened 2015-04-13 09:49 UTC
Cannot update data in snapshot.

I've got some data in savegame; metadata is marked with timestamp. I open this saved game for writing via `OpenWithManualConflictResolution()`, and perform `CommitUpdate()` with new data and metadata (timestamp); callback returns `Success`. Then I reopen this saved game for reading via `OpenWithManualConflictResolution()` and perform `ReadBinaryData()`.

Expected result: open succeeds with new metadata (timestamp), and read succeeds with new data.

Actual result: open succeeds with new metadata (timestamp), read also succeeds, but with **old** data.

Initial snapshot was created on another device; no conflicts were detected.

**Comment by claywilkinson** [comment] 2015-06-29 15:57
There has been substantial fixes to the SavedGames API implementation on the server side.  Can you confirm that this issue is resolved for you?  Thanks!

**Comment by Inoc** [comment] 2015-10-22 07:58
Hi,

I'm facing the same problem.

I save a simple string data and recieve the "success" callback from "savedGameClient.CommitUpdate".

Then I try to Open and Read again the data file. I can see that the metadata changed with the new totalPlayedTime but the data are the old ones.

I've tried different ConflictResolution strategies but mainly "UseLongestPlaytime". I just updated with the last release but the problem persists.

Do you have any idea to resolve this problem ?

Thank you

**Comment by bbbreimmm** [comment] 2015-12-22 16:18
We are currently encoutering the same problem right now in our project, but updating to the latest version will not be done right now because of how we handled the GooglePlay lib for other plugins to work around the multi-dex limitations of Unity before 5.3. Just wanted to chime in on the issue by mentionning that we are able to 100% repro the issue with the following steps:

1. Advance the date of the device to several days in the future, then start the game.
2. Upload your save to the Cloud, then kill the application.
3. Set the device to the real time and date, then restart the game.
4. Make some progress in the game, then try to upload the save.
5. Notice that the Upload is said to be successful, but that you can only download the save from "the future".

As mentionned, the meta-data gets updated, but the raw save data always remain the one from the "future save". Tried multiple conflict resolution startegies, all of them resulting in the same behaviour. The issue can be resolved by pushing to the cloud with an even more advanced local time, or just by waiting to catch back up to the fake future date.

Hope this helps in resolving the issue ;)

**Comment by claywilkinson** [comment] 2015-12-22 19:28
Thanks @bbbreimmm  for the clear reproduction steps.  I'll pass them along and let you know when there is an update.

**Comment by claywilkinson** [comment] 2017-01-06 17:36
The issue has been fixed in Aug/Sep of 2016.

**Closed by claywilkinson** 2017-01-06 17:36 UTC
