### ISSUE TITLE
Accepting invites room connection fail - ShutdownState

### ISSUE THREAD

**Issue by ZenithCode** [playgameservices/play-games-plugin-for-unity#351] opened 2015-01-07 17:15 UTC
In my game, I receive an invitation, accept, the room is created and the game starts fine. This works fine the first time you accept an invite.  If you try a second time however, the room always fails.

These are the logs:
//First Invite works fine - then we exit room to accept the other invitation
`[Play Games Plugin DLL] 01/07/15 17:59:11 +01:00 DEBUG: Entering state: LeavingRoom`
`[Play Games Plugin DLL] 01/07/15 17:59:11 +01:00 DEBUG: Entering state: ShutdownState`
`[Play Games Plugin DLL] 01/07/15 17:59:11 +01:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.`
`[Play Games Plugin DLL] 01/07/15 17:59:12 +01:00 DEBUG: Entering internal callback for InternalLeaveRoomCallback`

//Second invitation
`17:59:49.468: I/Unity(14041): Got invitation from ****`
` [Play Games Plugin DLL] 01/07/15 17:59:55 +01:00 DEBUG: Entering state: BeforeRoomCreateStartedState`
` [Play Games Plugin DLL] 01/07/15 17:59:55 +01:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.`
` [Play Games Plugin DLL] 01/07/15 17:59:55 +01:00 DEBUG: Entering internal callback for RealtimeManager#InternalFetchInvitationsCallback`
` [Play Games Plugin DLL] 01/07/15 17:59:55 +01:00 DEBUG: OnData Callback has addr: 26396`
` [Play Games Plugin DLL] 01/07/15 17:59:55 +01:00 DEBUG: BeforeRoomCreateStartedState.IsNonPreemptable: Is preemptable by default.`
` [Play Games Plugin DLL] 01/07/15 17:59:55 +01:00 DEBUG: Entering state: RoomCreationPendingState`
` [Play Games Plugin DLL] 01/07/15 17:59:55 +01:00 DEBUG: RoomCreationPendingState.OnStateEntered: Defaulting to no-op.`
` [Play Games Plugin DLL] 01/07/15 17:59:57 +01:00 DEBUG: Entering internal callback for RealtimeManager#InternalRealTimeRoomCallback`
` [Play Games Plugin DLL] 01/07/15 17:59:57 +01:00 DEBUG: Entering state: ShutdownState`
` [Play Games Plugin DLL] 01/07/15 17:59:57 +01:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.`
`17:59:57.106: I/Unity(14041): On Room Connected State: False`
`[Play Games Plugin DLL] 01/07/15 18:01:14 +01:00 DEBUG: Ignoring REMOVED for invitation ChEKCQit5-fqqwcQAhABGAEgARD-_J22rt2fp20`

Can anyone help with this please?
Thanks

**Comment by ZenithCode** [comment] 2015-01-08 13:20
I've tested this on Android on another project and I get the same behavior.  Can anyone shed light on why the room goes to 'Shutdown state'?

**Comment by ZenithCode** [comment] 2015-01-08 19:07
I've created a very small sample project to demonstrate the problem and maybe helps developers fix it quicker! :-)

https://dl.dropboxusercontent.com/u/9385978/SampleGPGProject.rar

**Comment by TycEkart** [comment] 2015-01-23 13:35
I experience the same problem in the latest build (0.9.11).
I'm thinking of downgrading untill this bug is fixed. Does anyone know when this bug surfaced?

**Comment by claywilkinson** [comment] 2015-01-26 17:11
Thanks for the details. Tracking internally as 19142482

**Comment by mrggl** [comment] 2015-01-29 02:27
Hi all - this issue is fixed internally at head, and (fingers crossed) will go away with our next release.

In the meantime, I have found a simple workaround that should prevent the issue from occurring.

In your unity project, locate the code here:

https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/Platforms/Native/NativeRealtimeMultiplayerClient.cs#L191

and comment out "using (invitation)" along with the braces, i.e.:

```
                foreach (var invitation in response.Invitations()) {
                    //using(invitation) {
                        if (invitation.Id().Equals(invitationId)) {
                            using (var helper = HelperForSession(newRoom)) {
                                newRoom.StartRoomCreation(mNativeClient.GetUserId(),
                                    () => mRealtimeManager.AcceptInvitation(
                                        invitation, helper, newRoom.HandleRoomResponse));
                                return;
                            }
                        }
                    //}
                }
```

Let me know if that helps!

**Comment by TycEkart** [comment] 2015-01-29 08:44
I've just tried to apply the workaround. It does let you create a room, but there is never a call back on the methods of the RealTimeMultiplayerListener interface.

I'll just wait for an update :)


#Joined room for the second time#

[Play Games Plugin DLL] 01/29/15 9:30:27 +01:00 DEBUG: Entering state: BeforeRoomCreateStartedState
[Play Games Plugin DLL] 01/29/15 9:30:27 +01:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.
[Play Games Plugin DLL] 01/29/15 9:30:27 +01:00 DEBUG: OnData Callback has addr: 5348
[Play Games Plugin DLL] 01/29/15 9:30:27 +01:00 DEBUG: BeforeRoomCreateStartedState.IsNonPreemptable: Is preemptable by default.
[Play Games Plugin DLL] 01/29/15 9:30:27 +01:00 DEBUG: Entering state: RoomCreationPendingState
[Play Games Plugin DLL] 01/29/15 9:30:27 +01:00 DEBUG: RoomCreationPendingState.OnStateEntered: Defaulting to no-op.
[Play Games Plugin DLL] 01/29/15 9:30:28 +01:00 DEBUG: Entering internal callback for RealtimeManager#InternalRealTimeRoomCallback
[Play Games Plugin DLL] 01/29/15 9:30:28 +01:00 DEBUG: Entering state: ConnectingState
[Play Games Plugin DLL] 01/29/15 9:30:34 +01:00 DEBUG: Entering InternalOnParticipantStatusChangedCallback
[Play Games Plugin DLL] 01/29/15 9:30:34 +01:00 DEBUG: Entering internal callback for RealTimeEventListenerHelper#InternalOnRoomStatusChangedCallback
[Play Games Plugin DLL] 01/29/15 9:30:35 +01:00 DEBUG: Entering internal callback for RealTimeEventListenerHelper#InternalOnRoomConnectedSetChangedCallback
[Play Games Plugin DLL] 01/29/15 9:30:35 +01:00 DEBUG: New participants connected: p_CJXE-Lnl97X9XRAB,p_CO61sqOunoLgIxAB

[Play Games Plugin DLL] 01/29/15 9:30:35 +01:00 DEBUG: Fully connected! Transitioning to active state.
[Play Games Plugin DLL] 01/29/15 9:30:35 +01:00 DEBUG: Entering state: ActiveState
[Play Games Plugin DLL] 01/29/15 9:30:35 +01:00 DEBUG: Entering internal callback for RealTimeEventListenerHelper#InternalOnRoomConnectedSetChangedCallback
[Play Games Plugin DLL] 01/29/15 9:30:35 +01:00 DEBUG: Updated participant statuses: [Participant: 'Player 7537' (id p_CJXE-Lnl97X9XRAB), status=Joined, player=NULL, connected=True],[Participant: 'A Co' (id p_CO61sqOunoLgIxAB), status=Joined, player=[Player: 'A Co' (id 105214404220489206580)], connected=True]

[Play Games Plugin DLL] 01/29/15 9:30:36 +01:00 DEBUG: Entering InternalOnDataReceived: 5348
[Play Games Plugin DLL] 01/29/15 9:35:48 +01:00 DEBUG: Entering internal callback for RealTimeEventListenerHelper#InternalOnRoomConnectedSetChangedCallback
[Play Games Plugin DLL] 01/29/15 9:35:48 +01:00 DEBUG: Updated participant statuses: [Participant: 'Player 7537' (id p_CJXE-Lnl97X9XRAB), status=Left, player=NULL, connected=False],[Participant: 'A Co' (id p_CO61sqOunoLgIxAB), status=Joined, player=[Player: 'A Co' (id 105214404220489206580)], connected=False]


#And leaving the room here#

!!! [Play Games Plugin DLL] 01/29/15 9:35:48 +01:00 WARNING: Player was disconnected from the multiplayer session.
[Play Games Plugin DLL] 01/29/15 9:35:48 +01:00 DEBUG: Entering InternalOnParticipantStatusChangedCallback
[Play Games Plugin DLL] 01/29/15 9:35:48 +01:00 DEBUG: Entering internal callback for RealTimeEventListenerHelper#InternalOnRoomConnectedSetChangedCallback
[Play Games Plugin DLL] 01/29/15 9:35:48 +01:00 DEBUG: Updated participant statuses: [Participant: 'Player 7537' (id p_CJXE-Lnl97X9XRAB), status=Left, player=NULL, connected=False],[Participant: 'A Co' (id p_CO61sqOunoLgIxAB), status=Joined, player=[Player: 'A Co' (id 105214404220489206580)], connected=False]

[Play Games Plugin DLL] 01/29/15 9:35:48 +01:00 DEBUG: Entering state: LeavingRoom
[Play Games Plugin DLL] 01/29/15 9:35:48 +01:00 DEBUG: Entering state: ShutdownState
[Play Games Plugin DLL] 01/29/15 9:35:48 +01:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.
[Play Games Plugin DLL] 01/29/15 9:35:48 +01:00 DEBUG: Entering internal callback for InternalLeaveRoomCallback

**Comment by ZenithCode** [comment] 2015-01-29 11:05
@mrggl - This solved my problem. :-)  

Invitations are not always received - not sure if problem is related to this because they've always been a bit shaky.

**Comment by ngandtt** [comment] 2015-01-30 09:32
This acceptance invitation makes me crazy! Last week, I tested, it called OnInvitationReceived but not now. I have to call AcceptFromInbox to get notification from Google play game services, and then when I accepted, it doesn't start match but leaving room with message like above...

**Comment by mrggl** [comment] 2015-01-30 19:28
@ZenithCode glad to hear it.

Closing this out.

**Closed by mrggl** 2015-01-30 19:28 UTC

**Comment by tcossairt** [comment] 2015-03-30 20:04
I see you closed this out -- what plugin revision was this fixed?  I don't see it noted in any changelog notes.

**Comment by ArmandCloud** [comment] 2015-05-02 19:51
I still have this problem,
Same logs produced with 9.15
Regards,

**Comment by VicEsquivel** [comment] 2016-02-14 05:58
I had been working fine, but 4 days ago this very same error started appearing out of nowhere... 

Even old versions of my prototype that used to work are presenting this very same issue not only on the send invite match, but on the quick match finder... 
 Im getting this message, did any of you find the cause of it?

WARNING: Player was disconnected from the multiplayer session.
(Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

I am using GooglePlayGamesPlugin-0.9.27...

**Comment by claywilkinson** [comment] 2016-02-15 16:58
Is is consistently happening?  Can you share a log leading up to the disconnection?  I don't want to blame the network, but is it possible it is an intermittent connectivity issue?

**Comment by VicEsquivel** [comment] 2016-02-15 17:42
@claywilkinson 

Yes, This is consistently happening. I am no longer able to start a Pvp match... 

I have tested it with multiple web access points, and even with the mobile celular data network, with no luck...

This is the log. I opened an issue for this: https://github.com/playgameservices/play-games-plugin-for-unity/issues/977


**My games Log:**
02-15 11:13:24.033  16732-16765/? I/Unity﹕ Game State: InitialSync
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.063  16732-16765/? I/Unity﹕ Match State: SettingUp
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.063  16732-16765/? I/Unity﹕ Game State: InitialSync
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.103  16732-16765/? I/Unity﹕ Match State: SettingUp
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.103  16732-16765/? I/Unity﹕ Game State: InitialSync
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.133  16732-16765/? I/Unity﹕ Match State: SettingUp
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.133  16732-16765/? I/Unity﹕ Game State: InitialSync
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.163  16732-16765/? I/Unity﹕ Match State: SettingUp
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.163  16732-16765/? I/Unity﹕ Game State: InitialSync
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.193  16732-16765/? I/Unity﹕ Match State: SettingUp
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.193  16732-16765/? I/Unity﹕ Game State: InitialSync
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.233  16732-16765/? I/Unity﹕ Match State: SettingUp
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.233  16732-16765/? I/Unity﹕ Game State: InitialSync
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.253  16732-16874/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:13:24 -06:00 DEBUG: Entering internal callback for RealTimeEventListenerHelper#InternalOnRoomConnectedSetChangedCallback
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.263  16732-16765/? I/Unity﹕ Match State: SettingUp
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.263  16732-16765/? I/Unity﹕ Game State: InitialSync
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.303  16732-16765/? I/Unity﹕ Match State: SettingUp
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.303  16732-16765/? I/Unity﹕ Game State: InitialSync
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.303  16732-16874/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:13:24 -06:00 DEBUG: New participants connected:
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.303  16732-16874/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:13:24 -06:00 DEBUG: Fully connected! Transitioning to active state.
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.303  16732-16874/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:13:24 -06:00 DEBUG: Entering state: ActiveState
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.313  16732-16874/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:13:24 -06:00 DEBUG: Entering internal callback for RealTimeEventListenerHelper#InternalOnRoomConnectedSetChangedCallback
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.343  16732-16874/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:13:24 -06:00 DEBUG: Updated participant statuses: [Participant: 'Code 91 Mx' (id p_CP-s8tizxNSo2QEQAQ), status=Joined, player=[Player: 'Code 91 Mx' (id 116188677374566560658)], connected=False],[Participant: 'Jugador 1128' (id p_CM-HkszMg6vniwEQAQ), status=Joined, player=NULL, connected=False]
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.353  16732-16874/? W/Unity﹕ !!! [Play Games Plugin DLL] 02/15/16 11:13:24 -06:00 WARNING: Player was disconnected from the multiplayer session.
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.403  16732-16765/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:13:24 -06:00 DEBUG: Entering state: LeavingRoom
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.883  16732-16874/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:13:24 -06:00 DEBUG: Entering internal callback for InternalLeaveRoomCallback
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.883  16732-16874/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:13:24 -06:00 DEBUG: Entering state: ShutdownState
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.883  16732-16874/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:13:24 -06:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:13:24.893  16732-16765/? I/Unity﹕ TearDownMatch is called!



**Quiz Racer Sample Project**
02-15 11:32:02.503  19561-19582/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:32:02 -06:00 DEBUG: Entering state: BeforeRoomCreateStartedState
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:02.503  19561-19582/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:32:02 -06:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:02.503  19561-19582/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:32:02 -06:00 DEBUG: QuickGame: Setting MinPlayersToStart = 1
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:02.513  19561-19582/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:32:02 -06:00 DEBUG: OnData Callback has addr: 35
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:02.513  19561-19582/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:32:02 -06:00 DEBUG: BeforeRoomCreateStartedState.IsNonPreemptable: Is preemptable by default.
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:02.513  19561-19582/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:32:02 -06:00 DEBUG: Entering state: RoomCreationPendingState
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:02.523  19561-19582/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:32:02 -06:00 DEBUG: RoomCreationPendingState.OnStateEntered: Defaulting to no-op.
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:04.623  19561-19627/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:32:04 -06:00 DEBUG: Entering internal callback for RealtimeManager#InternalRealTimeRoomCallback
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:05.723  19561-19627/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:32:05 -06:00 DEBUG: Entering InternalOnParticipantStatusChangedCallback
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:05.733  19561-19627/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:32:05 -06:00 DEBUG: Entering internal callback for RealTimeEventListenerHelper#InternalOnRoomStatusChangedCallback
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:06.553  19561-19627/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:32:06 -06:00 DEBUG: Entering internal callback for RealTimeEventListenerHelper#InternalOnRoomConnectedSetChangedCallback
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:06.603  19561-19627/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:32:06 -06:00 DEBUG: New participants connected:
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:06.603  19561-19627/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:32:06 -06:00 DEBUG: Fully connected! Transitioning to active state.
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:06.603  19561-19627/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:32:06 -06:00 DEBUG: Entering state: ActiveState
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:06.613  19561-19627/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:32:06 -06:00 DEBUG: Entering internal callback for RealTimeEventListenerHelper#InternalOnRoomConnectedSetChangedCallback
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:06.633  19561-19582/? I/Unity﹕ RaceManager.SetupTrack-> called
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:06.633  19561-19582/? I/Unity﹕ RaceManager.SetupTrack-> Self is [Participant: 'Code 91 Mx' (id p_CJPB1cLT_qDUgQEQAQ), status=Joined, player=[Player: 'Code 91 Mx' (id 116188677374566560658)], connected=False]
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:06.633  19561-19582/? I/Unity﹕ RaceManager.SetupTrack-> About to get a list of connected participants
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:06.633  19561-19627/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:32:06 -06:00 DEBUG: Updated participant statuses: [Participant: 'Code 91 Mx' (id p_CJPB1cLT_qDUgQEQAQ), status=Joined, player=[Player: 'Code 91 Mx' (id 116188677374566560658)], connected=False],[Participant: 'Jugador 3281' (id p_CIn08-iuufrnvgEQAQ), status=Joined, player=NULL, connected=False]
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:06.633  19561-19627/? W/Unity﹕ !!! [Play Games Plugin DLL] 02/15/16 11:32:06 -06:00 WARNING: Player was disconnected from the multiplayer session.
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:06.653  19561-19582/? I/Unity﹕ RaceManager.SetupTrack-> Racers are  System.Collections.Generic.List`1[GooglePlayGames.BasicApi.Multiplayer.Participant] with count of 0
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:06.663  19561-19582/? I/Unity﹕ Showing Playing Panel!
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:06.673  19561-19582/? I/Unity﹕ PlayingEvents.Start -> Starting Playing!! Race state is Playing
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:06.743  19561-19582/? I/Unity﹕ RaceManager.Instance.State = Aborted
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:06.743  19561-19582/? I/Unity﹕ Showing MainMenu!
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:06.843  19561-19582/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:32:06 -06:00 DEBUG: Entering state: LeavingRoom
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:07.333  19561-19627/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:32:07 -06:00 DEBUG: Entering internal callback for InternalLeaveRoomCallback
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:07.333  19561-19627/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:32:07 -06:00 DEBUG: Entering state: ShutdownState
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:07.333  19561-19627/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:32:07 -06:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-15 11:32:24.193  19561-19582/? I/Unity﹕ [Play Games Plugin DLL] 02/15/16 11:32:24 -06:00 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
