### ISSUE TITLE
Turn based multiplayer latest match not passed when notified in Game

### ISSUE THREAD

**Issue by miacoviello** [playgameservices/play-games-plugin-for-unity#294] opened 2014-11-29 20:44 UTC
When in a turn based match on two iOS devices:

Player 1:
Turn 1:
- Select game and turn via PlayGamesPlatform.Instance.TurnBased.AcceptFromInbox
- Play Player 1, Turn 1 then call PlayGamesPlatform.Instance.TurnBased.TakeTurn
  providing refreshed game state.  
- It is now player 2 turn.  Keep game open - Goto Player 1, Turn 1 below.

Turn 2:
- Notification arrives via GotMatch(TurnBasedMatch match, bool shouldAutoLaunch) callback.
- Since it is my turn for the current game I'm playing, automatically load the match data provided from the match object.
-  The match object contains Player 1, Turn 1 state and NOT Player 2, Turn 1 State as expected.

Player 2:
Turn 1:
-  Push notification arrives that it is my turn.
- Open game, then select game and turn via PlayGamesPlatform.Instance.TurnBased.AcceptFromInbox
- Play Player 2, Turn 1 then call PlayGamesPlatform.Instance.TurnBased.TakeTurn
  providing refreshed game state.  
- It is now player 1 turn 2 turn.  Keep game open - Goto Player 1, Turn 2 above.

**Comment by claywilkinson** [comment] 2015-01-24 00:30
Is this still happening?  Can you reproduce this issue with one of the samples - such as TicTacToss?

**Comment by miacoviello** [comment] 2015-02-03 14:51
Hi Clayton,
this is still happening but i'll try to reproduce with tic tac toss if you
like.  I wont get to it until this weekend, and have just updated to the
latest release of the plugin yesturday.  I'll test with the new version and
if it continues I'll email you back.

Thanks,
Michael Iacoviello

On Fri, Jan 23, 2015 at 7:30 PM, Clayton Wilkinson <notifications@github.com
> wrote:

> Is this still happening? Can you reproduce this issue with one of the
> samples - such as TicTacToss?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/playgameservices/play-games-plugin-for-unity/issues/294#issuecomment-71289913>
> .
>



-- 
Michael Iacoviello
905-902-1173

**Comment by claywilkinson** [comment] 2015-02-03 15:43
@miacoviello  - Thanks!  I do't think the latest update will have any effect  - it was just a small change to enable automated building (and testing :) ).

**Comment by claywilkinson** [comment] 2015-06-12 15:37
Closing this issue since  its been months.  The turnbased games are working OK in the latest plugin on android and iOS.  Please open another issue if you are still having questions.

**Closed by claywilkinson** 2015-06-12 15:37 UTC

**Comment by miacoviello** [comment] 2015-06-12 22:24
Hi Clayton,  this is confirmed fixed in the latest add.
