### ISSUE TITLE
Invitation delegate not called

### ISSUE THREAD

**Issue by aditya2** [playgameservices/play-games-plugin-for-unity#1139] opened 2016-05-05 13:27 UTC
I m trying to make a real time multiplayer game with play game services but before working on game i m trying the invitation system but constantly running in this huge problem ...

1: I m sending invitation to Phone B
2: Application is not running on Phone B 
3: Phone B is getting invitation in notification bar
4: Clicking on invitation in notification bar eventually starting up my application but without invitation delegate being called

One thing i want to mention here is that i don't know how to take out log from phone, i know there is something called Logcat but i don't know how to use it, if you could tell me how to take logs of play games services then please tell so that i could paste logs also

**Comment by claywilkinson** [comment] 2016-05-06 16:07
[Logcat](http://developer.android.com/tools/debugging/debugging-log.html) is used to access the log of an Android device.  It is a command line tool (or Android Studio window). http://developer.android.com/tools/debugging/debugging-log.html describes how to use it.

**Comment by pt5011** [comment] 2018-12-26 10:09
Hi,

I can confirm that this issue still exists in the latest version 0.9.57. It happens with both the InvitationDelegate and the MatchDelegate (for turn-based). And it only occurs when the app is not running. If the app is running (either in foreground or background) the delegates are called properly as expected.

I dug into GPGS code did some debugging and found out that when the app is launched from a notification, the internal methods NativeClient.HandleInvitation() and NativeTurnBasedMultiplayerClient.HandleMatchEvent() are not called , which is why the registered InvitationDelegate and MatchDelegate don't run. In the other case, these methods are called and the registered delegates run as expected. The problem is these methods seem to be called by the C++ side of GPGS and there's not much we can do with the available C# scripts to work around the issue.

@claywilkinson Could you please look into this? It is quite a big problem as it's very common for multiplayer notifications to come while the app is not running, and without the delegates running there's no way to respond to these notifications properly.

Thank you!

**Comment by DataGreed** [comment] 2019-06-11 16:47
This is definitely an issue worth fixing 🤞

**Comment by kirbyderby2000** [comment] 2019-08-20 18:26
It would be beautiful if the invitation delegate was called upon launching the game via accepting an invitation. 🙌

**Comment by dryn27** [comment] 2019-09-24 19:37
Hey, this is something you should work on, Google.

**Comment by ozdemir08** [comment] 2020-02-27 11:59
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.

**Closed by ozdemir08** 2020-02-27 11:59 UTC
