### ISSUE TITLE
Crash after signing into Play Game Services

### ISSUE THREAD

**Issue by Splaktar** [playgameservices/play-games-plugin-for-unity#545] opened 2015-05-30 22:28 UTC
Unity 5.0.2 and games plugin 0.9.20 on a Project Tango tablet (Android 4.4.2) with the latest Google Play Game Services (3.0.11).

```
05-30 17:21:28.559    4000-4044/? E/GamesNativeSDK﹕ Can't find com/google/android/gms/games/Games.Achievements: java.lang.NoSuchFieldError: no type "Lcom/google/android/gms/games/achievement/Achievements;" found and so no field "Achievements" could be found in class "Lcom/google/android/gms/games/Games;" or its superclasses.
05-30 17:21:28.559    4000-4044/? A/art﹕ art/runtime/check_jni.cc:64] JNI DETECTED ERROR IN APPLICATION: fid == null
05-30 17:21:28.559    4000-4044/? A/art﹕ art/runtime/check_jni.cc:64]     in call to GetStaticObjectField
05-30 17:21:28.559    4000-4044/? A/art﹕ art/runtime/check_jni.cc:64] "main_dispatch" prio=5 tid=19 Runnable
05-30 17:21:28.559    4000-4044/? A/art﹕ art/runtime/check_jni.cc:64]   | group="main" sCount=0 dsCount=0 obj=0x648efa60 self=0x4d30d040
05-30 17:21:28.559    4000-4044/? A/art﹕ art/runtime/check_jni.cc:64]   | sysTid=4044 nice=0 cgrp=apps sched=0/0 handle=0x4d3111e0
05-30 17:21:28.561    4000-4044/? A/art﹕ art/runtime/check_jni.cc:64]   | state=R schedstat=( 6848334 18164918 55 ) utm=0 stm=0 core=1 HZ=100
05-30 17:21:28.562    4000-4044/? A/art﹕ art/runtime/check_jni.cc:64]   | stack=0x4f053000-0x4f057000 stackSize=1016KB
05-30 17:21:28.562    4000-4044/? A/art﹕ art/runtime/check_jni.cc:64]   (no managed stack frames)
05-30 17:21:28.562    4000-4044/? A/art﹕ art/runtime/check_jni.cc:64]
05-30 17:21:28.576    4000-4044/? A/libc﹕ Fatal signal 11 (SIGSEGV) at 0x00000023 (code=1), thread 4044 (main_dispatch)
05-30 17:21:29.023     898-1053/? E/InputDispatcher﹕ channel '64f86528 com.gdg.chs/com.google.unity.GoogleUnityActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
0
```

There also seem to be some other issues:
```
05-30 17:21:02.925    4000-4020/? E/GamesNativeSDK﹕ Exception in dalvik/system/DexClassLoader.loadClass: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.games.NativeSdkEntryPoints" on path: DexPathList[[zip file "/data/data/com.gdg.chs/app_.gpg.classloader/de80b70ed0da0dfe988a41fa560612ee.jar"],nativeLibraryDirectories=[/system/lib, /vendor/lib, /system/lib]].
```

**Comment by claywilkinson** [comment] 2015-06-01 22:56
Thanks for the stacktrace.  We'll take a look.

The other issue about the NativeSdkEntryPoints can be safely ignored.

**Comment by claywilkinson** [comment] 2015-06-02 17:16
@Splaktar  - Can you post the whole log?  There is some initialization messages that should be before this error.  Also, can you double check that you have the Play Services SDK downloaded and run Windows > Google Play Games > Setup > Android Setup... 
 Usually this is caused by the jar file missing in the apk.

**Comment by Splaktar** [comment] 2015-06-06 13:09
Yes, I can confirm that I have the Play Services SDK downloaded and that I ran the Android Setup and put in my proper application id. This was working fine for me, so I know that the configuration was setup properly. But after making some code changes, this started to occur every time that I launched the app.

I no longer have access to a Tango tablet, so additional stack trace messages are not possible.

**Comment by claywilkinson** [comment] 2015-06-08 22:32
So is this an active issue you are having or can I close it?

**Comment by Splaktar** [comment] 2015-06-09 03:20
It blocked me from using Play Game Services during a hackathon. Thought you might want to fix it. But go ahead and close it.

**Comment by claywilkinson** [comment] 2015-06-09 15:26
@Splaktar -  thanks for the feedback! I'll take a look and see if I can re-create it on a Tango.

**Comment by bigbirdtommy** [comment] 2015-09-18 13:57
Any progress on this: I just bumped into it today as well.

Unity 5.2.0f  
Project Tango 4.4.2   Build: KOT49H.150811

"Successfully connected to Google Play" followed by hard crash of app.

V/GamesNativeSDK( 9113): Play Games callback indicates connection.
I/GamesNativeSDK( 9113): Successfully connected to Google Play.
E/GamesNativeSDK( 9113): Can't find com/google/android/gms/games/Games.Achievements: java.lang.NoSuchFieldError: no type "Lcom/google/android/gms/games/achievement/Achievements;" found and so no field "Achievements" could be found in class "Lcom/google/android/gms/games/Games;" or its superclasses.
F/art     ( 9113): art/runtime/check_jni.cc:64] JNI DETECTED ERROR IN APPLICATION: fid == null
F/art     ( 9113): art/runtime/check_jni.cc:64]     in call to GetStaticObjectField
F/art     ( 9113): art/runtime/check_jni.cc:64] "main_dispatch" prio=5 tid=20 Runnable
F/art     ( 9113): art/runtime/check_jni.cc:64]   | group="main" sCount=0 dsCount=0 obj=0x649d1d50 self=0x4ad2dc38
F/art     ( 9113): art/runtime/check_jni.cc:64]   | sysTid=9330 nice=0 cgrp=apps sched=0/0 handle=0x4abbf8c8
F/art     ( 9113): art/runtime/check_jni.cc:64]   | state=R schedstat=( 3164586 552414 15 ) utm=0 stm=0 core=1 HZ=100
F/art     ( 9113): art/runtime/check_jni.cc:64]   | stack=0x4f107000-0x4f10b000 stackSize=1016KB
F/art     ( 9113): art/runtime/check_jni.cc:64]   (no managed stack frames)
F/art     ( 9113): art/runtime/check_jni.cc:64] 
I/Unity   ( 9113):  [Play Games Plugin DLL] 09/18/15 8:52:30 -05:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID
I/Unity   ( 9113):  
I/Unity   ( 9113): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   ( 9113):

**Comment by bigbirdtommy** [comment] 2015-09-18 13:58
App works happily on my N6.

FYI

**Comment by claywilkinson** [comment] 2015-09-18 14:32
Thanks for the information.  Can you share what version of Google Play Services and the Play Games App you are running?

**Comment by bigbirdtommy** [comment] 2015-09-18 14:35
GP Services:  8.1.15  (2250156-036)

GPG app 3.2.21  (2197783-036)

**Comment by tyrmullen** [comment] 2015-11-20 19:42
The fact that it connected successfully to Google Play means that it found the other classes in com/google/android/gms/ just fine at connection time, so it was accessing the google-play-services.jar without problems from the main program thread.  When kicked over to out "main_dispatch" thread, however, it seems to have lost that ability.

Unfortunately, the version of the ART JRE which shipped with KitKat (4.4.2) was a "developer preview" version, and it seems to be the case that the parts of the JRE which are particularly prone to errors/strange crashes/issues are native C++ calls (and specifically multi-threading in C++).  So there may be a workaround for this particular issue, but crashes and crazy behavior native-side are somewhat expected for that particular environment.

The good news is that the old Dalvik (which shipped with 4.4.2 and before) didn't have any such issues, and the even better news is that I've encountered no such issues with any version of ART since ART became the standard.  So Lollipop+ with ART or KitKat- with Dalvik should both be fine.  I imagine that will fix your issues (if that's something you can test out readily with the Project Tango device you're using?), but have yet to try this out myself.

**Comment by bigbirdtommy** [comment] 2015-11-23 17:31
Unfortunately, the OS version on Tango seems static at 4.4.2... (rumor is
forever as there are no Google resources available for the migration)...
Sounds like it is just DOA then.

Thanks!
-tom

Tom Myers
Google Voice number: 651-538-0475
Give me a call!  It should reach me anywhere! :)
https://google.com/+ThomasBMyers

**Comment by claywilkinson** [comment] 2016-01-13 23:24
At the current time, the Google Play Game Services C++ API is not supported on Tango devices.  You  can use the Java API via JNI when targeting Tango.  If you look at the history of the plugin, there is an older version that uses JNI vs. the C++ API for the implementation.

**Closed by claywilkinson** 2016-01-13 23:24 UTC
