### ISSUE TITLE
Social.localUser.Authenticate crashed when update play-services-games-10.2.1?

### ISSUE THREAD

**Issue by buckbim** [playgameservices/play-games-plugin-for-unity#1660] opened 2017-03-23 03:34 UTC
Hi Friends.I'm using unity 5.5.2f1 and update latest play-services-games-10.2.1 version for some reason I can't down it.When I login with Auth as above then Unity crash immediately.
Does Anyone have solutions?
Thank you so much.

**Comment by arcrus** [comment] 2017-03-24 10:51
#1629  <-- have a look

**Comment by buckbim** [comment] 2017-03-27 01:57
Thanks @arcrus But as I'm say I don't wanna reduce version 10.0.1.I wanna use 10.2.0 to build to android studio.

**Comment by claywilkinson** [comment] 2017-04-05 00:16
An updated version should be coming this week.  Closing this issue as a dupe of #1604

**Closed by claywilkinson** 2017-04-05 00:16 UTC
