### ISSUE TITLE
IVideoClient not in package

### ISSUE THREAD

**Issue by dashanddot** [playgameservices/play-games-plugin-for-unity#2388] opened 2018-12-06 22:55 UTC
IVideoClient.cs not in package (GooglePlayGames\BasicApi\Video)

**Comment by olehkuznetsov** [comment] 2018-12-07 17:22
try to delete plugin and to re-import it.

**Comment by olehkuznetsov** [comment] 2018-12-14 15:12
Reproduced this after upgrading from 0.9.51 to 0.9.56.

**Comment by olehkuznetsov** [comment] 2018-12-18 17:22
Fixed in 0.9.57

**Closed by olehkuznetsov** 2018-12-18 17:22 UTC
Labels: bug

**Comment by twomedia** [comment] 2019-06-17 07:51
@olehkuznetsov This same issue seems to be happening after upgrading to the latest release (v0.9.64)

**Comment by olehkuznetsov** [comment] 2019-06-17 08:56
From which version have you updated?
Try to delete Assets->GooglePlayGames and reimport the plugin, please.

**Comment by ciftciMert** [comment] 2019-06-27 16:42
> From which version have you updated?
> Try to delete Assets->GooglePlayGames and reimport the plugin, please.

How to delete plugin?
