### ISSUE TITLE
Failed to sign in with Google Play Games.

### ISSUE THREAD

**Issue by vuvandong** [playgameservices/play-games-plugin-for-unity#1655] opened 2017-03-19 08:54 UTC
Android sdk tools 25.3.1. Downloaded to Android Studio 2.3.
I used to Unity 5.5.2f.
Plugin 0.9.36.

**Comment by siddharth3322** [comment] 2017-03-20 08:34
I was also facing same problem when I try to authenticate its force close for me.

Here are few more details from my side. I tried with Minimal project as well but same thing happening with me.

![gpgerror_1](https://cloud.githubusercontent.com/assets/3082151/24092708/e439bebc-0d75-11e7-9fcb-0733ba540b05.png)

APK File Link
[https://drive.google.com/open?id=0B6CFlS0aZDPiR3VrTk9WS0F6Szg](url)

Source Code Link
[https://drive.google.com/open?id=0B6CFlS0aZDPiU0x3dGxyclREMFk](url)

Please give me some quick help in this so I can submit my project.

**Comment by vuvandong** [comment] 2017-03-21 13:34
I dont dev android app. But, try this #1629

**Comment by claywilkinson** [comment] 2017-04-05 14:17
There will be an update to the plugin this week that will fix the incompatibility with play-services 10.2.  Closing this issue as a duplicate of #1604.

**Closed by claywilkinson** 2017-04-05 14:17 UTC
