### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by jennyfish** [playgameservices/play-games-plugin-for-unity#1663] opened 2017-03-27 11:18 UTC
Exception in dalvik/system/DexClassLoader.loadClass: java.lang.IncompatibleClassChangeError: Class com.google.android.gms.games.NativeSdkCallbacks implements non-interface class com.google.android.gms.nearby.connection.Connections$ConnectionRequestListener (declaration of 'com.google.android.gms.games.NativeSdkCallbacks' appears in /data/user/0/com.gamesky.pol/app_.gpg.classloader/d75c8e1bbeab9e1ddffb9d332585db71.jar).

**Comment by claywilkinson** [comment] 2017-04-05 00:15
Closing as a dupe of #1604 - there is an update coming this week to fix this.

**Closed by claywilkinson** 2017-04-05 00:15 UTC
