### ISSUE TITLE
Error: Invalid classname: Method - VersionHandlerImpl.UpdateVersionedAssets not found

### ISSUE THREAD

**Issue by andoprof** [playgameservices/play-games-plugin-for-unity#2753] opened 2019-10-17 11:24 UTC
"Invalid classname: Method - VersionHandlerImpl.UpdateVersionedAssets not found"
current-build/GooglePlayGamesPlugin-0.10.04.unitypackage
- Unity 2018.4.11f1
- Firebase 6.6.0
Please fix it as soon as! Thanks!

Log:
Exception: Method VersionHandlerImpl.UpdateVersionedAssets not found
Google.VersionHandler.InvokeMethod (System.Type type, System.Object objectInstance, System.String methodName, System.Object[] args, System.Collections.Generic.Dictionary`2[TKey,TValue] namedArgs) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandler/src/VersionHandler.cs:554)
Google.VersionHandler.InvokeStaticMethod (System.Type type, System.String methodName, System.Object[] args, System.Collections.Generic.Dictionary`2[TKey,TValue] namedArgs) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandler/src/VersionHandler.cs:485)
Google.VersionHandler.InvokeImplMethod (System.String methodName, System.Object[] args, System.Collections.Generic.Dictionary`2[TKey,TValue] namedArgs, System.Boolean schedule) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandler/src/VersionHandler.cs:416)
Google.VersionHandler.UpdateVersionedAssets (System.Boolean forceUpdate) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandler/src/VersionHandler.cs:383)
GooglePlayGames.Editor.GPGSAndroidSetupUI.PerformSetup (System.String clientId, System.String classDirectory, System.String className, System.String resourceXmlData, System.String nearbySvcId) (at Assets/GooglePlayGames/Editor/GPGSAndroidSetupUI.cs:121)
UnityEngine.Debug:LogException(Exception)
GooglePlayGames.Editor.GPGSAndroidSetupUI:PerformSetup(String, String, String, String, String) (at Assets/GooglePlayGames/Editor/GPGSAndroidSetupUI.cs:125)
GooglePlayGames.Editor.GPGSAndroidSetupUI:DoSetup() (at Assets/GooglePlayGames/Editor/GPGSAndroidSetupUI.cs:330)
GooglePlayGames.Editor.GPGSAndroidSetupUI:OnGUI() (at Assets/GooglePlayGames/Editor/GPGSAndroidSetupUI.cs:302)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by firegate666** [comment] 2019-10-17 12:49
I can confirm the same thing with Unity 2019.3-beta

You use Setup to put in your XML and then you get this error. When you build, you get a warning that says "Play Services is not configured and will not work properly" and you client crashes as soon as you try authenticate

I tried this package GooglePlayGamesPlugin-0.10.04.unitypackage, but also the 3 older ones. None works.

**Comment by cyberangel67** [comment] 2019-10-18 01:18
Also getting this same error

**Comment by cyberangel67** [comment] 2019-10-18 04:14
If it helps I have done a step through of the  code and it fails on this line

Line 119 GPGSAndroidSetupUI.cs
Google.VersionHandler.UpdateVersionedAssets(forceUpdate: true);

**Comment by 0Cristofer** [comment] 2019-10-18 20:32
Confirmed on Unity 2019.2.7f2

**Comment by GladFox** [comment] 2019-10-19 03:53
Confirmed on Unity 2019.2.8f1

**Comment by real-mikhail** [comment] 2019-10-19 10:26
Getting this error on v0.10.04.
v0.9.64 works like a charm for me.

**Comment by sunio00000** [comment] 2019-10-19 17:34
Confirmed on Unity 2019.2.9f1
and
v0.9.64 works for me. (before install, have to delete installed Assets/PlayerServicesResolver)

**Comment by NunoDinisSantos** [comment] 2019-10-22 10:43
Unity 2019.1.10f1 is also getting this error.
v0.9.64 gives me an error when I try to upload to the google play. 

I'm using v9.5.0 but I can't login. I get 16 warnings in the pre-lauch report. Leaderboards and achievements do nothing when I click on them (authentication always returns false).

Any idea on when the fix comes ?

**Comment by josephsipos** [comment] 2019-10-23 01:59
Confirmed on Unity 2019.2.9f1... Any idea of when a fix is coming?

**Comment by 0Cristofer** [comment] 2019-10-23 04:19
So, I tested a couple things, and it looks like the problem is either the plugin wasn't updated for the newest version of the resolver or the resolver has problems.
What I did:
Tested Play Services 0.9.64 + resolver 1.2.2xx
Tested Play Services 10.0.04 + resolver 1.2.2xx

In both instances this error started happening after resolver 1.2.223, 223 works fine.
My guess would be that something is new in 224 and above and the Play Services plugin wasn't updated (so the problem would be with the Play Services plugin), or there is a problem with the Resolver plugin starting at 224 (the problem would be with the Resolver plugin).

**Comment by YauheniHerasimenka** [comment] 2019-10-23 06:38
Same the problem in Unity 2017.4.17f1 GPGs 0.10.04

**Comment by NunoDinisSantos** [comment] 2019-10-23 09:36
Hey guys ! I managed to fix mine. However, mine was due to another plugin conflict.
I have google mobile ads AND google play games. If you guys are having issues on implementing both, do this:

- erase folders of google play games and google mobile ads (along with playservices resolver and plugin) 
- import google play games v0.9.64 (everything)
- import google mobile ads **VERSION 3.17** (THIS IS IMPORTANT. ONLY THIS VERSION WORKED FOR ME), WITHOUT playservices resolver.
- Let the unity compile and then do **Force Resolve**
- You should be able to setup google play games now
- Change in the android manifest of google mobile ads, where it says [APPLICATION_ID], change to "YOUR_APP_ID"
- Build and upload to google play. I get no pre-launch errors as well and it's working fine.

**Comment by cyberangel67** [comment] 2019-10-23 09:40
> Hey guys ! I managed to fix mine. However, mine was due to another plugin conflict.
> I have google mobile ads AND google play games. If you guys are having issues on implementing both, do this:
> 
> * erase folders of google play games and google mobile ads (along with playservices resolver and plugin)
> * import google play games v0.9.64 (everything)
> * import google mobile ads **VERSION 3.17** (THIS IS IMPORTANT. ONLY THIS VERSION WORKED FOR ME), WITHOUT playservices resolver.
> * Let the unity compile and then do **Force Resolve**
> * You should be able to setup google play games now
> * Change in the android manifest of google mobile ads, where it says [APPLICATION_ID], change to "YOUR_APP_ID" (should be something like "ca-app-pub..."  Get it in admob)
> * Build and upload to google play. I get no pre-launch errors as well and it's working fine.
> 
> Google mobile ads V3.17:
> https://github.com/googleads/googleads-mobile-unity/releases/tag/3.17.0

I think that is a different issue, I created a blank project with nothing but this plugin!!

**Comment by ozdemir08** [comment] 2019-10-23 17:27
Thanks everyone for reporting and commenting on this. We've looked into it and a fix has been merged to the unity-jar-resolver. You can check out the description in [the pr](https://github.com/googlesamples/unity-jar-resolver/pull/289), if you'd like to learn more about the issue.

unity-jar-resolver will make a new release soon and after that we will make one. I'm expecting both releases to be completed within 24 hours. 

If you want to work on this plugin in the meantime, you can still use v10.04 with v1.2.124(or before) of unity-jar-resolver. A way to do that is, importing only PlayServicesResolver from v9.64 package and importing only GooglePlayGames from v10.04.

**Comment by ozdemir08** [comment] 2019-10-24 13:14
We have released v10.05, it should be fixing this issue.

**Closed** 2019-10-24 13:16 UTC
Labels: bug

**Comment by adrianpanicek** [comment] 2019-11-08 16:53
I still have this issue on version 0.10.05

**Comment by olehkuznetsov** [comment] 2019-11-08 17:01
Should be fixed in 0.10.06, can you check it please?

**Comment by GuillaumZ** [comment] 2019-11-17 18:12
Hi, sadly, with Unity 2019.2.9f1 and 2019.2.12f1, after a clean install of google play unity package 10.06 (I erased first the Asset/PlayServicesResolver and the Assets/googleplaygames folders) , if i do "force resolve" in unity editor/assets/Playservicesresolver, I get that error :

```
Resolution failed
Failed to fetch the following dependencies:
com.google.games:gpgs-plugin-support:0.10.06
UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/Logger.cs:127)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:967)
GooglePlayServices.GradleResolver:LogMissingDependenciesError(List`1) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/GradleResolver.cs:95)
GooglePlayServices.<DoResolutionUnsafe>c__AnonStorey14:<>m__1F(List`1) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/GradleResolver.cs:812)
GooglePlayServices.<GradleResolution>c__AnonStoreyF:<>m__16() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/GradleResolver.cs:318)
GooglePlayServices.<GradleResolution>c__AnonStoreyF:<>m__18(Result) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/GradleResolver.cs:397)
GooglePlayServices.<GradleResolution>c__AnonStorey10:<>m__28() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/GradleResolver.cs:502)
Google.RunOnMainThread:ExecuteNext() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:377)
Google.RunOnMainThread:<ExecuteAll>m__A() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:408)
Google.RunOnMainThread:RunAction(Action) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:406)
Google.RunOnMainThread:Run(Action, Boolean) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:363)
GooglePlayServices.<GradleResolution>c__AnonStoreyF:<>m__27(Result) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/GradleResolver.cs:502)
GooglePlayServices.ProgressReporter:SignalComplete() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/CommandLineDialog.cs:116)
GooglePlayServices.ProgressReporter:CommandLineToolCompletion(Result) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/CommandLineDialog.cs:107)
GooglePlayServices.<RunAsync>c__AnonStorey1:<>m__4() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/CommandLine.cs:137)
Google.RunOnMainThread:ExecuteNext() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:377)
Google.RunOnMainThread:<ExecuteAll>m__A() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:408)
Google.RunOnMainThread:RunAction(Action) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:406)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions() (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:303)
```

**Comment by GuillaumZ** [comment] 2019-11-17 18:17
If I may be complete, first I have this error (see below), then the one i pasted in my previous post.

```
Gradle failed to fetch dependencies.

Failed to run 'C:\Users\XXXXXXXXXXXXXXXXXXXXX\Temp\PlayServicesResolverGradle\gradlew.bat --no-daemon -b "C:\Users\XXXXXXXXXXXXXXXXXXX\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle" "-PANDROID_HOME=C:/Program Files/Unity/Hub/Editor/2019.2.12f1/Editor/Data/PlaybackEngines/AndroidPlayer\SDK" "-PTARGET_DIR=C:\Users\XXXXXXXXXXXXXXXXXXX\Assets\Plugins\Android" "-PMAVEN_REPOS=file:///C:/Users/XXXXXXXXXXXXXXXXXXX/Assets/GooglePlayGames/Editor/m2repository" "-PPACKAGES_TO_COPY=com.google.games:gpgs-plugin-support:0.10.06" "-PUSE_JETIFIER=0" "-PDATA_BINDING_VERSION=3.4.0"'
stdout:

stderr:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/C:/Users/XXXXXXXXXXXXXXXXXXX/.gradle/wrapper/dists/gradle-5.1.1-bin/90y9l8txxfw1s2o6ctiqeruwn/gradle-5.1.1/lib/groovy-all-1.0-2.5.4.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

FAILURE: Build failed with an exception.

```

**Comment by GuillaumZ** [comment] 2019-11-17 18:26
Hooo it's working with the latest unity jar resolver Version 1.2.132 !  : https://github.com/googlesamples/unity-jar-resolver
I didn't try the force resolve though, but in unity editor/window/googleplaygames/setup/androidsetup, i did a setup and it worked !

**Comment by GuillaumZ** [comment] 2019-11-17 18:29
there it is, I also tried the "force resolve" and it worked too. Thanks for the good work guys !

**Comment by deltronofficial** [comment] 2020-02-15 07:55
> there it is, I also tried the "force resolve" and it worked too. Thanks for the good work guys !

Hi,
Can you help me?
I'm using AdMob for android [Unity-2019.3.0f3].
AND when I try to force resolve i get error: Resolution failed and Gradle failed to fetch dependencies.

**Comment by cyberangel67** [comment] 2020-02-15 08:40
> Can you help me?
> I'm using AdMob for android [Unity-2019.3.0f3].
> AND when I try to force resolve i get error: Resolution failed and Gradle failed to fetch dependencies.

You may wish to upgrade your version, the version you listed there was a Release Candiate and there was at least 3 more before the final release. Also Unity has now updated the version to Unity 2019.3.1f1 as well and if you are still getting this error message, then I would suggest double checking that the tools are installed and you have the internal tools selected.
