### ISSUE TITLE
How can I do server authentication with Google Play Services

### ISSUE THREAD

**Issue by jjduran121** [playgameservices/play-games-plugin-for-unity#222] opened 2014-09-12 16:00 UTC
I'm trying to implement server authentication through Google Play Services. I need to log in a client and pass a token to a server so our server can verify the user is who they say they are.  Currently I am able to get the user authenticated, but all I receive back is the full name and a userID.   

This plugin doesn't seem to respond with a session token.  How am I supposed to authenticate the user?   Ideally, I would like to receive a token that I can pass to our server, and have our server confirm the session is valid with Google.  Am I missing something?

**Comment by hex** [comment] 2015-01-06 08:53
Will there be any support for this in the next version?

**Comment by claywilkinson** [comment] 2015-01-23 22:22
Consolidating the issues, so closing this as a duplicate of #181

**Closed by claywilkinson** 2015-01-23 22:22 UTC
Labels: duplicate, enhancement

**Comment by cboxgo** [comment] 2015-02-18 18:05
Just curious, will this be added into an upcoming version of the unity plugin?  The plugin works great for Android and IOS, so it would be wonderful to be able to use the leaderboards, saved games, and achievements without having to rewrite my games for the Unity Web Player.  Thanks in advance for any information...

**Comment by rohitvishwakarma1819** [comment] 2022-03-19 18:24
whats the update anyone ?
