### ISSUE TITLE
Login Failed on Debug Log

### ISSUE THREAD

**Issue by rigby00** [playgameservices/play-games-plugin-for-unity#2447] opened 2019-02-09 12:51 UTC
Hi, 

I'm using Unity 2018.3.5 and Google Play Services 9.60 everything is normal. But when i start app to connect google play services it says "Login Failed". I checked everyting sha1 etc etc nothing solved my problem. Can you help please.

Thanks.

**Comment by kreesty** [comment] 2019-02-09 17:33
Same. I tried 9.60 and 9.53 and it happens with both.

**Comment by rigby00** [comment] 2019-02-09 18:06
> Same. I tried 9.60 and 9.53 and it happens with both.

**Yes but i didn't found any solution can you help us guys please. Thanks.**

**Comment by vaibhavgpt-google** [comment] 2024-10-09 06:57
The issue is not comprehensive enough. Closing the issue as of now, please re-open it, if you are still facing it.
Thanks

**Closed by vaibhavgpt-google** 2024-10-09 06:57 UTC
