### ISSUE TITLE
libGTMOAuth2_external.a does not contain bitcode error when building iOS

### ISSUE THREAD

**Issue by effxiikc** [playgameservices/play-games-plugin-for-unity#1989] opened 2017-10-22 05:16 UTC
I'm getting this error below when I'm trying to build an archive for iOS.

> ld: '/Users/kelvin/Documents/iPhone/Projects/Current/Git/Blaze Runners/Builds/iOS/BlazeRunners/Pods/GoogleAuthUtilities/Libraries/libGTMOAuth2_external.a(GTMOAuth2Authentication.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/kelvin/Documents/iPhone/Projects/Current/Git/Blaze Runners/Builds/iOS/BlazeRunners/Pods/GoogleAuthUtilities/Libraries/libGTMOAuth2_external.a' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Is this an error caused by Play Games Services? I've added NO_GPGS in the iOS build settings in Unity already. Anyone else get an error similar to this?

**Comment by claywilkinson** [comment] 2017-10-30 18:31
Can you take a #1994? with NO_GPGS there should not be any code added to the XCode project, but the dependency is still apparently being added.  If you remove the dependency it should build OK with NO_GPGS.  

I'm going to close this issue as a duplicate of #1994.  If you have follow up  comments/questions please add them there.

As a reminder, iOS support for GPGS is deprecated and will be removed soon: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html

**Closed by claywilkinson** 2017-10-30 18:31 UTC
