### ISSUE TITLE
Callback not called when savedGameClient.OpenWithAutomaticConflictResolution is invoked

### ISSUE THREAD

**Issue by kkondarev** [playgameservices/play-games-plugin-for-unity#1477] opened 2016-11-07 15:02 UTC
If actual conflict resolving is involved, the callback for game being opened is not called at all.
Scenario:
Turn device online -> start the game -> authentication successful -> save game is created -> some gameplay -> game is saved successfully -> exit game ->
Turn device offline -> start the game -> save game loaded successfully -> some gameplay -> game is saved successfully -> exit game ->
Turn device online -> start game -> save game attempts to load -> callback is not called at all, so game hangs

Narrowed it down to following:

The game always starts successfully when the device is offline, the save game is also opened, all good.
When the device is online, game loading is stuck on:

`
ISavedGameClient savedGameClient = PlayGamesPlatform.Instance.SavedGame; savedGameClient.OpenWithAutomaticConflictResolution(saveName, DataSource.ReadCacheOrNetwork, ConflictResolutionStrategy.UseLongestPlaytime, onSavedGameOpened);
`

-> onSavedGameOpened callback is not called at all - diesn't matter how many times I try
-> If another app receives focus for a sec and then I switch back to the game - the callback is called and the save game is opened
-> if the game is restarted with device offline, the callback is called and the save is opened every time

In log I have found the following, but am not sure what it means / how to fix it:

> 
10-26 22:38:48.854: W/GamesServiceBroker(6870): Client connected with SDK 8487000, Services 9877036, and Games 37240036
10-26 22:38:48.914: E/SnapshotEventService(6870): Error handling event: CompletionEvent [id=DriveId:CAESSDFfdWxkT2hXZ2o4bjFMQmpEeWwtMWlzWnlSNk9zQnY4OGRZWHRVNGtpMFVOb3dsaUlFR2VaSWJtb0xBbzBVOUwtMzVxeDJmaxjEBSCKyuvRxVEoAA==, status=2, trackingTag='info.dragonslabs.submarine<:>drive://g15862525828023294684/104358369895/DefaultGame<:>104358369895<:>6<:>https://www.googleapis.com/auth/games_lite<:>com.google']
10-26 22:38:48.914: E/SnapshotEventService(6870): java.lang.IllegalStateException: Attempting to underflow ref count for drive://g15862525828023294684/104358369895/DefaultGame
10-26 22:38:48.914: E/SnapshotEventService(6870): at com.google.android.gms.common.internal.Asserts.fail(Asserts.java:135)
10-26 22:38:48.914: E/SnapshotEventService(6870): at com.google.android.gms.games.broker.SnapshotAgent.decrementPendingChangeCount(SnapshotAgent.java:874)
10-26 22:38:48.914: E/SnapshotEventService(6870): at com.google.android.gms.games.service.PlaySnapshotEventService.onCompletionInner(PlaySnapshotEventService.java:107)
10-26 22:38:48.914: E/SnapshotEventService(6870): at com.google.android.gms.games.service.PlaySnapshotEventService.onCompletion(PlaySnapshotEventService.java:58)
10-26 22:38:48.914: E/SnapshotEventService(6870): at com.google.android.gms.chimera.DriveEventService.access$000(DriveEventService.java:70)
10-26 22:38:48.914: E/SnapshotEventService(6870): at com.google.android.gms.chimera.DriveEventService$EventHandler.handleMessage(DriveEventService.java:132)
10-26 22:38:48.914: E/SnapshotEventService(6870): at android.os.Handler.dispatchMessage(Handler.java:99)
10-26 22:38:48.914: E/SnapshotEventService(6870): at android.os.Looper.loop(Looper.java:176)
10-26 22:38:48.914: E/SnapshotEventService(6870): at com.google.android.gms.chimera.DriveEventService$1.run(DriveEventService.java:223)

Any suggestions how to proceed to fix or workaround this issue?

**Comment by kkondarev** [comment] 2016-11-15 07:35
Anyone? Please?

**Comment by claywilkinson** [comment] 2016-12-27 19:08
@kkondarev  - This looks like the same error as in #1450?  If so, is it OK to close this one as a duplicate?

**Comment by claywilkinson** [comment] 2017-01-03 20:50
Closing as a duplicate of #1450  - Please monitor that issue for resolution.

**Closed by claywilkinson** 2017-01-03 20:50 UTC
Labels: duplicate, SavedGames
