### ISSUE TITLE
Problem in cloud save internalerror

### ISSUE THREAD

**Issue by HuseyinKutlukkaya** [playgameservices/play-games-plugin-for-unity#2609] opened 2019-06-21 20:45 UTC
I can   login and open leaderboard but   cloud save and load  SavedGameRequestStatus returns internalerror in SaveGameOpened method

code:

 private void AuthenticateUser()
    {
        PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().EnableSavedGames().Build();
        PlayGamesPlatform.DebugLogEnabled = false;
        PlayGamesPlatform.InitializeInstance(config);
        PlayGamesPlatform.Activate();
      
    }
    public void Login()
    {
        Social.localUser.Authenticate((bool succes) =>
        {
            if (succes == true)
            {
               
                Debug.Log("succes\n");
            }
            else

            {
                Debug.Log("fail \n");
            }
        });
    }
    

 

    public void SaveToCloud()
    {
        OpenSave(true);
    }

    public void LoadFromCloud()
    {
        OpenSave(false);
    }
    #region Cloud Save
    void OpenSave(bool saving)
    {
        Debug.Log("Open Save");
        if (Social.localUser.authenticated)
        {
            issaving = saving;
            ((PlayGamesPlatform)Social.Active).SavedGame.OpenWithAutomaticConflictResolution(
                saveName,DataSource.ReadCacheOrNetwork,ConflictResolutionStrategy.UseLongestPlaytime,SaveGameOpened
                );
        }
    }

    private void SaveGameOpened(SavedGameRequestStatus status, ISavedGameMetadata meta)
    {
        Debug.Log("SaveGameOpened");
        if (status==SavedGameRequestStatus.Success)
        {
            if (issaving)//write
            {
                byte[] data = System.Text.ASCIIEncoding.ASCII.GetBytes("test data");
                SavedGameMetadataUpdate update = new SavedGameMetadataUpdate.Builder()
                    .WithUpdatedDescription("saved at" + DateTime.Now.ToString()).Build();
                ((PlayGamesPlatform)Social.Active).SavedGame.CommitUpdate(meta,update,data,SaveUpdate);
            }
            else// read
            {
                
                ((PlayGamesPlatform)Social.Active).SavedGame.ReadBinaryData(meta, SaveRead);
            }
        }
        else
        {
            Debug.Log("SaveGameOpened Error Status = " + status);
        }

       
    }

    private void SaveRead(SavedGameRequestStatus status, byte[] data)
    {
        if (status == SavedGameRequestStatus.Success)
        {
            string saveData = System.Text.ASCIIEncoding.ASCII.GetString(data);
            Debug.Log("Data="+ saveData);
        }
    }

    private void SaveUpdate(SavedGameRequestStatus status, ISavedGameMetadata meta)
    {
        Debug.Log("SaveUpdate Status="+status);

       
    }

    #endregion

**Comment by olehkuznetsov** [comment] 2020-01-09 11:58
Should be fixed in v0.10.06. Feel free to reopen if it reproduces there.

**Closed by olehkuznetsov** 2020-01-09 11:58 UTC
Labels: SavedGames, bug

**Comment by TheOneVries** [comment] 2020-05-03 18:17
Perhaps open it again? I have the same issue with v0.10.06. I use the exact same steps, but when testing on SavedGameRequestStatus.Success I always get an internal error. Is this because I am trying to save to a file that does not yet exist? (From what I've seen, there is no need to implement the ISavedGameMetadata to a custom class, right? Yet it is always null when trying to save a fresh file this way)

**Comment by SunQdev** [comment] 2021-08-22 23:22
I have exactly the same problem. I've been fighting her for about a week. The code is about the same. Goes to the leaderboard. But if I click "save" or "load", then I seem to exit the services and the button with the leaderboard no longer works. The leaderboard only works again after restarting the scene. Sorry for my english
