### ISSUE TITLE
Stopped polling job due to exception: System.UnauthorizedAccessException: Access to the path is denied.

### ISSUE THREAD

**Issue by bajwasab** [playgameservices/play-games-plugin-for-unity#2417] opened 2019-01-18 23:41 UTC
unable to import google play services plugin  GooglePlayGamesPlugin-0.9.58
Stopped polling job due to exception: System.UnauthorizedAccessException: Access to the path is denied.
  at System.IO.Directory.Move (System.String sourceDirName, System.String destDirName) [0x000f8] in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/Directory.cs:403 
  at GooglePlayServices.DefaultResolver.ProcessAar (System.String dir, System.String aarFile, Boolean antProject, GooglePlayServices.AndroidAbis& abis) [0x002be] in /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/DefaultResolver.cs:395 
  at GooglePlayServices.ResolverVer1_1+<ProcessAars>c__AnonStorey1F.<>m__35 () [0x000c7] in /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:1374 
  at Google.RunOnMainThread.ExecutePollingJobs () [0x0004a] in /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:286 
UnityEngine.Debug:LogError(Object)
Google.RunOnMainThread:ExecutePollingJobs() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:289)
Google.RunOnMainThread:<ExecuteAll>m__6() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:400)
Google.RunOnMainThread:RunAction(Action) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:392)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by olehkuznetsov** [comment] 2019-01-22 17:13
can you try to add the plugin to a new project, please?

**Comment by ThePumpel** [comment] 2019-01-23 22:49
same here, got the same issue after importing the Firebase.Analytics package, right when the resolver is doing its job until that same point
> 
> Also the processing AARs... dialog stuck and i have to close unity.
> 
> ![capture](https://user-images.githubusercontent.com/21969875/51632297-32253280-1f64-11e9-81cc-b1373663d5f1.JPG)

**Comment by olehkuznetsov** [comment] 2019-01-24 11:16
Can you try first to manually delete GoogelPlayGames folder from Assets folder in Unity Editor, please?

**Comment by ojodumehku** [comment] 2019-01-24 14:50
I have kind of same problem,
i use unity 5.5.0 f3. when i make a new project the problem still there.
what sould i do?
i stuck almost 2 weeks

**Comment by olehkuznetsov** [comment] 2019-01-24 17:02
It seems you need to manually remove GooglePlayGames from Assets folder before installing new plugin.

**Comment by ThePumpel** [comment] 2019-01-25 09:38
For me it fixed the issue when I switched from Internal to Gradle in Build Settings.

**Comment by ojodumehku** [comment] 2019-01-25 11:08
> It seems you need to manually remove GooglePlayGames from Assets folder before installing new plugin.

do you mean remove in unity application or in file folder on  "mycomputer"?

**Comment by ojodumehku** [comment] 2019-01-25 11:10
> For me it fixed the issue when I switched from Internal to Gradle in Build Settings.

can you desc the step?

**Comment by olehkuznetsov** [comment] 2019-01-25 11:10
Should be enough to remove it in Unity Application.

**Comment by ojodumehku** [comment] 2019-01-25 11:12
> Should be enough to remove it in Unity Application.


I've done it often but the error still appears.

i used unity 5.5.0f3.
what your unity version?

**Comment by ojodumehku** [comment] 2019-01-25 11:32
![image](https://user-images.githubusercontent.com/47001454/51743507-6406d800-20cf-11e9-82be-930c333c6aa1.png)
![was](https://user-images.githubusercontent.com/47001454/51743529-7ed94c80-20cf-11e9-84fb-0f3513a01115.PNG)

**Comment by olehkuznetsov** [comment] 2019-01-25 11:50
Can you try to create folder Assets/Plugins/Android manually in file explorer, please?

**Comment by ojodumehku** [comment] 2019-01-25 12:04
> Can you try to create folder Assets/Plugins/Android manually in file explorer, please?

bro...do you mean in my unity software? 
![image](https://user-images.githubusercontent.com/47001454/51744938-f90bd000-20d3-11e9-809c-b7127ce2179e.png)

**Comment by ojodumehku** [comment] 2019-01-25 12:05
or i must make the folder "Assets/Plugins/Android" before import "GooglePlayGamesPlugin-0.9.58" package?

**Comment by ojodumehku** [comment] 2019-01-25 12:43
I have done what you said  @olehkuznetsov but the the error still appears

**Comment by ojodumehku** [comment] 2019-01-25 13:18
this error make me  so frustarated

**Comment by ojodumehku** [comment] 2019-01-25 13:21
i am use sdk r25  and jdk 8_202 with unity 5.5.0 f3.
should i downgrade that? @olehkuznetsov

**Comment by BehzadBakhti** [comment] 2019-01-25 17:55
> It seems you need to manually remove GooglePlayGames from Assets folder before installing new plugin.

I don't have GooglePlayGames before adding this plug in!

**Comment by TwistedWebbe** [comment] 2019-01-26 06:42
I am also having this problem. Using Unity 2018.2.14f1. I purchased the asset today because it said it was supposed to be easy in all of the recent reviews. Importing this into the project that I need it in has failed every time, but blank new projects work. Help would be appreciated. I have tried removing the folder mentioned above, and disabling my security software. This is the error as it is displayed:
`Stopped polling job due to exception: System.UnauthorizedAccessException: Access to the path is denied.
  at System.IO.Directory.Move (System.String sourceDirName, System.String destDirName) [0x000f8] in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/Directory.cs:403 
  at GooglePlayServices.DefaultResolver.ProcessAar (System.String dir, System.String aarFile, Boolean antProject, GooglePlayServices.AndroidAbis& abis) [0x002be] in /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/DefaultResolver.cs:395 
  at GooglePlayServices.ResolverVer1_1+<ProcessAars>c__AnonStorey1F.<>m__35 () [0x000c7] in /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:1374 
  at Google.RunOnMainThread.ExecutePollingJobs () [0x0004a] in /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:286 
UnityEngine.Debug:LogError(Object)
Google.RunOnMainThread:ExecutePollingJobs() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:289)
Google.RunOnMainThread:<ExecuteAll>m__6() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:400)
Google.RunOnMainThread:RunAction(Action) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:392)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
`

**Comment by wagner32** [comment] 2019-01-27 12:37
> > can use describe step by step setting "gradle" because i dont know about that, please
> > I simply changed the Build Mode from Internal to Gradle. The package imports correctly, but I would rather not have to use Gradle to build my apk files.


the problem is getting more complicated.. can u help me @TwistedWebbe @olehkuznetsov 
![image](https://user-images.githubusercontent.com/47056856/51801003-b6303080-226a-11e9-9911-450e1dffa3c4.png)
![image](https://user-images.githubusercontent.com/47056856/51801024-e972bf80-226a-11e9-9bab-e44ffdcc5689.png)

**Comment by wagner32** [comment] 2019-01-27 12:38
![image](https://user-images.githubusercontent.com/47056856/51801040-18893100-226b-11e9-8755-c0dc85b93ab5.png)

**Comment by wagner32** [comment] 2019-01-27 17:55
@bajwasab i know the solusion just make "JAVA_HOME"
like this

![image](https://user-images.githubusercontent.com/47056856/51804757-5f8d1b80-2297-11e9-90b8-e09ace2c17af.png)

**Comment by wagner32** [comment] 2019-01-28 16:09
what error sho in your game?

**Comment by xxluky** [comment] 2019-01-30 07:37
Same problem here. Yesterday I upgraded to Unity 2018.3.3f1. I saw some warnings in my console about www obsolote problem so today I decided to upgrade Google Play Games Plugin where this is solved in the new version. I did the installation of the plugin as usual:
- Start Unity from Command Line
- Delete folder Play Services Resolver
- Delete folder Google Play Games
- Restart Unity
- Import the new Plugin

Everything imports great but the error shows when trying to resolve. Then it stucks.
I tried to set JAVA_HOME and JDK_HOME but no luck.

**Comment by xxluky** [comment] 2019-01-30 09:07
Here is my problem:
Stopped polling job due to exception: System.UnauthorizedAccessException: Access to the path is denied.
  at System.IO.Directory.Move (System.String sourceDirName, System.String destDirName) [0x000f8] in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/Directory.cs:403 
  at GooglePlayServices.DefaultResolver.ProcessAar (System.String dir, System.String aarFile, Boolean antProject, GooglePlayServices.AndroidAbis& abis) [0x002be] in /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/DefaultResolver.cs:395 
  at GooglePlayServices.ResolverVer1_1+<ProcessAars>c__AnonStorey1F.<>m__35 () [0x000c7] in /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/ResolverVer1_1.cs:1374 
  at Google.RunOnMainThread.ExecutePollingJobs () [0x0004a] in /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:286 
UnityEngine.Debug:LogError(Object)
Google.RunOnMainThread:ExecutePollingJobs() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:289)
Google.RunOnMainThread:<ExecuteAll>m__6() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:400)
Google.RunOnMainThread:RunAction(Action) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:392)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by xxluky** [comment] 2019-01-31 06:53
> Seems related to this [googlesamples/unity-jar-resolver@f8ba790](https://github.com/googlesamples/unity-jar-resolver/commit/f8ba790ef8d19b3df8834ddb21dcb1ca457c2b63)
> Will prepare the new version with fixed resolver today.

Working like a charm! Great job. Thanks a lot.

**Comment by olehkuznetsov** [comment] 2019-01-31 11:16
> Working like a charm! Great job. Thanks a lot.
Thanks for the confirmation it was fixed in v0.9.59.

**Closed by olehkuznetsov** 2019-01-31 11:16 UTC
Labels: bug

**Comment by pengzhuo1989** [comment] 2019-02-16 16:44
I change the building settings  internal to grade , and restart unity project   ,then fix this problem

**Comment by ExocetYu** [comment] 2019-02-16 16:46
I change the building settings internal to grade , and restart unity project ,then fix this problem

**Comment by BoishakhiStudios** [comment] 2019-09-28 05:29
hey bros go to asset in yop menu.then goto play service > androis > delete resolved libreies.then force resolve.

**Comment by BoishakhiStudios** [comment] 2019-09-28 05:29
hey bros go to asset in yop menu.then goto play service > androis > delete resolved libreies.then force resolve.

**Comment by BoishakhiStudios** [comment] 2019-09-28 05:29
hey bros go to asset in yop menu.then goto play service > androis > delete resolved libreies.then force resolve.

**Comment by BoishakhiStudios** [comment] 2019-09-28 05:29
hey bros go to asset in yop menu.then goto play service > androis > delete resolved libreies.then force resolve.

**Comment by BoishakhiStudios** [comment] 2019-09-28 05:29
hey bros go to asset in yop menu.then goto play service > androis > delete resolved libreies.then force resolve.

**Comment by chaifix** [comment] 2019-12-19 02:56
I got the same issue. Maybe update unity-jar-resolver to newer version could help.
