### ISSUE TITLE
Android - run in background

### ISSUE THREAD

**Issue by AndroidPICO** [playgameservices/play-games-plugin-for-unity#1166] opened 2016-05-20 17:09 UTC
How to make this plugin run in background when app is minimized?

**Comment by ArmandCloud** [comment] 2016-06-05 10:16
What feature you want to run in background.

Regards,

**Comment by AndroidPICO** [comment] 2016-06-15 10:33
Realtime Multiplayer - when app is paused ( minimize, click ad, call) it automatically disconnects (leave room).

**Comment by claywilkinson** [comment] 2016-06-16 20:59
This is because the unity game engine is paused when the activity is paused.  There is not an easy way to work around this.  Why do you want to have a player in a realtime game not be playing?  It seems reasonable to have that player leave the game when they leave the app?

**Comment by LinkC0re** [comment] 2016-08-09 01:32
I really want to find out , too, actually. When someone calls,  the person disconnects from the room. It will be really distrurbing for the users. Did anyone found a solution?

**Comment by claywilkinson** [comment] 2016-08-09 17:56
I don't believe there is a work around at this time.  It is the behavior of the underlying communications library within the Game Services SDK that when the activity is paused, the connection is closed.  I have passed it along as an enhancement to change the behaviour.  

I can see their thinking in the case of  a fast paced game, for example a car racing, when the activity pauses you can't see the road, and will crash anyway.  But if the game play is slower, or you can effectively pause the game play, it should not disconnect.

Thanks again for the feedback.

**Comment by LinkC0re** [comment] 2016-08-17 13:48
Thank you claywilkinson. I am currently developing a realtime card game so it will be nice not to disconnect if someone calls.

**Comment by lijuicsoft** [comment] 2016-09-03 11:40
How to reconnect to a room in Google real time muliplayer with Unity3D ?

**I create a quick game multiplayer connection**

    const int MinOpponents = 1, MaxOpponents = 1;
    const int GameVariant = 0;
    PlayGamesPlatform.Instance.RealTime.CreateQuickGame(MinOpponents,MaxOpponent,GameVariant,listener);

**and Create With Invitation Screen**

     PlayGamesPlatform.Instance.RealTime.CreateWithInvitationScreen(
     minimumOpponents,maximumOpponents,gameVariation, listener);
Connected to a room with one opponent

 **I dissabled my Ethernet connection of one device**

    Control Panel > All Control Panel Items > Network and Sharing Center > Change Adapter Settings > Ethernet >Disable this network device

**I Enabled my Ethernet connection by**

    Control Panel > All Control Panel Items > Network and Sharing Center > Change Adapter Settings > Ethernet >Enable this network device

   

**In my game each player's data is sending to each other .** 

    PlayGamesPlatform.Instance.RealTime.SendMessageToAll (true, messageToSend);

**Before Ethernet disconnect it works perfect** . After ethernet reconnection data is not getting to each other , but if one device left the room , following event will call.

    public void OnPeersDisconnected (string[] participantIds)
      {
          foreach (string participantID in participantIds) {
              ShowMPStatus ("Player " + participantID + " has left.");
              if (updateListener != null) {
                  updateListener.PlayerLeftRoom (participantID);
              }
          }
      }

**How to detect , player disconnected from net and how to reconnect to same room properly**

**Comment by valdowb** [comment] 2017-09-24 18:35
this is ridicoulous I have game with banner underneath when somebody click the banner will get disconnected from my multiplayer people will be discouraged to click on banner whole idea is that i am making game for get some money   is there any way to fix it??????

**Comment by bbekec** [comment] 2019-04-26 13:29
Same to me. This is the biggest problem for me. 
I m also developing a card game. In a game room there is 13 episodes. Players play each episode approximately 15 -20 minutes. 
I designed the game that if there is no response from user in a time period, system sends data and game goes on. Although system is ok, If one changes screen, whole game and player disconnects. 
As result, they are removing app from their device.

**Comment by DataGreed** [comment] 2019-07-03 14:06
I experience the same issue. This behaviour is vary annoying for the players.

There is a native java solution, mentioned [here](https://stackoverflow.com/questions/18678211/google-play-game-services-how-to-not-leave-room-onpause/19200280#19200280): 
> I have edited BaseGameActivity.onStop() and have removed gamehelper.onStop(). So I stop gamesclient only in onDestroy. My game work perfectly also in background now.

And [referenced here](https://stackoverflow.com/questions/44518833/real-time-multiplayer-google-play-games-services-peer-gets-disconnected-when-app) by another person who succeed in implementing it:
> Though, you may also opt to try this suggested solution. Try editing BaseGameActivity.onStop() and remove gamehelper.onStop(). With this, gamesclient will only stopped in onDestroy. It might be a good option but I haven't actually tried it

> moving gameHelper.onStop to on destroy worked for me

That means the problem is definitely solvable. 
I could try submitting a PR, but I am not good with java and I cannot find any mention of onStop or onPause methods in the `play-games-plugin-for-unity` repo. 

Is there anyone here who could actually suggest where to start?

**Comment by DataGreed** [comment] 2019-07-03 14:13
@claywilkinson could you please tell me what methods the guys in the quotation above reference? is it something from the library this repo uses as underlying communication library you were refferring to? Where can I find this library to take a look at it and possibly alter the behaviour?

Could you please suggest where to start?

**Comment by DataGreed** [comment] 2019-07-03 14:18
it seems to me that fixing this issue is about commenting out this line in the library from `NativeRealtimeMultiplayerClient .HandleAppPausing`:

https://github.com/playgameservices/play-games-plugin-for-unity/blob/13933e7e1f4fc764d069cc975e200410afecee29/source/PluginDev/Assets/GooglePlayGames/Platforms/Native/NativeRealtimeMultiplayerClient.cs#L125

Could someone please clarify if that would solve the problem?

**Comment by DataGreed** [comment] 2019-07-03 15:10
I'v created a pull-request (`.unitypackage` not updated, only source code) - I would appreciate if someone could check it and tell me if it works.

**Comment by DataGreed** [comment] 2019-07-05 22:09
Okay, I'e tried it myself and it seems that the code I've removed does not actually do anything since the behavior stayed the same. Weird

**Comment by ozdemir08** [comment] 2020-02-27 11:57
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.

**Closed by ozdemir08** 2020-02-27 11:57 UTC
Labels: Enhancement
