### ISSUE TITLE
Firebase : Can’t disable Google Play Games on IOS

### ISSUE THREAD

**Issue by RedYggdrasil** [playgameservices/play-games-plugin-for-unity#1992] opened 2017-10-24 16:04 UTC
Hello,

I got a problem with Google play games on IOS, when I use the NO_GPGS tag in Unity And I Build the project to get my Xcode project google play games, Google play games  is still imported and cause an error forcing me to enable bitcode.

I’m pretty confident than the presence of firebase plugin on the project is the cause of the issue.

Also, has someone succeed in getting the both of them working together nicely ?

Thanks.
<img width="1410" alt="screenshot 2017-10-24 17 48 34" src="https://user-images.githubusercontent.com/15359127/31954394-bdbd1d4e-b8e5-11e7-86d3-461f46bdfcdc.png">

<img width="252" alt="screenshot 2017-10-24 17 48 48" src="https://user-images.githubusercontent.com/15359127/31954353-a6c950c6-b8e5-11e7-9efb-ca1fd1d2f720.png">

**Comment by claywilkinson** [comment] 2017-10-30 18:27
Take a look at https://github.com/playgameservices/play-games-plugin-for-unity/issues/1994 - I think the problem is even with NO_GPGS, the XML file containing the dependencies for GPGS has iOS configured.  If you remove that, it should work. 

I'm going to close this one as a dupe - if you have more follow please update #1994.

**Closed by claywilkinson** 2017-10-30 18:27 UTC

**Comment by pearl90** [comment] 2017-11-23 12:45
I have a question so if i used the NO_GPGS , and removed the dependencies from xml ..will firebase work fine on iOS? i want to use firebase on iOS but i don't want GPGS useless files in the iOS build because its throwing me an error.
