### ISSUE TITLE
Ability to build on iOS without having to remove play service every time

### ISSUE THREAD

**Issue by sambauwens** [playgameservices/play-games-plugin-for-unity#395] opened 2015-02-05 19:57 UTC
I use play games services on android for some time. But I use GameCenter on iOS, I prefer to use the native game Social API on each platform (plus I prefer the GameCenter way which provides a "Gaming acccount", over google play game services way that works with the google plus account whose playername is the real person's name that can't be changed, which is a problem for many users on android, but I digress).

The problem is that I can't build for iOS without doing the "Setup for iOS" integration, it gives me build errors. I'd like to just be able to have Game Services for Android, and not for iOS (which is the use case for most people I'm sure).

So each time I want to build for iOS I have to remove all game services files and it's not the nicest thing. So I thought ok I'll integrate game services for iOS without using it, just to avoid having to remove these files each time I want to build/test a version on iOS, but doing that asked to enable push services on game start, which is another problem on itself. So I'm left with having to disable play games services all the time.

It would be very nice to be able to use Play Game Services on Android and still be able to build the project on iOS even though I'm not using Play Game Services on this platform.

**Comment by samtstern** [comment] 2015-02-06 20:39
Closing as duplicate of #276

**Closed by samtstern** 2015-02-06 20:39 UTC
