### ISSUE TITLE
Rejection by Apple Because of Google Sign in Process

### ISSUE THREAD

**Issue by simsis3d** [playgameservices/play-games-plugin-for-unity#580] opened 2015-06-20 13:08 UTC
As I read here(http://stackoverflow.com/questions/15281386/google-iphone-api-sign-in-and-share-without-leaving-app/24577040#24577040) A google guy says that

"Use the (new) Google Sign in iOS SDK. The SDK natively supports Sign In through WebView when no Google app is present to complete the Sign In process."

@claywilkinson can you please say that when this new Sign in SDK will be available for us? If it will take long time(more than two weeks) can you write a workaround for UIWebView for us in order to use it untill new plugin version available. Thanks.

**Comment by MofoMan2000** [comment] 2015-06-21 23:51
Duplicate of #148 but this is good information to know.

**Comment by claywilkinson** [comment] 2015-09-12 02:12
Version 0.9.25 uses Google SignIn SDK which is acceptable to Apple.

**Closed by claywilkinson** 2015-09-12 02:12 UTC
