### ISSUE TITLE
Google Play Game Services App Crashes after successful authentication in Unity android

### ISSUE THREAD

**Issue by AdnanNazir** [playgameservices/play-games-plugin-for-unity#847] opened 2015-12-07 08:17 UTC
I am making a multiplayer Unity3D Game.
I am using play game services plugin from Google given the link below
https://github.com/playgameservices/play-games-plugin-for-unity
I am in a strange trouble, so far I am testing and running the minimal Sample that ships with the free Google Play Game Services for Unity. In this sample there is only a simple button that authenticate user with GPGS. Upon pressing the button in my minimal example that I have taken from the Plugin the app does authenticate myself and my picture also displays as texture below button but then the app crashed and below I copied log that I get when app crashes. 

12-07 13:08:48.924 23694-23694/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.gs.toughashell, PID: 23694
                                                   java.lang.Error: FATAL EXCEPTION [main]
                                                   Unity version     : 5.2.2f1
                                                   Device model      : LGE LG-F240L
                                                   Device fingerprint: lge/omega_lgu_kr/omega:5.0.2/LRX22G/1506717071d79:user/release-keys

I am also confused in one think. For iOS while testing IAP and other stuff our app doesn’t need necessarily appear in the iTunes Connect for testing. Is there is the same case with google?
I mean for testing purposes do I need to upload my apk to the alpha/beta testing mode in the apk section of google play developer console? Or I can test it without uploading just as in iOS??

**Comment by claywilkinson** [comment] 2015-12-07 16:37
Can you post more of the log related to crash?

You should be able to test Android applications without uploading them.

**Comment by claywilkinson** [comment] 2016-01-04 17:02
ok to close?

**Comment by bricevdm** [comment] 2016-01-08 17:54
Hi Clay,

I take the liberty to hijack this thread as I ran into the exact same issue.
I'm also trying to run the minimal sample on Unity Android, and it crashes just after login in successfully (I can see the avatar flashing for a split second). I'm not familiar with debugging on device (and I am not a developer by trade so bear with me).

I assume you are asking for information I should find in adb.exe logcat. Here's what I think is relevant (there is a lot of stuff in there and I'm not sure how to filter them properly).

E/AndroidRuntime(13492): Process: com.<MY DOMAIN>.<MY APP>, PID: 13492
E/AndroidRuntime(13492): java.lang.Error: FATAL EXCEPTION [main]
E/AndroidRuntime(13492): Unity version     : 5.3.1f1
E/AndroidRuntime(13492): Device model      : samsung SM-T530
E/AndroidRuntime(13492): Device fingerprint: samsung/matissewifixx/matissewifi:5.0.2/LRX22G/T530XXU1BOG2:user/release-keys
E/AndroidRuntime(13492): 
E/AndroidRuntime(13492): Caused by: java.lang.NoSuchMethodError: No virtual method shouldShowRequestPermissionRationale(Ljava/lang/String;)Z in class Lcom/google/games/bridge/TokenFragment; or its super classes (declaration of 'com.google.games.bridge.TokenFragment' appears in /data/app/com.com.<MY DOMAIN>.<MY APP>-1/base.apk)

Feel free to ask if I can provide better information. I have the same crash on 2 devices using 2 different test user accounts. I think I have properly set up my project but I might be wrong (1 "Welcome" achievement & "Minimal.GPGSIds")

Best regards

**Comment by johnnydeath** [comment] 2016-01-10 04:20
I am having the exact same crash with 0.9.27.  I rolled back to 0.9.26 to work around the issue.

**Comment by benkaranja** [comment] 2016-01-10 10:04
Hi Clay. 

Am having the same issue 
"Game crashes just after login in successfully (I can see the avatar flashing for a split second)"
But my unity version is 4.7.0f1.
I'll try and test the issue on 5.3.1 and revert

Regards

**Comment by claywilkinson** [comment] 2016-01-11 16:39
What version of Android are you running?  The error might be some non-backward compatible code got into the plugin.  `shouldShowRequestPermissionRationale` is a "M" API.  If that is so, let me update the plugin...

**Comment by bricevdm** [comment] 2016-01-11 17:30
the tablet I got the log from uses android 5.0.2 and my phone uses android 4.4.4

**Comment by bricevdm** [comment] 2016-01-12 00:07
I reverted back to 0.9.26 as johnnydeath suggested and it worked :+1: thanks a lot !
I only had to replace the plugin folder and keep the other changes from 0.9.27a and it is working so far for log in/out and leaderboards.

**Comment by hijuh125830** [comment] 2016-01-14 15:48
hello bricevdm
can you send me 0.9.26. i haveing the same issue. Please help me.

**Comment by hijuh125830** [comment] 2016-01-14 15:49
my email is hijuh125830@gmail.com

**Comment by johnrossporter** [comment] 2016-01-14 19:19
I had this exact same error and was able to fix it by removing calls to GooglePlayGames.PlayGamesPlatform.Instance.GetToken() which appears in the Minimal sample project.

**Comment by bricevdm** [comment] 2016-01-15 13:56
you can find the package by looking into the HIstory of the current-build folder https://github.com/playgameservices/play-games-plugin-for-unity/blob/00624a5c2c66a3b6175f14aebea4fa6ccd8758a3/current-build/GooglePlayGamesPlugin-0.9.26.unitypackage?raw=true

**Comment by hijuh125830** [comment] 2016-01-15 15:31
hello friend, thank you very much. i completed google leaderboard using GooglePlayGamesPlugin-0.9.27a.unitypackage.
But i have one more problem.
Can you help for Share in Unity3d (android, iphone) like facebook, twitter, message(text)...
i need to sample source or package. Really, i can pay for this because this is very important for me.
Please help me. thank you.

Sent from Mailbird [http://www.getmailbird.com/?utm_source=Mailbird&amp;utm_medium=email&amp;utm_campaign=sent-from-mailbird]
On 2016-01-15 오후 9:56:29, Brice <notifications@github.com> wrote:
you can find the package by looking into the HIstory of the current-build folder https://github.com/playgameservices/play-games-plugin-for-unity/blob/00624a5c2c66a3b6175f14aebea4fa6ccd8758a3/current-build/GooglePlayGamesPlugin-0.9.26.unitypackage?raw=true [https://github.com/playgameservices/play-games-plugin-for-unity/blob/00624a5c2c66a3b6175f14aebea4fa6ccd8758a3/current-build/GooglePlayGamesPlugin-0.9.26.unitypackage?raw=true]

**Comment by benkaranja** [comment] 2016-01-21 19:06
Hey Clay,
I can confirm GooglePlayGamesPlugin-0.9.26 works like a miracle. on unity 4.8 and 5.3.1.
0.9.27a crashes on both. I will share the log files.
Thanks

**Comment by claywilkinson** [comment] 2016-01-21 19:29
Thanks! I am working on an update - so this is perfect timing!

**Comment by claywilkinson** [comment] 2016-01-27 20:19
This is fixed in the 0.9.30 version of the plugin.  Please open a new issue if there is still a problem.  Thanks!

**Closed by claywilkinson** 2016-01-27 20:19 UTC

**Comment by keni4** [comment] 2016-12-04 23:19
Hi, it still exist on 0.9.35 + Unity 5.4.1.p4. Some devices crahes on Login (may be successfull), or Play Games Activation. Some devices crashes on fething leaderboards.
Btw, at one day my leaderboard score fetching stop working. Fetch only old results, no updates to leaderboard, but Aproxymetely scores seems to look fine. After hours of pain my solution was use internal PlayGamesPlatform.Instance.LoadScores with all leadboard parameters. Wired...

**Comment by dreamwagon** [comment] 2017-01-24 18:41
I am experiencing a crash every time I attempt to show leaderboards on iOS. I see the leaderboard for a moment, then the app crashes. Possibly the same issue? Everything works great on android for me
