### ISSUE TITLE
Unable to convert classes into dex.

### ISSUE THREAD

**Issue by loftyy** [playgameservices/play-games-plugin-for-unity#872] opened 2015-12-20 22:03 UTC
good evening gents,

I've been having this error and tried solving it with the help of similar resolved issues but they didn't work, please help me

It's been 2 days and i still can't fix it and it has halted my progress. The facebook SDK worked completely fine but when I imported playgames plug-in the game is not building anymore but I can play it on Unity Remote 4.

Here are the screenshots (to make things easier to see) and errors:
note: I have added texts to the screenshot which I think will help so please read them :-)

Screenshot : http://content.screencast.com/users/Loftyy/folders/Jing/media/f1a249d8-9b14-4e71-a701-35edc740a93a/2015-12-21_0022.png

First error: http://pastebin.com/h8pjLkE9
Second error: http://pastebin.com/4rudv7cE

Screenshot : http://content.screencast.com/users/Loftyy/folders/Jing/media/850b2a0d-a2d4-4cba-82d5-9c6a7a9841eb/2015-12-21_0024.png

Screenshot : http://content.screencast.com/users/Loftyy/folders/Jing/media/2ccd7d4d-01c2-43ed-9773-44dda667d4c6/2015-12-21_0025.png

Screenshot : http://content.screencast.com/users/Loftyy/folders/Jing/media/6727ff2f-d5d7-4c03-886b-798d9a8d3607/2015-12-21_0027.png

Screenshot : http://content.screencast.com/users/Loftyy/folders/Jing/media/f92cda78-d1f9-43f7-b748-f38fb9d99716/2015-12-21_0026.png

Screenshot : http://content.screencast.com/users/Loftyy/folders/Jing/media/9b5a8034-769c-4fda-ab22-2176c620d020/2015-12-21_0032.png

Screenshot : http://content.screencast.com/users/Loftyy/folders/Jing/media/3e0d0803-857e-4095-b599-c953fa4e12a0/2015-12-21_0033.png

Video (notice how the files deleted get recreated once the build begins): http://screencast.com/t/e15V2Xy6

**Comment by pedro15** [comment] 2015-12-20 22:55
1) Verify that you have the android sdk updated.
2) be sure that you don't have duplicated .jar / AAR plugins files.

**Comment by loftyy** [comment] 2015-12-20 23:54
@pedro15 
- updated my sdk to the lattest, didn't work.
- I tried deleting some files which I thought were causing this issue as show here (http://screencast.com/t/e15V2Xy6) but as I said, these files get recreated as soon as I build the game. 
I have included some pictures, could you direct me as to which jar/aar file is causing this please?

thank you sir

**Comment by SDowd-FD** [comment] 2015-12-21 22:09
The problem is when everyone makes a package for unity they operate under the assumption that you don't have any of the pre-reqs.  You will run into this issue for any plugin that happens to include jar files/classes that they think you need, and you happen to already have.  

This particular plugin contains a post-process that will re-include or update any of the files it finds as missing or out of date, which is why the FacebookSDK doesn't regenerate the files you (may have) expected it to.

**Comment by loftyy** [comment] 2015-12-22 12:17
@SDowd-FD you are right, that is what I was thinking but I didn' t know which files were duplicated. Everything is working now =)

**Comment by loftyy** [comment] 2015-12-22 12:18
@SDowd-FD you are right, that is what I was thinking but I didn' t know which files were duplicated. Everything is working now =)

**Comment by claywilkinson** [comment] 2015-12-22 19:10
@loftyy and others - thanks for the feedback.  We're working on figuring out a way to make it both automatic (so the required client jars are not missing) and be compatible with all the various plugins out there.

OK to close this issue?

**Comment by loftyy** [comment] 2015-12-22 23:40
@claywilkinson  no problemo boss, I just have 1 simple question. When I want to unlock an achievement,  should I load Social.LoadAchievements beforehand? Because I have used the code which you used for unlock normal achievements after signing-ing and Activating google play services. Thanks =) Have a good day.

**Comment by claywilkinson** [comment] 2016-01-04 17:10
Great news! thanks for the update.

**Closed by claywilkinson** 2016-01-04 17:10 UTC
