### ISSUE TITLE
No Welcome Back UI on every app start on Authenticate

### ISSUE THREAD

**Issue by pa3kc** [playgameservices/play-games-plugin-for-unity#743] opened 2015-10-08 09:07 UTC
No Welcome Back UI on every app start on Authenticate

**Comment by banditdevelopment** [comment] 2015-10-08 15:00
Yep, it is the same for me on iOS and Android. Not sure if it is intentional or not, @claywilkinson can probably clarify.

**Comment by teemukorh** [comment] 2015-10-09 11:49
Same here on Android

**Comment by jimmy-black** [comment] 2015-10-13 08:44
I'm having the same issue on android as well :(

**Comment by claywilkinson** [comment] 2015-10-13 14:44
Is it consistent?  If you can get a log of it not showing up that would be awesome.  At least can you post what version of Play Services, the Play Games App, and OS version.

**Comment by claywilkinson** [comment] 2015-10-13 17:40
So on Android, there are some edge cases that can cause the welcome toast not to be visible.  These can be things like - changing the view so the toast is actually "off screen", also some input events can dismiss the toast  - so it can show/hide quickly.  Also, if the app is being resumed, depending on some internal state, the toast does not appear (since you are already authenticated).

If you have a consistent reproduction scenario, I'd be interested in investigating more!

**Comment by banditdevelopment** [comment] 2015-10-13 18:16
I've seen inconsistent 'Welcome Back' UI on almost every Android game with GPS, including Clash of Clans. I figure it's not a big enough issue if Supercell hasn't fixed it.

Does the welcome UI display during silent authentication as well?

**Comment by claywilkinson** [comment] 2015-10-21 14:12
If it has been enough time, silent authentication will display the toast.  I am not 100% sure how "enough" time is determined.  The idea behind that is the notification should not distract the player from the game. If they are switching in and out of the game it would be annoying to be welcomed all the time.

**Comment by teemukorh** [comment] 2015-10-22 18:23
That is probably the case in here. Guess google hasn't documented this in their native sdk?

**Comment by claywilkinson** [comment] 2015-10-27 17:59
I'll pass the suggestion along to update the SDK.  OK to close the issue?

**Closed** 2016-01-04 16:57 UTC
Labels: enhancement
