### ISSUE TITLE
Does plugin 0.9.27 work with Unity 4.6.7?

### ISSUE THREAD

**Issue by quangfuky** [playgameservices/play-games-plugin-for-unity#807] opened 2015-11-16 13:23 UTC
I had tested 0.9.27 with unity 5.0.4 and It works just fine. But when I use unity 4.6.7, it has an error that "Unable to convert classes to dex format". I want to use unity 4.6.7 for smaller APK file.

**Comment by claywilkinson** [comment] 2015-11-16 17:50
I have used 4.6.8 with no problems building the "SmokeTest" sample.  Usually this error is caused by having duplicate jars or classes.  Maybe make sure there are no "* 1." copies of the jars.

**Comment by xike456** [comment] 2015-11-16 18:00
I tested plugin 0.9.27 with minimal sample. If i'm not set up Android, i could build the apk. After I set up Android, the plugin import something then I couldn't build and have the error above. I tested with 0.9.25 and everything works just fine.

**Comment by claywilkinson** [comment] 2015-11-16 18:06
Can you share the contents of your Assets/Plugins/Android directory?

**Comment by xike456** [comment] 2015-11-16 18:21
Here link for Android directory:
https://drive.google.com/file/d/0B1AdvGYvRpEYdnJmUVRiS1d3SDA/view?usp=sharing

**Comment by claywilkinson** [comment] 2015-11-16 18:36
Try deleting the .aar files in Assets/Plugins/Android - these  overlap with the google_play_services_lib.  I am pretty sure that 4.6 does not fully support .aar files (but 5+ does - which is much nicer).

For my own curiosity, how much smaller is the apk with 4.6 vs. 5.2?  The main reason for the plugin to switch to .aar files was to reduce the amount of code being added to the apk by ~50%.

**Comment by xike456** [comment] 2015-11-16 18:46
I work with 2D game project. With 4.6 the apk size about 13mb but 5.0 is about 18mb. 5mb is pretty much for a small 2D game. Thanks for your support, i will check and reply if it works.

**Comment by fido77** [comment] 2015-11-18 05:56
I am having the same issue with the "Unable to convert classes to dex format" in 4.6.7. The other plugins I have are Unity Ads and a plugin for Perk. I have removed all the .aar files in the game folder and still get the error. It looks like there are duplicate classes in the .jar files, but there are no duplicate .jar files that I can see. I will paste in the full error I am getting in hopes that helps to resolve this issue. 

Error building Player: CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
C:/Program Files/Java/jdk1.7.0_76\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Android/sdk\tools" -Dfile.encoding=UTF8 -jar "C:/Program Files (x86)/Unity/Editor/Data/BuildTargetTools/AndroidPlayer\sdktools.jar" -

stderr[

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Landroid/support/annotation/AnimRes;
	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
	at com.android.dx.command.dexer.Main.processClass(Main.java:732)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at SDKMain.main(SDKMain.java:130)

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Landroid/support/annotation/WorkerThread;
	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
	at com.android.dx.command.dexer.Main.processClass(Main.java:732)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at SDKMain.main(SDKMain.java:130)

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/dynamic/LifecycleDelegate;
	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
	at com.android.dx.command.dexer.Main.processClass(Main.java:732)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at SDKMain.main(SDKMain.java:130)
3 errors; aborting
]

**Comment by fido77** [comment] 2015-11-18 05:57
I had to cut some of it out due to it was too long. But that is the main part that shows what classes are duplicated I believe.

**Comment by xike456** [comment] 2015-11-18 10:20
@fido77  try 0.9.25. It works for me on Unity 4.6.7

**Comment by lordtyred** [comment] 2015-11-18 19:28
Exactly same problem here. Looks like when building - created another copy of jar or something.
Deleting aar files did not help.
@xike456 There is none 0.9.25 in old-build, did you mean 0.9.21?

**Comment by lordtyred** [comment] 2015-11-18 20:02
0.9.25 works for me too, thanks @xike456. Download it from repository.
I've find all jars in project with search, deleted them and import 0.9.25
It works.

**Comment by fido77** [comment] 2015-11-18 23:06
I have not found a 0.9.25. It only shows 0.9.21 in the old versions when I download the zip.

**Comment by fido77** [comment] 2015-11-18 23:26
I found it. I use GIT, but not that familiar with it enough to think of looking at the branches :p

**Comment by fido77** [comment] 2015-11-19 00:07
I have removed all the jar files, no aar files, and imported 0.9.25. I still get the same error. I also have to remove some stuff from the manifest to get past the manifest errors, but I think I have that down. I know I can delete the android-support-v4 jar file and another and it will build, but I do not know if I need those or not for the Google Play Services.

**Comment by xike456** [comment] 2015-11-19 03:58
@lordtyred @claywilkinson  i found out that we can use 0.9.27 with unity 4.6.7. After import and set up android, open file android-support-v4 and delete folder support/annotation. That folder is the same with folder in support-annotations-xxx.jar file that make unity cant build.
@fido77 try create new project to test the plugin. you may find what is the problem.

**Comment by claywilkinson** [comment] 2015-11-19 04:22
@xike456 - Thanks for the confirmation.  I'll try to add it to the readme and see if we can make the setup do the right thing when running in 4.6

**Comment by fido77** [comment] 2015-11-19 22:56
Is there a way to remove these three classes from the jar files, or make it where it ignores them if they are already in the project?

**Comment by xike456** [comment] 2015-11-20 04:16
@fido77 just open .jar file with winrar or 7zip and delete duplicate file.

**Comment by fido77** [comment] 2015-11-20 04:18
Ok. I will try that.

**Comment by RealMayo** [comment] 2015-11-20 23:58
@xike456 is correct.  Google Play Game Services version 0.9.25 works with Unity version 4.6.7f1.  You can find it here...
https://github.com/playgameservices/play-games-plugin-for-unity/tree/frengle/current-build

**Comment by fido77** [comment] 2015-11-24 16:08
Still not working for me. I found that Perk has one of the jar files in their sdk, but I have not been able to remove it yet.

**Comment by RealMayo** [comment] 2015-11-24 16:53
@fido77 I suggest you create an empty test project and see that you can compile and run v0.9.25 successfully.  Then its just a matter of figuring out which of your other plugins have JARs that conflict with Google Play Game Services JARs.

**Comment by fido77** [comment] 2015-11-24 17:40
I have found which ones conflict. I guess it's just trying to get the duplicate classes or whatever out of one of them and hope it does not cause that SDK to not work correctly.

**Comment by claywilkinson** [comment] 2015-12-11 01:13
OK to close this one?

**Comment by RealMayo** [comment] 2015-12-11 01:30
@claywilkinson Well if you close it, will it still be searchable from Google Search?  That's how I originally stumbled across this, and it helped me realize what was going, and what to do.

**Comment by claywilkinson** [comment] 2015-12-11 01:33
Yes, closed services are searchable.  It just makes it easier to see what is an open issue vs. resolved.

**Comment by RealMayo** [comment] 2015-12-11 03:23
Cool well in all honesty this issue is only resolved via the workaround of using the older version (v0.9.25).  Ideally you could analyze that older version and see why it works whereas the version (v0.9.27) doesn't work. Or are you saying that there's a newer version out now in which you believe this to be fixed?

**Comment by fido77** [comment] 2015-12-11 05:04
I still have an issue, but I think I have got everything I can from here. I am using 0.9.25 now and actually have leader boards working. now my other stuff don't seem to be working. weird, everything is working great in the Unity editor, but when I launch it to Google Play, it don't work. I'll figure out something.

**Closed** 2016-01-04 17:04 UTC
