### ISSUE TITLE
Small issue 

### ISSUE THREAD

**Issue by loftyy** [playgameservices/play-games-plugin-for-unity#937] opened 2016-01-29 19:07 UTC
1. Search for a room [RTMP], starts searching and everything is working.
2. I stop searching for a match.
3. Try to search for a room again but it doesn't work anymore.
4. I have to exit the app and close it then it will work again.

Is there a way to fix this small issue?

**Comment by claywilkinson** [comment] 2016-01-29 19:22
How do you stop searching for a match?  Do you leave the room?  Can you share the log of what happens when you try to start quick match again?

**Comment by loftyy** [comment] 2016-01-30 00:43
Yes, I press the arrow or "Quit Match". I will try to get the logs to you asap !

**Comment by loftyy** [comment] 2016-01-31 02:07
Here is what shows up when do step 3 from my first post:




E/Unity   (20176):
E/Unity   (20176): (Filename: ./Runtime/GfxDevice/egl/WindowContextEGL.cpp Line: 205)
E/Unity   (20176):
W/Unity   (20176): *** [Play Games Plugin DLL] 01/31/16 1:59:41 +00:00 ERROR: Received attempt to create a new room without cleaning up the old one.
W/Unity   (20176):
W/Unity   (20176): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
W/Unity   (20176):

**Comment by claywilkinson** [comment] 2016-02-01 16:50
Do you call LeaveRoom() when you quit the match?  This will clean up the room, so you can create a new one.

**Comment by loftyy** [comment] 2016-02-02 06:25
I don't know where in your code I should add LeaveRoom() because I press back on the **google play waiting UI** not my own UI, do you know in which of your scripts i should add leave room?

**Comment by danspeedy1** [comment] 2016-02-03 22:15
Seeing the same issue when using the waiting room UI. Pressing the back button and then 'create quick game' results in the following debug output:


02-03 22:12:51.717: I/Unity(4798):  [Play Games Plugin DLL] 02/03/16 22:12:51 +00:00 DEBUG: Entering state: BeforeRoomCreateStartedState
02-03 22:12:51.717: I/Unity(4798):  
02-03 22:12:51.717: I/Unity(4798): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
02-03 22:12:51.717: I/Unity(4798):  [Play Games Plugin DLL] 02/03/16 22:12:51 +00:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.
02-03 22:12:51.717: I/Unity(4798):  
02-03 22:12:51.717: I/Unity(4798): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
02-03 22:12:51.717: I/Unity(4798):  [Play Games Plugin DLL] 02/03/16 22:12:51 +00:00 DEBUG: ConnectingState.IsNonPreemptable: Is preemptable by default.
02-03 22:12:51.717: I/Unity(4798):  
02-03 22:12:51.717: I/Unity(4798): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
02-03 22:12:51.717: W/Unity(4798): *** [Play Games Plugin DLL] 02/03/16 22:12:51 +00:00 ERROR: Received attempt to create a new room without cleaning up the old one.
02-03 22:12:51.717: W/Unity(4798):  
02-03 22:12:51.717: W/Unity(4798): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
02-03 22:12:51.717: I/Unity(4798):  [Play Games Plugin DLL] 02/03/16 22:12:51 +00:00 DEBUG: Session was torn down before room was created.
02-03 22:12:51.717: I/Unity(4798):  
02-03 22:12:51.717: I/Unity(4798): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
02-03 22:12:51.717: I/Unity(4798):  [Play Games Plugin DLL] 02/03/16 22:12:51 +00:00 DEBUG: Entering state: ShutdownState
02-03 22:12:51.717: I/Unity(4798):  
02-03 22:12:51.717: I/Unity(4798): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
02-03 22:12:51.717: I/Unity(4798):  [Play Games Plugin DLL] 02/03/16 22:12:51 +00:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.
02-03 22:12:51.717: I/Unity(4798):  
02-03 22:12:51.717: I/Unity(4798): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
02-03 22:12:51.717: I/Unity(4798): OnRoomConnected has failed
02-03 22:12:51.717: I/Unity(4798):  
02-03 22:12:51.717: I/Unity(4798): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

**Comment by claywilkinson** [comment] 2016-02-04 00:09
The flow is a little strange, but it is designed to handle starting the waiting room, then leaving, then going back, etc.

When the waiting room UI is left, there are 3 cases:
1.  The room is ready - so start playing OnRoomConnected() is called.
2. The player left the room (or the match in this case, not the waiting room UI).  LeaveRoom() is called internally, and OnLeftRoom() is called.
3. The back button was hit.  The state of the multiplayer room is still pending, so OnRoomSetupProgress() is called.

If you click the menu on the waiting room and Quit Match, this will leave the room, and it should be in a clean state to create a new room.

If you are going back to the menu or something where a new match can be created, you should make sure LeaveRoom() is called.

**Comment by loftyy** [comment] 2016-02-04 06:18
Hm, I'm trying to call LeaveRoom when the player clicks on search after having quit. I don't get the error in logcat but I still get no response.

**Comment by danspeedy1** [comment] 2016-02-04 09:01
I now ensure that LeaveRoom() is called when the user presses the button that kicks off a new quick game but the waiting room UI does not open  again. Funnily enough, if I get another device to start a quick game, then the game does start on both devices.

Here is the log after clicking the quick game button a second time:

02-03 23:53:34.461: I/Unity(6459):  [Play Games Plugin DLL] 02/03/16 23:53:34 +00:00 DEBUG: Entering state: LeavingRoom
02-03 23:53:34.461: I/Unity(6459):  
02-03 23:53:34.461: I/Unity(6459): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
02-03 23:53:34.465: I/Unity(6459):  [Play Games Plugin DLL] 02/03/16 23:53:34 +00:00 DEBUG: LeavingRoom.IsRoomConnected: Returning room not connected.
02-03 23:53:34.465: I/Unity(6459):  
02-03 23:53:34.465: I/Unity(6459): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
02-03 23:53:34.465: I/Unity(6459):  [Play Games Plugin DLL] 02/03/16 23:53:34 +00:00 DEBUG: Entering state: BeforeRoomCreateStartedState
02-03 23:53:34.465: I/Unity(6459):  
02-03 23:53:34.465: I/Unity(6459): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
02-03 23:53:34.469: I/Unity(6459):  [Play Games Plugin DLL] 02/03/16 23:53:34 +00:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.
02-03 23:53:34.469: I/Unity(6459):  
02-03 23:53:34.469: I/Unity(6459): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
02-03 23:53:34.469: I/Unity(6459):  [Play Games Plugin DLL] 02/03/16 23:53:34 +00:00 DEBUG: QuickGame: Setting MinPlayersToStart = 1
02-03 23:53:34.469: I/Unity(6459):  
02-03 23:53:34.469: I/Unity(6459): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
02-03 23:53:34.469: I/Unity(6459):  [Play Games Plugin DLL] 02/03/16 23:53:34 +00:00 DEBUG: OnData Callback has addr: 75
02-03 23:53:34.469: I/Unity(6459):  
02-03 23:53:34.469: I/Unity(6459): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
02-03 23:53:34.469: I/Unity(6459):  [Play Games Plugin DLL] 02/03/16 23:53:34 +00:00 DEBUG: BeforeRoomCreateStartedState.IsNonPreemptable: Is preemptable by default.
02-03 23:53:34.469: I/Unity(6459):  
02-03 23:53:34.469: I/Unity(6459): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
02-03 23:53:34.469: I/Unity(6459):  [Play Games Plugin DLL] 02/03/16 23:53:34 +00:00 DEBUG: Entering state: RoomCreationPendingState
02-03 23:53:34.469: I/Unity(6459):  
02-03 23:53:34.469: I/Unity(6459): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
02-03 23:53:34.469: I/Unity(6459):  [Play Games Plugin DLL] 02/03/16 23:53:34 +00:00 DEBUG: RoomCreationPendingState.OnStateEntered: Defaulting to no-op.
02-03 23:53:34.469: I/Unity(6459):  
02-03 23:53:34.469: I/Unity(6459): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
02-03 23:53:34.477: D/ChimeraCfgMgr(3051): Loading module com.google.android.gms.games from APK com.google.android.play.games
02-03 23:53:34.477: D/ChimeraModuleLdr(3051): Module APK com.google.android.play.games already loaded
02-03 23:53:34.481: V/GLSActivity(2854): AuthDelegateWrapperCreated with selected intent: Intent { cmp=com.google.android.gms/.auth.DefaultAuthDelegateService }
02-03 23:53:34.481: V/GLSActivity(2854): AuthDelegateWrapperCreated with selected intent: Intent { cmp=com.google.android.gms/.auth.DefaultAuthDelegateService }
02-03 23:53:34.689: D/Genymotion(2520): Received Ping
02-03 23:53:34.773: D/dalvikvm(2854): GC_FOR_ALLOC freed 517K, 30% free 3799K/5352K, paused 5ms, total 5ms
02-03 23:53:34.825: I/Unity(6459):  [Play Games Plugin DLL] 02/03/16 23:53:34 +00:00 DEBUG: Entering internal callback for InternalLeaveRoomCallback
02-03 23:53:34.825: I/Unity(6459):  
02-03 23:53:34.825: I/Unity(6459): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
02-03 23:53:34.825: I/Unity(6459):  [Play Games Plugin DLL] 02/03/16 23:53:34 +00:00 DEBUG: Entering state: ShutdownState
02-03 23:53:34.825: I/Unity(6459):  
02-03 23:53:34.825: I/Unity(6459): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
02-03 23:53:34.825: I/Unity(6459):  [Play Games Plugin DLL] 02/03/16 23:53:34 +00:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.
02-03 23:53:34.825: I/Unity(6459):  
02-03 23:53:34.825: I/Unity(6459): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
02-03 23:53:34.825: I/libjingle(4104): virtual int games_rtmp::BuzzSubscriptionsTask::SetOnDisconnectTask::ProcessStart(): Send-on-disconnect: <cli:message to="games@ob.talk.google.com" type="headline" xmlns:cli="jabber:client"><push xmlns="google:push" channel="games.google.com/buzzbot" sendOnDisconnect="true"><recipient to="play-presence@games.bot.talk.google.com" remove="true"/></push></cli:message>
02-03 23:53:34.829: I/Unity(6459): OnRoomConnected has failed
02-03 23:53:34.829: I/Unity(6459):  
02-03 23:53:34.829: I/Unity(6459): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
02-03 23:53:34.833: I/libjingle(4104): worker_thread:0xb947c4e8 initialized=1
02-03 23:53:34.837: I/libjingle(4104): SSL Cleanup
02-03 23:53:34.849: D/dalvikvm(2854): GC_FOR_ALLOC freed 531K, 30% free 3779K/5352K, paused 9ms, total 9ms
02-03 23:53:34.909: D/dalvikvm(2854): GC_FOR_ALLOC freed 455K, 29% free 3832K/5352K, paused 8ms, total 8ms
02-03 23:53:35.937: D/dalvikvm(2854): GC_FOR_ALLOC freed 530K, 29% free 3813K/5352K, paused 6ms, total 6ms
02-03 23:53:35.985: D/dalvikvm(2854): GC_FOR_ALLOC freed 484K, 29% free 3841K/5352K, paused 8ms, total 8ms
02-03 23:53:35.989: I/libjingle(4104): Token type:OAuth2
02-03 23:53:35.989: I/libjingle(4104): Final XMPP server hostname talk.google.com port to 5222
02-03 23:53:36.029: D/dalvikvm(2854): GC_FOR_ALLOC freed 524K, 29% free 3828K/5352K, paused 5ms, total 5ms
02-03 23:53:36.133: I/libjingle(4104): OpenSSLAdapter::OnConnectEvent
02-03 23:53:36.433: I/libjingle(4104): BeginSSL: talk.google.com
02-03 23:53:36.677: D/Genymotion(2520): Received Ping
02-03 23:53:37.661: I/libjingle(4104): Starting Jingle info task.
02-03 23:53:37.661: I/libjingle(4104): IbbDataTask::ProcessStart() called:
02-03 23:53:37.661: I/libjingle(4104): ProcessStart()::Sending Jingle info stanza.
02-03 23:53:37.661: I/libjingle(4104): BuzzSubscriptionsTask::SubscribeTask::ProcessStart() called:
02-03 23:53:37.661: I/libjingle(4104): void games_rtmp::BuzzSubscription::CheckOverride(): Channel GAMES_NOTIFICATION_CHANNEL default: games.google.com
02-03 23:53:37.661: I/libjingle(4104): void games_rtmp::BuzzSubscription::CheckOverride(): Notifier GAMES_NOTIFICATION_JID default: games@google.com
02-03 23:53:37.661: I/libjingle(4104): void games_rtmp::BuzzSubscription::CheckOverride(): Channel GAMES_BUZZBOT_CHANNEL default: games.google.com/buzzbot
02-03 23:53:37.661: I/libjingle(4104): void games_rtmp::BuzzSubscription::CheckOverride(): Notifier GAMES_BUZZBOT_JID default: play-presence@games.bot.talk.google.com
02-03 23:53:37.661: I/libjingle(4104): SUBSCRIBE STANZA: <cli:iq type="set" to="games@ob.talk.google.com" id="9" xmlns:cli="jabber:client"><subscribe xmlns="google:push"><item channel="games.google.com" from="games@google.com"/><item channel="games.google.com/buzzbot" from="play-presence@games.bot.talk.google.com"/></subscribe></cli:iq>
02-03 23:53:37.661: I/libjingle(4104): Send Stanza return ok:
02-03 23:53:37.865: I/libjingle(4104): OnJingleInfo called. Setting relay/stun hosts.
02-03 23:53:38.077: I/libjingle(4104): SubscribeTask HandleStanza : <cli:iq to="games@ob.talk.google.com/games_andr0CF9D92A" from="games@ob.talk.google.com" id="9" type="result" xmlns:cli="jabber:client"/>
02-03 23:53:38.077: I/libjingle(4104): void games_rtmp::BuzzSubscriptionsTask::SubscriptionSuccess(): Subscription Successful.
02-03 23:53:38.077: D/ChimeraCfgMgr(3051): Loading module com.google.android.gms.games from APK com.google.android.play.games
02-03 23:53:38.077: D/ChimeraModuleLdr(3051): Module APK com.google.android.play.games already loaded
02-03 23:53:38.685: D/Genymotion(2520): Received Ping
02-03 23:53:38.761: D/dalvikvm(3051): GC_FOR_ALLOC freed 1033K, 21% free 5594K/7032K, paused 5ms, total 6ms
02-03 23:53:38.785: D/dalvikvm(2854): GC_FOR_ALLOC freed 517K, 29% free 3822K/5352K, paused 7ms, total 7ms
02-03 23:53:38.829: D/dalvikvm(2854): GC_FOR_ALLOC freed 523K, 29% free 3811K/5352K, paused 6ms, total 6ms
02-03 23:53:38.861: I/libjingle(4104): virtual int games_rtmp::BuzzSubscriptionsTask::SetOnDisconnectTask::ProcessStart(): Send-on-disconnect: <cli:message to="games@ob.talk.google.com" type="headline" xmlns:cli="jabber:client"><push xmlns="google:push" channel="games.google.com/buzzbot" sendOnDisconnect="true"><recipient to="play-presence@games.bot.talk.google.com">Q2hvS0NRaVBtdGJXb3dzUUFoQUJHQUFnX19fX19fX19fX19fQVJDX3BNUF91Zkc3elVBOmdhbWVzQG9iLnRhbGsuZ29vZ2xlLmNvbS9nYW1lc19hbmRyMENGOUQ5MkE=</recipient></push></cli:message>
02-03 23:53:38.861: I/Unity(6459):  [Play Games Plugin DLL] 02/03/16 23:53:38 +00:00 DEBUG: Entering internal callback for RealtimeManager#InternalRealTimeRoomCallback
02-03 23:53:38.861: I/Unity(6459):  
02-03 23:53:38.861: I/Unity(6459): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
02-03 23:53:38.861: I/Unity(6459):  [Play Games Plugin DLL] 02/03/16 23:53:38 +00:00 DEBUG: Entering state: ConnectingState
02-03 23:53:38.861: I/Unity(6459):  
02-03 23:53:38.861: I/Unity(6459): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

**Comment by danspeedy1** [comment] 2016-02-04 10:13
To clarify, if I start a quick game on the main menu, then close the Waiting Room UI using the back button and am taken back to the main menu then the game will still start if another player starts a quick game on a different device. It appears as though closing the Waiting Room UI does not cause the player to leave the room.

**Comment by loftyy** [comment] 2016-02-04 14:54
@danspeedy1 I hadn't noticed that but it does happen with me too...

**Comment by claywilkinson** [comment] 2016-02-04 15:52
Correct.  Closing the waiting room UI does not leave the room.  This is by design, allowing for things like adjusting options, etc while waiting for other players.  To have the behaviour you are describing, you'll need to set a flag as you show the waiting room UI.  Then clear the flag when OnLeftRoom or OnRoomConnected is called.  If you make it back to the main menu and the flag is set, then call LeaveRoom().

Does that make sense?

**Comment by danspeedy1** [comment] 2016-02-04 20:32
@claywilkinson Thanks for the reply. I took what you said on board and have tried to implement the behaviour I am after but I am still struggling. I added a button to the main menu which calls "PlayGamesPlatform.Instance.RealTime.LeaveRoom ();". I click "Quick Game", see the waiting room, click the back button to return to main menu and then click the new "leave room" button but I get the following logs and am unable to start a new game. Any ideas?

02-04 20:30:09.044: I/Unity(14942):  [Play Games Plugin DLL] 02/04/16 20:30:09 +00:00 DEBUG: Entering state: LeavingRoom
02-04 20:30:09.044: I/Unity(14942):  
02-04 20:30:09.044: I/Unity(14942): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
02-04 20:30:09.048: D/ChimeraCfgMgr(9222): Loading module com.google.android.gms.games from APK com.google.android.play.games
02-04 20:30:09.048: D/ChimeraModuleLdr(9222): Module APK com.google.android.play.games already loaded
02-04 20:30:09.052: V/GLSActivity(9005): AuthDelegateWrapperCreated with selected intent: Intent { cmp=com.google.android.gms/.auth.DefaultAuthDelegateService }
02-04 20:30:09.056: V/GLSActivity(9005): AuthDelegateWrapperCreated with selected intent: Intent { cmp=com.google.android.gms/.auth.DefaultAuthDelegateService }
02-04 20:30:09.072: W/audio_hw_primary(8407): out_write() limiting sleep time 30678 to 23219
02-04 20:30:09.336: D/dalvikvm(9005): GC_FOR_ALLOC freed 553K, 20% free 4009K/4956K, paused 5ms, total 6ms
02-04 20:30:09.356: I/Unity(14942):  [Play Games Plugin DLL] 02/04/16 20:30:09 +00:00 DEBUG: Entering internal callback for InternalLeaveRoomCallback
02-04 20:30:09.356: I/Unity(14942):  
02-04 20:30:09.356: I/Unity(14942): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
02-04 20:30:09.368: I/libjingle(10940): virtual int games_rtmp::BuzzSubscriptionsTask::SetOnDisconnectTask::ProcessStart(): Send-on-disconnect: <cli:message to="games@ob.talk.google.com" type="headline" xmlns:cli="jabber:client"><push xmlns="google:push" channel="games.google.com/buzzbot" sendOnDisconnect="true"><recipient to="play-presence@games.bot.talk.google.com" remove="true"/></push></cli:message>
02-04 20:30:09.372: I/libjingle(10940): worker_thread:0xb916fb88 initialized=1
02-04 20:30:09.376: I/libjingle(10940): SSL Cleanup
02-04 20:30:09.384: I/Unity(14942):  [Play Games Plugin DLL] 02/04/16 20:30:09 +00:00 DEBUG: Entering state: ShutdownState
02-04 20:30:09.384: I/Unity(14942):  
02-04 20:30:09.384: I/Unity(14942): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
02-04 20:30:09.384: I/Unity(14942):  [Play Games Plugin DLL] 02/04/16 20:30:09 +00:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.
02-04 20:30:09.384: I/Unity(14942):  
02-04 20:30:09.384: I/Unity(14942): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
02-04 20:30:09.392: I/Unity(14942): OnRoomConnected has failed
02-04 20:30:09.392: I/Unity(14942):  
02-04 20:30:09.392: I/Unity(14942): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
02-04 20:30:09.400: D/dalvikvm(9005): GC_FOR_ALLOC freed 539K, 20% free 4007K/4956K, paused 10ms, total 10ms
02-04 20:30:10.188: D/Genymotion(8654): Received Ping

**Comment by loftyy** [comment] 2016-02-05 01:10
I understand what you are saying but I don't know how  how i can check if the flag is set when returned to main menu. Isn't it easier to modify your code so that LeaveRoom() is called once the back button is touched or "Quit Match" ? Since i don't need players to adjust some options while waiting.

**Comment by danspeedy1** [comment] 2016-02-05 15:05
@loftyy I think I've figured it out. I'm at work but will be able to post my solution tonight. Hang tight!

**Comment by loftyy** [comment] 2016-02-05 22:07
thank you @danspeedy1 ! :+1:

**Comment by loftyy** [comment] 2016-02-07 00:26
@danspeedy1 bump?

**Comment by danspeedy1** [comment] 2016-02-07 01:50
Apologies, had one small issue to solve. 

@claywilkinson was correct and here is how I've implemented his suggestion.

In your class that implements RealTimeMultiplayerListener add the following field:

```private bool showingWaitingRoom = false;```

Add the following update method:

```
	void Update ()
	{
		if (showingWaitingRoom && !PlayGamesPlatform.Instance.RealTime.IsRoomConnected ()) {
			Debug.Log ("IM INSIDE HERE");
			PlayGamesPlatform.Instance.RealTime.LeaveRoom ();
		}
	}
```

Add the following code to your 'OnRoomSetupProgress' method:

```
	public void OnRoomSetupProgress (float percent)
	{
		// show the default waiting room.
		if (!showingWaitingRoom) {
			showingWaitingRoom = true;
			PlayGamesPlatform.Instance.RealTime.ShowWaitingRoomUI ();
		}
	}
```

In your 'OnRoomConnected' check for the success boolean to be false and set the 'showingWaitingRoom' to false:

```
	public void OnRoomConnected (bool success)
	{
		if (success) {
			//start game
		} else {
			Debug.Log ("OnRoomConnected has failed");
			showingWaitingRoom = false;
		}
	}
```

Add a line to your 'OnLeftRoom' method to set the 'showingWaitingRoom' to false:

```
	public void OnLeftRoom ()
	{
		showingWaitingRoom = false;
	}
```


Now, this works because our Unity app is paused when the Waiting Room UI is shown and so the update method does not run. When the user cancels the UI and returns to the main menu, the update method begins again at which point we leave the room.

Hope this works for you too @loftyy. Let me know if anything doesn't make sense.

**Comment by loftyy** [comment] 2016-02-08 14:20
@danspeedy1 thanks danny, I implemented what you did but it's not working. I recieve this in the logcat once I press the button to join a match after having quit the search : 
`I/Unity   (13980): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (13980):
I/Unity   (13980): OnRoomConnected has failed
I/Unity   (13980):
I/Unity   (13980): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (13980):
I/Unity   (13980): OnRoomConnected has failed
I/Unity   (13980):
I/Unity   (13980): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (13980):
I/Unity   (13980): OnRoomConnected has failed
I/Unity   (13980):
I/Unity   (13980): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (13980):
I/Unity   (13980): OnRoomConnected has failed
I/Unity   (13980):
I/Unity   (13980): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (13980):
I/Unity   (13980): OnRoomConnected has failed
I/Unity   (13980):
I/Unity   (13980): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (13980):`


here is my code : http://pastebin.com/TKyPmNGs

**Comment by danspeedy1** [comment] 2016-02-08 14:49
Sorry I forgot to remove that line. In my code above, OnRoomConnected has a debug line that prints the message that you are seeing " OnRoomConnected has failed ". But nothing is actually failing; it is just that OnRoomConnected has received a "false" boolean, I think we can both remove that debug line.

Other that the debug log issue, is everything working? (as your update suggests?)

**Comment by loftyy** [comment] 2016-02-08 19:20
@danspeedy1  It is working but there is one small issue, the first time I hit search, the google play waiting UI comes up for like 0.2s and then disapears. When I hit search (2nd time), the google play waiting UI comes up and searches for a match as usual, after this points I can quit/back out and keep pressing search and it would work properly. Except for the first time. Are you getting the same issue? Thanks btw ! :+1: :)

**Comment by danspeedy1** [comment] 2016-02-09 08:31
Great. Glad you got it working too. Not sure here is the right place to post but my twitter is @digital_distrac. PM me.

**Comment by danspeedy1** [comment] 2016-02-09 08:31
@loftyy

**Comment by claywilkinson** [comment] 2016-02-17 18:30
OK to close this one?

**Closed** 2016-04-04 20:12 UTC
