### ISSUE TITLE
Leaderboards not working

### ISSUE THREAD

**Issue by AjayKhara** [playgameservices/play-games-plugin-for-unity#341] opened 2014-12-31 08:23 UTC
I made a unity build yesterday, in which leaderboards worked fine.
After upgrading android sdk yesterday to the latest the leaderboards do not work anymore.

I updated the google play services to revision 22

Tried both the builds, from before upgrading the google play services(leaderboard works fine here) and after upgrading the play game services(leaderboard does not work, it says "No leaderboards for this game").

Also having this warning after upgrading.
![screen shot 2014-12-31 at 1 56 27 pm](https://cloud.githubusercontent.com/assets/3821924/5586470/ef3c0f90-90f4-11e4-95dc-2ce2954a8240.png)

Please help

**Comment by Otawo** [comment] 2015-01-02 16:06
I can confirm this as well. I have been having the same problem, and to try and launch my game as soon as possible, I had to revert to the Prime[31] GPGS, would really rather use this GPGS as it was much easier to get it to work than the Prime[31] one.

**Comment by mrggl** [comment] 2015-01-09 01:55
Your report makes it sound like the issue is independent of the Unity plugin and play services.

Are you sure your game is correctly configured in the play games developer console? It's possible for leaderboards to "disappear" if you're playing an unpublished game from an account that isn't a tester for the game. See https://developers.google.com/games/services/common/concepts/leaderboards for more.

**Comment by AjayKhara** [comment] 2015-01-15 10:20
Hello,
Yes it is configured correctly in the developer console, somehow the leaderboard work fine, but after upgrading the google play game services to version 22 it does not work anymore. And I get the warning displayed in the picture from the above post.

**Comment by mrggl** [comment] 2015-01-16 01:29
What do you mean by "it does not work anymore"? Is the problem simply that leaderboard UI doesn't display anything? Are you still able to submit scores to the leaderboard? Are there obvious errors in the log?

**Comment by AjayKhara** [comment] 2015-01-16 03:40
By that I mean, it does not authenticate to leaderboards, and Social.ShowLeaderboard() call does not show the UI anymore. And no I am not able to submit scores to leaderboard.
mrggl - can you just confirm that the plugin works fine when upgrading to the latest android sdk ?

**Comment by Voltarian** [comment] 2015-01-31 12:03
Same issue here. The game is in the Android Market with a working leaderboard. Since update of the SDK the leaderboard isn't showing up in the trunkversion. I even took an old branch (release version), build an apk from it, still not working.

**Comment by Voltarian** [comment] 2015-02-01 20:30
Okay I probably fixed the issue. It has not something to do with the version of the sdk. You need to sign  the apk. For testing reasons I never signed the app and of course it didn't authenticate. Signing solved the issue (That took me a month of bughunting...) for me.

**Comment by Otawo** [comment] 2015-02-02 01:22
I have always signed my APKs. You can't upload APKs to the Dev console as Beta unless you do. However I think that my personal issues were related to an issue with the Keystore becoming corrupted and needing to be replaced, when I had not made a backup copy of it. We replaced the online project and got everything working right.

**Comment by claywilkinson** [comment] 2015-02-02 15:59
@Otawo - glad to hear you got it working again.   @AjayKhara  - back to your original question, this is a known issue.  The version information in the SDK library has changed slightly causing a false alarm about the version.  This should be fixed shortly (or at least a workaround).

**Comment by AjayKhara** [comment] 2015-02-02 18:01
Thank you guys,
Yes it works perfectly now.

**Closed** 2015-02-12 20:48 UTC
