### ISSUE TITLE
Plugin Crash at Starting.

### ISSUE THREAD

**Issue by balatimuz** [playgameservices/play-games-plugin-for-unity#1635] opened 2017-03-08 13:54 UTC
Exception in dalvik/system/DexClassLoader.loadClass: java.lang.IncompatibleClassChangeError: Class com.google.android.gms.games.NativeSdkCallbacks implements non-interface class com.google.android.gms.nearby.connection.Connections$ConnectionRequestListener (declaration of 'com.google.android.gms.games.NativeSdkCallbacks' appears in /data/user/0/com.timuzsolutions.carracinggames/app_.gpg.classloader/d75c8e1bbeab9e1ddffb9d332585db71.jar).

Is it because of .aar files with latest Version 10.2.0..?

![capture](https://cloud.githubusercontent.com/assets/6349174/23706584/cb05b81e-0434-11e7-96a6-b30136fa6c8f.JPG)

**Comment by CTePeoTun** [comment] 2017-03-08 16:01
I also have this problem :( Help plz

**Comment by germafica** [comment] 2017-03-08 16:37
The .aar files work with 10.0.1 version. I recommend you check this issue #1607 and let me know if my steps working for you :)

**Comment by balatimuz** [comment] 2017-03-09 08:02
Thank you for reply, but we  cannot work with old .aar files.
Not sure why the plugin developers not able to fix..?
If it is officially from google they must have fixed it already..

**Comment by eklebanski** [comment] 2017-03-10 12:16
I think it's the same issue as #1629

**Comment by AdnanNazir** [comment] 2017-03-27 10:23
hello, the plugin isn't updated from past 3 months. 
Why is it so ?

**Comment by claywilkinson** [comment] 2017-04-05 14:24
Hello! There will be an update to the plugin this week that fixes this issue.  Closing this issue as a duplicate of #1604.

**Closed by claywilkinson** 2017-04-05 14:24 UTC
