### ISSUE TITLE
Two authenticates not implemented

### ISSUE THREAD

**Issue by Ethan-Shap** [playgameservices/play-games-plugin-for-unity#1514] opened 2016-12-10 21:32 UTC
I'm using the latest version of the google play plugin and Unity 5.5.0f. Both of the below are giving me errors for not being implemented.

- 'PlayGamesLocalUser' does not implement interface member 'ILocalUser.Authenticate(Action<bool, string>)'
-  'PlayGamesPlatform' does not implement interface member 'ISocialPlatform.Authenticate(ILocalUser, Action<bool, string>)'	

When I used the same plugin in unity 5.4.1 it worked perfectly fine, but since I've updated it is giving me these errors.

**Comment by tommyzat** [comment] 2016-12-10 23:54
Replace with these:

https://github.com/playgameservices/play-games-plugin-for-unity/commit/f199bbdf2386572ea06d273ca55d3cd87552a316

**Comment by claywilkinson** [comment] 2016-12-16 16:48
Unity version 5.5 changed the signature of these methods.  As @tommyzat pointed out a fix has been merged into the source.  I am working on updating the unitypackage in the next few days.  In the mean time, you can copy the change from GitHub into your project.

**Comment by claywilkinson** [comment] 2016-12-19 16:41
Closing as a duplicate of #1432

**Closed by claywilkinson** 2016-12-19 16:41 UTC
