### ISSUE TITLE
FATAL EXCEPTION: IntentService[ParsePushService] after update to version 0.9.30

### ISSUE THREAD

**Issue by Warhate** [playgameservices/play-games-plugin-for-unity#939] opened 2016-02-01 11:53 UTC
My app work fine with version 0.9.27. But after update to version 0.9.30, app crash with:

```
com.nival.pwdefenders2 E/AndroidRuntime: FATAL EXCEPTION: IntentService[ParsePushService]
                                                                        Process: com.nival.pwdefenders2, PID: 19573
                                                                        java.lang.Error: FATAL EXCEPTION [IntentService[ParsePushService]]
                                                                        Unity version     : 5.2.3f1
                                                                        Device model      : Acer A1-840FHD
                                                                        Device fingerprint: acer/a1840fhd_ww_gen1/ducati2fhd:4.4.2/KOT49H/1417676976:user/release-keys 
```

**Comment by claywilkinson** [comment] 2016-02-01 15:42
There probably is more informative log messages before this one to help figure out what is going on.  By the way, this exception is for Parse, no Google Play Game Services.  Have you checked with them?

**Comment by Warhate** [comment] 2016-02-01 15:58
Before it I have 

```
02-01 17:53:22.870 27416-27433/? I/ParsePushUnityHelper: ParsePushService started for GCM registration.
02-01 17:53:22.870 27416-27433/? I/dalvikvm: Could not find method com.google.android.gms.gcm.GoogleCloudMessaging.getInstance, referenced from method com.parse.ParsePushService.onHandleIntent
02-01 17:53:22.870 27416-27433/? W/dalvikvm: VFY: unable to resolve static method 34820: Lcom/google/android/gms/gcm/GoogleCloudMessaging;.getInstance (Landroid/content/Context;)Lcom/google/android/gms/gcm/GoogleCloudMessaging;
02-01 17:53:22.870 27416-27433/? D/dalvikvm: VFY: replacing opcode 0x71 at 0x004c
```

I think com.google.android.gms.gcm.GoogleCloudMessaging have been in google-play-services_lib/ But new post process remove this lib.

**Comment by Warhate** [comment] 2016-02-01 16:01
Maybe need add some dependencies to GPGSDependencies?

**Comment by claywilkinson** [comment] 2016-02-01 16:35
Yes, @Warhate is correct. But rather than adding to GPGSDependencies, create a new file so you don't
lose the dependency when you update the GPGS plugin.

This is preferable to including the whole google_play_services_lib since most of the code in there is probably not used in your game, so it just makes it bigger with no benefit.

 Create a new file in Assets/Editor/GCMDependencies.cs
```
[InitializeOnLoad]                                                              
public static class GCMDependencies                                             
{                                                                               
private static readonly string PluginName = "GCMDependencies";                  
                                                                                
    static GCMDependencies()                                                    
    {                                                                           
        PlayServicesSupport svcSupport = PlayServicesSupport.CreateInstance(    
                                         PluginName,                            
                                         EditorPrefs.GetString("AndroidSdkRoot"),
                                         "ProjectSettings");                    
                                                                                
        svcSupport.DependOn("com.google.android.gms",                           
                "play-services-gcm",                                            
                "8.4+");                                                        
                                                                                
    }                                                                           
} 
```

**Comment by Warhate** [comment] 2016-02-02 11:04
When I added this code to project, I got build exception.

```
CommandInvokationFailure: Failed to re-package resources. See the Console for details.
......
AndroidManifest.xml:73: Tag <provider> attribute authorities has invalid character '$'.
```

I fixed that only undo all the changes.

[FullLog.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/113770/FullLog.txt)

**Comment by claywilkinson** [comment] 2016-02-02 16:32
My guess is that is something not set up in an AndroidManifest.xml file in your project - completely unrelated to the aar dependencies?  Can you share the complete tag ?

**Comment by Warhate** [comment] 2016-02-02 17:06
This manifest I take from Staging Area after a failed build.
[AndroidManifest.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/114317/AndroidManifest.txt)

**Comment by claywilkinson** [comment] 2016-02-02 17:09
The problem is this line: 
```
android:name="com.google.android.gms.measurement.AppMeasurementContentProvider" android:exported="false" android:authorities="${applicationId}.google_measurement_service"/>
```

It looks like something did not substitute the applicationId correctly?

**Comment by Warhate** [comment] 2016-02-02 17:10
Error in line 82:

`android:authorities="${applicationId}.google_measurement_service"`

I guess this was added in post process.

**Comment by Warhate** [comment] 2016-02-02 17:20
I cannot find place where this string was addded.

**Comment by claywilkinson** [comment] 2016-02-03 01:22
This looks like it is a known issue with playservices-measurement aar file.  See http://forum.unity3d.com/threads/dealing-with-new-style-aars-that-have-applicationid-in-their-androidmanifest-xml.380596/

**Comment by Warhate** [comment] 2016-02-03 11:10
Well, I fixed it. I've modified AmdroidManifest in "sdk\extras\google\m2repository\com\google\android\gms\play-services-measurement\8.4.0" and after that build was successful. But I cannot modified AndroidManifest in plugin folder of my project, because postprocess (or somethink other) copies "play-services-measurement" each time. Maybe, there's another way to solve this issue?

**Comment by claywilkinson** [comment] 2016-02-10 17:24
@Warhate - I updated the plugin to version 0.9.31 and it now handles the ${applicationId} in the play-services-measurement  file.  If you upgrade to 0.9.31, it should be better.

**Comment by zeJoker** [comment] 2016-03-22 20:05
I'm facing this problem right now using plugin 0.9.32. I assume I don't need measurement part at all, but it keeps appearing. The only thing that helps is disabling background jar resolution and manually deleting this file. Is there a way to disable including it?

**Comment by claywilkinson** [comment] 2016-03-22 20:39
GCM depends on measurement, that is why it is being pulled in.  I am not sure what the affect of not having it present and using GCM will have.

**Comment by claywilkinson** [comment] 2016-04-04 20:12
OK to close this issue?

**Comment by zeJoker** [comment] 2016-04-04 20:13
Fine for me, thank you!

**Comment by claywilkinson** [comment] 2016-04-05 16:31
you're welcome!

**Closed by claywilkinson** 2016-04-05 16:31 UTC
