### ISSUE TITLE
Jar Resolver (provided in 0.9.35) doesn't work

### ISSUE THREAD

**Issue by qbit86** [playgameservices/play-games-plugin-for-unity#1428] opened 2016-10-12 10:11 UTC
I've removed old `play-services-*-8.4.0.aar`s, restarted Unity. Manually invoked menu item Assets > Play Services Resolver > Android Resolver > Resolve Client Jars. No `play-services-*-9.6.1.aar`s appeared.

```
KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[System.String,System.Collections.Generic.HashSet`1[System.String]].get_Item (System.String key) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:150)
Google.JarResolver.PlayServicesSupport.ResolveDependencies (Boolean useLatest)
GooglePlayServices.ResolverVer1_1.DoResolutionNoAndroidPackageChecks (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation)
GooglePlayServices.ResolverVer1_1+<DoResolution>c__AnonStorey1.<>m__0 ()
GooglePlayServices.ResolverVer1_1.DoResolution (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation, System.Action resolutionComplete)
GooglePlayServices.PlayServicesResolver.Resolve (System.Action resolutionComplete)
GooglePlayServices.PlayServicesResolver.MenuResolve ()
```

---

Unity 5.3.6p6 on Windows 10 Pro targeting Android. Latest Android SDK installed with all components updated via Android SDK Manager.

**Comment by Qbit86** [comment] 2016-10-12 14:33
@claywilkinson Any ideas on how to make Jar Resolver work?

**Comment by claywilkinson** [comment] 2016-10-12 16:36
I am not sure what you are asking?  If you update to 0.9.35, it should alert you that you have upgraded to 0.9.35 successfully, then restart Unity to clear out the old resolver from memory, then run Assets/Play Services Resolver/Android Resolver/Resolve Client jars.

**Comment by Qbit86** [comment] 2016-10-13 08:06
@claywilkinson Investigating with dotPeek shows that problem is probably in `PlayServicesSupport.ResolveDependencies()` in the line
```
this.Log("WARNING: No compatible versions of " + dependency2.VersionlessKey + " required by (" + string.Join(", ", new List<string>((IEnumerable<string>) dictionary3[dependency2.VersionlessKey]).ToArray()) + "), will try using the latest version " + dependency2.BestVersion, false);
```

`dictionary3` seems to not contain requested key (probably typo).

Please help me get Play Services updated; I cannot move on with my tasks, and release is coming :(

**Comment by jeffnatibes** [comment] 2016-10-13 13:53
Hi im having the same problem there is no way for me to get it working. I imported the latest version and keep getting this log.

`WARNING: No compatible versions of com.android.support:support-v4 required by (com.android.support:appcompat-v7:23.1.0+, com.google.android.gms:play-services-basement:9.6.0), will try using the latest version 24.0.0`
`WARNING: No compatible versions of com.android.support:support-annotations required by (com.android.support:support-v4:23.1+, com.android.support:support-v4:24.0.0), will try using the latest version 24.0.0`

What should i do ? I have tried the version before the last one and i get errors with the Logger class everywhere, my realease is close too i need to get this working.

**Comment by claywilkinson** [comment] 2016-10-13 14:36
Looks like there are two issues here:
@Qbit86 - the KeyNotFoundException is resolved by closing Unity, then deleting the file `ProjectSettings/GoogleDependencyGooglePlayGames.xml` and then open Unity and the resolver should work.

@jeffnatibes  - These are warnings and are OK - it is pointing out some inconsistencies in the metadata of the various libraries.  Using the latest version is the correct thing to do.

**Comment by Qbit86** [comment] 2016-10-13 15:01
@claywilkinson 

> _the KeyNotFoundException is resolved by closing Unity..._

This does not help.

Anyway, performing some magic moves is not solution. Well, `KeyNotFoundException` — which key exactly? Why you access item by key in dictionary with `[]` instead of exception-safe check via `TryGetValue()`? Looks like there are some assumptions not satisfied, some logic is broken. This is callee-side issue, not caller-side. `NullReferenceException` and `KeyNotFoundException` should not propagate to user, neither they should be caught — they should be checked in runtime and handled.

**Comment by Qbit86** [comment] 2016-10-13 15:03
@claywilkinson Could you please check the line from decompiled assembly I mentioned above?

**Comment by claywilkinson** [comment] 2016-10-13 15:33
The source is at https://github.com/googlesamples/unity-jar-resolver

The hashset is created by reading an xml file containing all the dependencies that need to be resolved.  Can you share the contents of ProjectSettings/GoogleDependencyGooglePlayGames.xml?

**Comment by Qbit86** [comment] 2016-10-13 15:45
`GoogleDependencyGooglePlayGames.xml`:
```
<dependencies><dependency><groupId>com.google.android.gms</groupId><artifactId>play-services-games</artifactId><version>9+</version><packageIds>extra-google-m2repository</packageIds></dependency><dependency><groupId>com.google.android.gms</groupId><artifactId>play-services-nearby</artifactId><version>9+</version><packageIds>extra-google-m2repository</packageIds></dependency><dependency><groupId>com.google.android.gms</groupId><artifactId>play-services-auth</artifactId><version>9+</version><packageIds>extra-google-m2repository</packageIds></dependency><dependency><groupId>com.android.support</groupId><artifactId>support-v4</artifactId><version>23.1+</version><packageIds>extra-android-m2repository</packageIds></dependency></dependencies>
```

`GoogleDependencyGoogleCloudMessagingPlugin.xml`:
```
<dependencies><dependency><groupId>com.google.android.gms</groupId><artifactId>play-services-gcm</artifactId><version>8.4+</version></dependency></dependencies>
```

`GoogleDependencyGoogle.GPGS.xml`:
```
<dependencies><dependency><groupId>com.google.android.gms</groupId><artifactId>play-services-games</artifactId><version>8.1+</version></dependency><dependency><groupId>com.google.android.gms</groupId><artifactId>play-services-nearby</artifactId><version>8.1+</version></dependency><dependency><groupId>com.google.android.gms</groupId><artifactId>play-services-plus</artifactId><version>8.1+</version></dependency><dependency><groupId>com.android.support</groupId><artifactId>appcompat-v7</artifactId><version>23.1.0+</version></dependency><dependency><groupId>com.google.android.gms</groupId><artifactId>play-services-ads</artifactId><version>8.1+</version></dependency></dependencies>
```

> _The hashset is created by reading an xml file containing all the dependencies that need to be resolved._

It's not the `HashSet` that probably causes problem; it's `Dictionary`, probably this call: `dictionary3[dependency2.VersionlessKey]`

**Comment by Qbit86** [comment] 2016-10-13 15:49
> _The source is at https://github.com/googlesamples/unity-jar-resolver_

`https://github.com/googlesamples/unity-jar-resolver/blob/master/source/JarResolverLib/src/Google.JarResolver/PlayServicesSupport.cs`:
```
Log("WARNING: No compatible versions of " +
    currentDep.VersionlessKey + " required by (" +
    String.Join(
        ", ", (new List<string>(
            reverseDependencyTree[
                currentDep.VersionlessKey])).ToArray()) +
    "), will try using the latest version " +
    currentDep.BestVersion);
```

**Comment by claywilkinson** [comment] 2016-10-13 17:09
First off, thanks for the details - I'll take a look.

 It looks like the problem is with the other xml files, GoogleDependencyGooglePlayGames.xml looks OK - I can see the `packageIds` element, the other two files do not have this element, so they are old.  Can you delete those too?

Do you know which plugins those files are coming from?  you might need to tweak where they call DependOn to match what the new version should have.

For example change:
`
svcSupport.DependOn("com.google.android.gms",                       
                "play-services-plus",                                           
                "8.4+")
`
to be (as seen in [GPGSDependencies.cs](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/Editor/GPGSDependencies.cs#L36)):
```
Google.VersionHandler.InvokeInstanceMethod(                         
                svcSupport, "DependOn",                                         
                new object[] { "com.google.android.gms", "play-services-games", 
                               PluginVersion.PlayServicesVersionConstraint },   
                namedArgs: new Dictionary<string, object>() {                   
                    {"packageIds", new string[] { "extra-google-m2repository" } }
                });  
```

**Comment by kruncher** [comment] 2016-10-13 17:35
I am not sure if this is related but I just performed the following steps:

1. Remove previous version of 'play-games-plugin-for-unity' from my Unity project.
2. Import the latest version (from a day or so ago).
3. It then brings up the following error:

![image](https://cloud.githubusercontent.com/assets/554215/19359831/c5222880-9173-11e6-909c-b5f25a0e7a92.png)

The previous version of 'play-games-plugin-for-unity' was working absolutely fine; for some reason the latest update is broken for me.

Any suggestions?

**Comment by claywilkinson** [comment] 2016-10-13 18:16
@kruncher - There is some code in the resolver that unpacks the aar using `jar` in some cases.  It looks like you need to set JAVA_HOME to the Java SDK (not JRE) and restart Unity.

**Comment by kruncher** [comment] 2016-10-13 18:26
@claywilkinson Thanks for your fast response, this seems to have resolved that issue.

I am now seeing the following messages in the console window:

![image](https://cloud.githubusercontent.com/assets/554215/19361490/c28a3e26-917a-11e6-8d87-53095e2c3023.png)

I am not sure what the `<RI.Hid> Failed to create device file:` message is; I believe that this is probably just an issue with Unity itself; but the other 4 warnings are being output by 'play-games-plugin-for-unity'.

**Comment by claywilkinson** [comment] 2016-10-13 18:33
The warnings are  OK - they are just pointing out inconsistencies in the metadata, and using the latest version is the correct thing to do.

The <RI.Hid> looks like some sort of issue with a driver? a [Quick Google](https://www.google.com/search?q=<RI.Hid>+Failed+to+create+device+file) search shows a lot of things related

**Comment by kruncher** [comment] 2016-10-13 20:08
Cheers :)

**Comment by Qbit86** [comment] 2016-10-13 20:59
@claywilkinson 

> Can you delete those too?

Thanks, I will try this tomorrow.

> It looks like the problem is with the other xml files

Even if they are completely malformed (like containing mp3 instead of xml), the library should inform with some specific exception or error message, so the user can figure out what is wrong and how to fix it.

> Do you know which plugins those files are coming from?

One is from Prime31 plugin for Google Cloud Messaging. (I have let them know that new version of Jar Resolver is available so they can update their plugins.) Don't remember about another, will try to investigate git history tomorrow.

**Comment by Qbit86** [comment] 2016-10-13 21:04
@kruncher 

> for some reason the latest update is broken for me.

Also make sure to update Android SDK via SDK Manager, so it can download latest `play-services-*.aar`s, so Jar Resolver can find them.

**Comment by claywilkinson** [comment] 2016-10-13 23:01
@Qbit86  - totally agree the exception is not acceptable, we're working on a fix.  Thanks again.

**Comment by jeffnatibes** [comment] 2016-10-14 06:58
@claywilkinson Hi thank you for the tip. I still have problems making it work thoe, my app is published as alpha test apk with alpha testers enabled and Google Play Services Testers added aswell. Still cant get the test user to authenticate it always fails. I have debuged through the logcat and i get the following debug message : 

` DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED`

Here is part of the full log : [http://pastebin.com/hEfwbnkF](http://pastebin.com/hEfwbnkF)

What could be causing this ?

P.D: The SHA1 is correctly configured in Google Play Console, Google API Console and the APK is signing with the correct SHA1 from the KeyStore.

**Comment by Qbit86** [comment] 2016-10-14 07:50
> Do you know which plugins those files are coming from?
> One is from Prime31 plugin for Google Cloud Messaging.

The other — `ProjectSettings/GoogleDependencyGoogle.GPGS.xml` — seems to be installed long ago with old version of Google Play Games plugin, like 0.9.27 or so.

> Can you delete those too?

I've deleted those `ProjectSettings/GoogleDependency*.xml` files, and Jar Resolver has finished with no errors. But two `aar`s are still 8.4.0: `play-services-ads-8.4.0.aar`, `play-services-gcm-8.4.0.aar`.

> you might need to tweak where they call DependOn to match what the new version should have.

Currently there are no calls to `DependOn` (apart from `GPGSDependencies.cs`).

**Comment by Qbit86** [comment] 2016-10-19 13:52
@claywilkinson Is it safe to add `ProjectSettings\GoogleAarExplodeCache.xml` to git ignore-list? I guess it should not be versioned, should it?

**Comment by kirilogan** [comment] 2016-10-26 09:27
For those wondering. I ran into this issue recently (today) and was able to solve it by following a mix of steps above and others.

1. Cleaned out my android SDK
2. When running the SDK manager "Run as administrator", and re-installed needed packages
2. Replaced all content of *Dependency*.xml files with <dependencies></<dependencies>
3, Re-ran "Resolve Client Jars"

**Comment by claywilkinson** [comment] 2016-12-28 22:33
@qbit86  - yes, it is safe to add GoogleAarExplodeCache to git ignore.  The latest version of the plugin 0.9.36, uses an updated jar resolver that improves this experience.

**Closed by claywilkinson** 2016-12-28 22:33 UTC
