### ISSUE TITLE
Authentication crashes game

### ISSUE THREAD

**Issue by Suhrahj** [playgameservices/play-games-plugin-for-unity#1647] opened 2017-03-16 03:04 UTC
So at first I thought the issue was the same as this thread: #1629 I just tried removing firebase altogether, but the problem still persists. I tried following logcat but it doesn't really make sense for me. There isn't even an error unless I actually try to use play services:

```
I/Unity(5916): UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
I/Unity(5916): UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
I/Unity(5916): UnityEngine.Logger:Log(LogType, Object)
I/Unity(5916): UnityEngine.Debug:Log(Object)
I/Unity(5916): GooglePlayGames.Native.NativeClient:InitializeGameServices() (at C:\Unity Projects\Test\Assets\GooglePlayGames\Platforms\Native\NativeClient.cs:213)
I/Unity(5916): GooglePlayGames.Native.NativeClient:Authenticate(Action`2, Boolean) (at C:\Unity Projects\Test\Assets\GooglePlayGames\Platforms\Native\NativeClient.cs:132)
I/Unity(5916): GooglePlayGames.PlayGamesPlatform:Authenticate(Action`2, Boolean) (at C:\Unity Projects\Test\Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:403)
I/Unity(5916): GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1, Boolean) (at C:\Unity Projects\Test\Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:372)
I/Unity(5916): GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1) (at C:\Unity Projects\Te
```

It actually ends like that.

**Comment by Tyxz** [comment] 2017-03-16 10:42
Do you use Cloud save? Have the same / similar issue if I activate `.EnableSavedGames()` in the config.

**Comment by Suhrahj** [comment] 2017-03-16 12:35
@Tyxz did you enable saving from developer console? I used to have that with saving and that was the issue.

**Comment by Suhrahj** [comment] 2017-03-16 13:02
@Tyxz That shouldn't be a problem, but did you also publish your game as beta? If you did, there is a section in the console for GPG "Testing" You have to add your testers there too if you haven't and enable beta testers. If you have done that all, all I can think of is if you enabled the saving function recently, it can take up to 2 days to work for some reason.

**Comment by BurningBlueFox** [comment] 2017-03-16 13:19
I'm having the same Issue, its strange since it's something async that crashes, since the log doesn't finish its line before crashing, i have not enabled saved games or anything else, it started happening when i updated the Play-Services plugins to the 10.2.0 version, there must be a workaround to this problem

**Comment by Suhrahj** [comment] 2017-03-16 13:28
@BurningBlueFox yes, that's exactly when it started happening to me too, I tried rolling back, but that also did not work for me for some reason.

**Comment by Tyxz** [comment] 2017-03-16 18:14
@Suhrahj did all of that, but was not sure if I use the feature so I turned it on and off some times, maybe earlier on than 2days. Thanks. Sorry I couldn't help with your issue 😐

**Comment by Suhrahj** [comment] 2017-03-16 18:15
@Tyxz thanksi as far as i know they are working on a solution for the current issue, you should keep an eye for that.

**Comment by claywilkinson** [comment] 2017-04-05 14:20
The updated plugin should be published this week.  Closing this issue as a duplicate of #1604.

**Closed by claywilkinson** 2017-04-05 14:20 UTC
