### ISSUE TITLE
AndroidJavaException when loading Leaderboard

### ISSUE THREAD

**Issue by vanustwo** [playgameservices/play-games-plugin-for-unity#574] opened 2015-06-14 15:45 UTC
Cannot load game leaderboard after signing in.
I'm using Plugin version: 0.9.20 (0x00000920) and Unity 5.1

Repro steps
1. Sign in
2. Call ((PlayGamesPlatform) Social.Active).ShowLeaderboardUI(_leaderboardId);
3. The following error is displayed

06-14 16:35:58.371: I/Unity(16683): UnityEngine.Events.InvokableCall:Invoke(Object[])
06-14 16:35:58.371: I/Unity(16683): UnityEngine.Events.InvokableCallList:Invoke(Object[])
06-14 16:35:58.371: I/Unity(16683): UnityEngine.Events.UnityEventBase:Invoke(Object[])
06-14 16:35:58.371: I/Unity(16683): UnityEngine.Events.UnityEvent:Invoke()
06-14 16:35:58.371: I/Unity(16683): Unit
06-14 16:35:58.401: I/Unity(16683):  [Play Games Plugin DLL] 06/14/15 16:35:58 +01:00 DEBUG: Entering internal callback for AndroidPlatformConfiguration#InternalIntentHandler
06-14 16:35:58.401: I/Unity(16683):  
06-14 16:35:58.401: I/Unity(16683): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
06-14 16:35:58.451: I/Unity(16683): AndroidJavaException: java.lang.ClassNotFoundException: com.google.games.bridge.NativeBridgeActivity
06-14 16:35:58.451: I/Unity(16683):   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0 
06-14 16:35:58.451: I/Unity(16683):   at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (IntPtr clazz, IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <filename unknown>:0 
06-14 16:35:58.451: I/Unity(16683):   at UnityEngine.AndroidJavaObject._CallStatic[AndroidJavaObject] (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0 
06-14 16:35:58.451: I/Unity(16683):   at UnityEngine.AndroidJavaObject.CallStatic[AndroidJavaObject] (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0 
06-14 16:35:58.451: I/Unity(16683):   at UnityEngine.AndroidJavaObject.FindClass (System.String name) [0x00000] in <filename unknown>:0 
06-14 16:35:58.451: I/Unity(16683):   at UnityEngine.AndroidJavaClass._AndroidJavaClass (System.String className) [0x00000] in <filename unknown>:0 
06-14 16:35:58.451: I/Unity(16683):   at UnityEngine.AndroidJavaClass..ctor (System.String className) [0x00000] in <filename unknown>:0 
06-14 16:35:58.451: I/Unity(16683):   at GooglePlayGames.Native.NativeClient.LaunchBridgeIntent (IntPtr bridge

**Comment by claywilkinson** [comment] 2015-06-15 06:27
NativeBridgeActivity not found, sounds like the native libraries are not being included in your project correctly.  Can you delete the plugins directory and re-import the plugin?

**Comment by claywilkinson** [comment] 2015-08-04 21:12
@vanustwo  - Are you still having issues?  OK if I close this issue?  Thanks!

**Comment by claywilkinson** [comment] 2015-09-12 02:11
closing since there has been no activity.  please re-open if this was not the problem.

**Closed by claywilkinson** 2015-09-12 02:11 UTC

**Comment by oddgames-david** [comment] 2016-03-07 00:08
I'm battling this one right now, google play ui pops up for logging in and show's me actually logged in but it shows this native bridge error.

Let you know if I fix it.

**Comment by claudiojundi** [comment] 2016-05-05 16:56
same here 

using the newest GooglePlayGamesPlugin-0.9.32

**Comment by claudiojundi** [comment] 2016-05-05 18:01
Same Here with the GooglePlayGamesPlugin-0.9.32
Unity 5.3.4

----OnLeaderboardClick-----

(Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
[Play Games Plugin DLL] 05/05/16 14:54:33 -03:00 DEBUG: ShowLeaderboardUI with default ID

(Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
[Play Games Plugin DLL] 05/05/16 14:54:33 -03:00 DEBUG: ShowLeaderboardUI, lbId= callback is 

(Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
[Play Games Plugin DLL] 05/05/16 14:54:33 -03:00 DEBUG: Entering internal callback for AndroidPlatformConfiguration#InternalIntentHandler

(Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
 *** [Play Games Plugin DLL] 05/05/16 14:54:33 -03:00 ERROR: Exception launching bridge intent: java.lang.ClassNotFoundException: com.google.games.bridge.NativeBridgeActivity


(Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
 *** [Play Games Plugin DLL] 05/05/16 14:54:33 -03:00 ERROR: UnityEngine.AndroidJavaException: java.lang.ClassNotFoundException: com.google.games.bridge.NativeBridgeActivity
 java.lang.ClassNotFoundException: com.google.games.bridge.NativeBridgeActivity
     at java.lang.Class.classForName(Native Method)
     at java.lang.Class.forName(Class.java:324)
    at java.lang.Class.forName(Class.java:285)
     at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
    at com.unity3d.player.UnityPlayer.a(Unknown Source)
   at com.unity3d.player.UnityPlayer$b.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.games.bridge.NativeBridgeActivity" on path: DexPathList[[zip file "/data/app/com.jsassaki.thecircle-1/base.apk"],nativeLibraryDirectories=[/data/app/com.jsassaki.thecircle-1/lib/arm, /data/app/com.jsassaki.thecircle-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)

**Comment by claudiojundi** [comment] 2016-05-23 14:23
Up

**Comment by claudiojundi** [comment] 2016-05-23 14:24
Please open this topic

**Comment by ikitae** [comment] 2017-05-29 16:55
Same issue on 
unity 5.6.1 
plugin 0.9.38a

**Comment by claywilkinson** [comment] 2017-05-30 14:32
@ikitae  -please open a different issue since you are using a different version of the plugin.  Also include a log of the problem.
